- src/utils/reducerUtils.js
Ellers får man bare spinner på møtebehovsiden, siden man aldri har forsøkt å hente møtebehov.
> Check if tilgang is false when checking harForsoktHentetMotebehov

- src/components/sykmeldinger/SykmeldingTeaser.js
> Fix SM status text in sykmelding list

- src/utils/sykmeldinger/sykmeldingParser.js
- test/mockdata/sykmeldinger/mockOldSykmeldinger.js
- test/utils/sykmeldingParserTest.js
Sykmeldingvisningen for selvstendig næringsdrivende (og kanskje frilansere) feiler i modia. Dette skal fikse de tilfellene hvor vi ikke har svar på `fravaersperioder`-spørsmålet.
> Get empty array if sporsmal of type perioder is null

- mock/data/motebehov.json
- mock/data/veilederoppgaver.json
- src/components/GlobalNavigasjon.js
- src/components/motebehov/BehandleMotebehovKnapp.js
- src/components/motebehov/Motebehov.js
- src/containers/GlobalNavigasjonContainer.js
- src/containers/MotebehovContainer.js
- src/utils/motebehovUtils.js
- src/utils/veilederoppgaverUtils.js
- test/utils/motebehovUtilsTest.js
Use harUbehandletMotebehov util to decide if prikk is needed.
> Don't show/behandle veilederoppgaver of type motebehov.

- mock/data/sykmeldinger.json
- src/utils/sykmeldinger/sykmeldingParser.js
- test/mockdata/sykmeldinger/mockOldSykmeldinger.js
- test/mockdata/sykmeldinger/mockSykmeldingExtraInfo.js
- test/mockdata/sykmeldinger/mockSykmeldinger.js
- test/utils/sykmeldingParserTest.js
Dette kommer nå fra backend, så da kan vi ta det inn for å være mest mulig klare til sykmeldte faktisk har muligheten til å benytte seg av tjenesten.
Selve visningen kommer litt etter hvert, siden det gjenstår noen avklaringer på hvordan ting skal se ut.
> Map info about egenmeldt sykmelding

- src/routers/AppRouter.js
Change landing page from Historikk to Sykmeldinger to let NKS find Sykmelding-info faster
> Change landing page

- mock/data/ledere.json
- src/components/personkort/PersonkortElement.js
- src/components/personkort/PersonkortLedere.js
- src/components/personkort/PersonkortVisning.js
- src/styles/_personKort.less
- src/utils/ledereUtils.js
- src/utils/sykmeldinger/sykmeldingUtils.js
- test/components/personkort/PersonkortVisningTest.js
- test/mockdata/mockLedere.js
- test/utils/ledereUtilsTest.js
Also sort ledere so that ledere for virksomheter with active sykmelding comes first.
> Add label to ledere in virksomheter with active sykmelding

- package-lock.json
- src/components/sykmeldingstatuspanel/BekreftetSykmeldingStatuspanel.js
- src/utils/index.js
Fordi da vil det være likt som på Ditt Sykefravær
> Change title text for statusPanel for bekreftet sykmeldinger

- src/utils/sykmeldinger/sykmeldingParser.js
- test/mockdata/sykmeldinger/mockOldSykmeldinger.js
- test/mockdata/sykmeldinger/mockSykmeldingExtraInfo.js
- test/mockdata/sykmeldinger/mockSykmeldinger.js
- test/utils/sykmeldingParserTest.js
Gjør klar for å markere de sykmeldingene som opprinnelig var på papir
> Add papirsykmelding field to old sykmelding

- src/mote/TextField.js
- src/mote/skjema/MotebookingSkjema.js
Validation of length prevents attemps to write MoteSted to database with a length that exceeds the limit of the field(255 chars).
> Add validation for length of MoteSted with limit 200

- src/utils/sykmeldinger/sykmeldingUtils.js
- test/utils/sykmeldingUtilsTest.js
Replace check for list of Diagnosekoder R991 and U071 with property harRedusertArbeidsgiverperiode
> Replace check for Corona-Diagnosekode

- package-lock.json
- src/components/historikk/Historikk.js
- src/index.js
- src/utils/globals.js
- remove mysterious globals
- fix import
- update package lock
> Fiks syfomodiaperson

- package-lock.json
- package.json
- src/mote/components/MotebookingStatus.js
Ved å bruke "panel" får vi en hvit boks inne i `AlertStripe`, rundt teksten, det ser ikke fint ut.
> Fix alertstripe

- src/utils/sykmeldinger/sykmeldingParser.js
- test/mockdata/sykmeldinger/mockSykmeldingExtraInfo.js
- test/utils/sykmeldingParserTest.js
Her feilet det når lege ikke hadde fylt ut alle underpunktene til pkt 6.2
> Add null check foreach field in utdypende opplysninger

- src/reducers/flaggperson.ts
Sett felter til false når state oppdateres, slik at ikke alle felter til slutt er true
> Fix flaggPerson reducer

- .gitignore
- src/components/pengestopp/PengestoppModal.tsx
- src/sagas/flaggPersonSagas.ts
- tsconfig.json
- add floobit files to gitignore
- updates to tsconfig and webpack for better debugging
- display error msg if failing to change status
> display error fetch

- mock/mockIspengestopp.js
- server.js
- src/actions/flaggperson_actions.ts
- src/api/index.js
- src/components/pengestopp/Pengestopp.tsx
- src/components/pengestopp/PengestoppModal.tsx
- src/containers/SykmeldingerContainer.js
- src/reducers/flaggperson.ts
- src/sagas/flaggPersonSagas.ts
- src/utils/pengestoppUtils.ts
Legg til interface for FlaggPersonState
Oppdater redux state for flaggperson manuelt etter lagring av status i stedet for å hente fra backend
Bruk StatusEndring som type for data i statusHentet action, i stedet for string
> Show error message when fetching status failed

- mock/mockSyfosoknad.js
- src/components/sykmelding/SykmeldingSide.js
- src/containers/DinSykmeldingContainer.js
- src/containers/SykepengesoknadContainer.js
- src/containers/SykepengesoknaderContainer.js
- src/containers/SykmeldingerContainer.js
- src/sagas/soknaderSagas.js
- src/sagas/sykepengesoknaderSagas.js
- src/selectors/toggleSelectors.js
- test/containers/SykepengesoknadContainerTest.js
Disse trenger vi ikke, siden vi ønsker å ha samme oppførsel lokalt som ute i miljø
> Remove !erDev checks

- src/components/Motelandingsside.js
- src/components/MotelandingssidePrikk.tsx
- src/containers/MotelandingssideContainer.js
- src/utils/GlobalNavigasjonUtils.js
Vis prikk på linkene også, slik at veiledere vet om oppgaven gjelder møtebehov eller møteplanlegger.
> Add prikk to links on motelandingsside if unfinished tasks

- src/components/TextDropdown.tsx
- src/components/pengestopp/TemporaryPengestopp.tsx
Da kan den brukes flere steder.
Den har dukket opp i flere skisser nå, så da blir den nok snart tatt i bruk.
> Make TextDropdown generic

- package-lock.json
Fordi den hadde et sikkerhetshull
```
High            Prototype Pollution in node-forge
Package         node-forge
Dependency of   webpack-dev-server [dev]
Path            webpack-dev-server > selfsigned > node-forge
More info       https://npmjs.com/advisories/1561
```
> Bump node-forge

- src/components/oppfoelgingsdialoger/OppfoelgingsPlanerOversikt.js
- src/components/oppfolgingsplan/lps/BehandleOppfolgingsplanLPS.js
- src/components/oppfolgingsplan/lps/OppfolgingsplanerOversiktLPS.js
- src/styles/_ikoner.less
- src/utils/datoUtils.js
- test/utils/datoUtilsTest.js
> Bedre respons på marker som behandlet (LPS)

- mock/data/mockPersonAdresse.js
- src/components/sykmelding/sykmeldingOpplysninger/DineSykmeldingOpplysninger.js
- src/components/sykmelding/sykmeldingOpplysninger/SykmeldingCheckbox.js
- src/components/sykmelding/sykmeldingOpplysninger/SykmeldingNokkelOpplysning.js
- src/components/sykmelding/sykmeldingOpplysninger/SykmeldingPeriode.js
- src/components/sykmelding/sykmeldingOpplysninger/SykmeldingPerioder.js
- src/components/sykmelding/sykmeldingOpplysninger/flereopplysninger/AndreSykmeldingOpplysninger.js
- src/components/sykmelding/sykmeldingOpplysninger/flereopplysninger/BedreArbeidsevne.js
- src/components/sykmelding/sykmeldingOpplysninger/flereopplysninger/FlereOpplysninger.js
- src/components/sykmelding/sykmeldingOpplysninger/flereopplysninger/Friskmelding.js
- src/components/sykmelding/sykmeldingOpplysninger/flereopplysninger/MeldingTilArbeidsgiver.js
- src/components/sykmelding/sykmeldingOpplysninger/flereopplysninger/MeldingTilNAV.js
- src/components/sykmelding/sykmeldingOpplysninger/flereopplysninger/MulighetForArbeid.js
- src/components/sykmelding/sykmeldingOpplysninger/flereopplysninger/SykmeldingOpplysning.js
- src/components/sykmelding/sykmeldingOpplysninger/flereopplysninger/Tilbakedatering.js
- src/components/sykmelding/sykmeldingOpplysninger/flereopplysninger/UtdypendeOpplysninger.js
- src/utils/sykmeldingUtils.js
Move components for sykmeldingOpplysninger in from Digisyfo-npm to make it easier to make changes in these components
> Move components in from digisyfo-npm

- src/reducers/ledere.js
- src/utils/ledereUtils.js
- test/utils/ledereUtilsTest.js
Bruk fom på neste leder som tom-dato
> Set tom date on all ledere in a virksomhet except the latest

- src/components/pengestopp/Pengestopp.tsx
- src/components/pengestopp/PengestoppDropdown.tsx
- src/components/pengestopp/PengestoppModal.tsx
- src/data/pengestopp/types/FlaggPerson.ts
- src/utils/pengestoppUtils.ts
Add Arsaksvelger to Pengestopp, but toggle off in dev/prod.
> Add Arsaksvelger to Pengestopp

- package-lock.json
- package.json
- src/components/speiling/sykepengsoknader/soknader/SoknadTeaser.js
All imports from digisyfo-npm are now replace and the package is therefore removed.
> Remove unused digisyfo-npm

- src/components/vedtak/VedtakUnselected.tsx
Fikser at ikonet på vedtaksseksjonen blir megastort.
> add width and align center

- .github/workflows/dispatch.yaml
- package-lock.json
Bygger appen først hvis docker-image ikke bygget fra før
> Add install and build step

- src/components/mote/components/Motelandingsside.tsx
- src/components/mote/container/MotelandingssideContainer.js
- src/components/motebehov/Motebehov.tsx
- src/components/motebehov/MotebehovKvittering.tsx
- src/components/motebehov/MotebehovSide.tsx
- src/routers/AppRouter.tsx
- src/styles/_motebehovKvittering.less
- src/styles/_motelandingsside.less
- Møtebehovside: Legger til overskrift og flytter behandlet-knapp inn.
- Flytter Møtebehovside inn i Møtelandingsside.
Fortsetter med konvertering av MotelandingssideContainer.js til typescript i videre PR.
> Move motebehov into motelandingsside

- mock/data/mockMotebehov.js
- package-lock.json
- src/components/InfoRow.tsx
- src/components/Layout.tsx
- src/components/Prediksjon/PrediksjonVisning.tsx
- src/components/mote/components/DialogmotePanel.tsx
- src/components/mote/components/Motelandingsside.tsx
- src/components/mote/components/innkalling/DialogmoteMoteStatusPanel.tsx
- src/components/mote/components/innkalling/InnkallingDialogmotePanel.tsx
- src/components/mote/components/innkalling/Moteplanleggeren.tsx
- src/components/mote/components/innkalling/NyttDialogMote.tsx
- src/components/mote/components/innkalling/SeMoteStatus.tsx
- src/components/motebehov/BehandleMotebehovKnapp.tsx
- src/components/motebehov/DialogmoteOnskePanel.tsx
- src/components/motebehov/MotebehovKvittering.tsx
- src/components/utdragFraSykefravaeret/UtdragFraSykefravaeret.tsx
- src/data/mote/moter_hooks.ts
Dette er da visning av dm2 møtestatus på landingssiden, uten noe redux, api eller annet - for å ha en start på gui.
> DM2 Møtestatus første utgave uten state

- package.json
- src/components/dialogmote/DialogmoteInnkallingSkjema.tsx
- src/data/dialogmote/dialogmoteTypes.ts
- test/dialogmote/DialogmoteInnkallingSkjemaTest.tsx
Sender foreløpig tom liste for innkalling inntil forhåndsvisning er implementert. Fikset samtidig test-script slik at også .tsx-tester kjøres.
> Add empty list for innkalling to dto

- server.js
- src/data/dialogmote/dialogmoteSagas.ts
Simplify url generation and set parseReqBody to false to avoid issues with insufficient memory due to large body
> Fix proxy for requests to Isdialogmote

- mock/mockData.js
- mock/syfomoteadmin/mockSyfomoteadmin.js
Fikset slik at mockSyfomoteadmin kan endre tilstand på mote-mockdata som tidligere
> Fix mutable moter mockdata

- mock/isdialogmote/mockIsdialogmote.js
- mock/mockData.js
- src/components/dialogmote/DialogmoteInnkallingSkjema.tsx
- src/components/dialogmote/DialogmoteInnkallingTekster.tsx
- src/components/dialogmote/avlys/AvlysDialogmoteBegrunnelse.tsx
- src/components/dialogmote/avlys/AvlysDialogmoteContainer.tsx
- src/components/dialogmote/avlys/AvlysDialogmoteSkjema.tsx
- src/components/dialogmote/avlys/AvlysDialogmoteSkjemaSeksjon.tsx
- src/components/dialogmote/avlys/DialogmoteInfo.tsx
- src/components/mote/components/innkalling/DialogmoteMoteStatusPanel.tsx
- src/data/dialogmote/dialogmote.ts
- src/data/dialogmote/dialogmoteSagas.ts
- src/data/dialogmote/dialogmoteTypes.ts
- src/data/dialogmote/dialogmote_actions.ts
- src/routers/AppRouter.tsx
- test/dialogmote/AvlysDialogmoteSkjemaTest.tsx
Første utkast til skjema for avlysning av dialogmøte uten forhåndsvisning.
> Avlys dialogmote

- src/components/dialogmote/referat/Buttonrow.tsx
- src/components/dialogmote/referat/Deltakere.tsx
- src/components/dialogmote/referat/Referat.tsx
- src/components/dialogmote/referat/Stillingsprosent.tsx
- src/data/sykmelding/sykmeldinger_hooks.ts
- src/hooks/useVeilederinfo.ts
- src/utils/sykmeldinger/sykmeldingUtils.ts
- test/utils/sykmeldingUtilsTest.js
Foreløpig ingen ekte funksjonalitet, knappene gjør ingenting.
Kun én tekstboks nå, så kan man utvide etter hvert.
Den har ingen egen side nå, man må koble den på et planlagt møte, slik at man kan komme til referat, og avbryte referat.
> Add Referat component for DM2

- .husky/pre-commit
- package-lock.json
- package.json
- src/data/logging/loggingHooks.ts
Slår sammen pageload tracking til 1 event, for å unngå spam av events, samt enklere fremvisning i dashboard.
Snek også med fiks på prettier pre-commit
> Amplitude endre pageload tracking

- src/colors.ts
- src/components/TextDropdown.tsx
- src/components/pengestopp/PengestoppHistorikk.tsx
- src/components/personkort/ledere/PersonKortVirksomhetHeader.tsx
- src/components/vedtak/VedtakEkspanderbartPanel.tsx
- src/components/vedtak/VedtakInfoBox.tsx
- src/components/vedtak/VedtakUnselected.tsx
- webpack.common.js
Henter fargene fra (https://design.nav.no/resources/colors) i styled components.
> Bruker navfarger i styled components

- src/components/personkort/Personkort.tsx
Hent fnr fra navBruker, og prøv å hent data når fnr endrer seg, da får vi hentet data når navBruker blir hentet.
Før prøvde vi kun én gang, og hvis vi ikke hadde navBruker enda, fikk vi aldri hentet den dataen vi ville ha.
> Fetch data in Personkort when fnr from navBruker is changed

- src/components/Utvidbar.js
- src/components/buttons/TrackedFareknapp.tsx
- src/components/buttons/TrackedFlatknapp.tsx
- src/components/buttons/TrackedHovedknapp.tsx
- src/components/buttons/TrackedKnapp.tsx
- src/components/motebehov/BehandleMotebehovKnapp.tsx
- src/components/motebehov/DialogmoteOnskePanel.tsx
- src/components/speiling/sykmeldinger/sykmeldinger/DineSykmeldinger.tsx
- src/components/speiling/sykmeldinger/sykmeldinger/SykmeldingTeaser.js
- src/components/speiling/sykmeldinger/sykmeldinger/SykmeldingTeasere.tsx
- src/components/utdragFraSykefravaeret/UtdragFraSykefravaeret.tsx
- src/data/logging/loggingHooks.ts
- src/sider/Side.tsx
- src/sider/SideFullbredde.tsx
Fikser i tillegg bug der track page load ikke fikk med seg redux default state ettersom tracking skjedde før state var lastet.
> Tracker åpning av sykmeldinger

- src/components/dialogmote/referat/Deltakere.tsx
- src/components/dialogmote/referat/DialogmoteReferatContainer.tsx
- src/components/dialogmote/referat/Referat.tsx
- src/components/dialogmote/referat/ReferatButtons.tsx
- test/dialogmote/ReferatTest.tsx
Glemte noen endringer som skulle med i forrige PR (https://github.com/navikt/syfomodiaperson/pull/316)
> Aktivert deltaker arbeidstaker checkbox, tracker send referat

- src/data/dialogmote/dialogmoteTexts.ts
- src/hooks/dialogmote/useForhandsvisAvlysning.ts
- src/hooks/dialogmote/useForhandsvisInnkalling.ts
- src/hooks/dialogmote/useForhandsvisningHilsen.ts
- test/dialogmote/DialogmoteInnkallingSkjemaTest.tsx
Byttet ut veileders epost og tlf med arbeidsgiver-tlf + mindre tekstjusteringer iht skisser
> Innkalling: tekstjusteringer

- src/components/dialogmote/referat/Deltakere.tsx
- src/components/dialogmote/referat/Referat.tsx
- src/utils/valideringUtils.ts
- test/dialogmote/AvlysDialogmoteSkjemaTest.tsx
- test/dialogmote/DialogmoteInnkallingSkjemaTest.tsx
- test/dialogmote/ReferatTest.tsx
- test/testUtils.ts
Fjernet deltaker-sjekkbokser og gjort nærmeste leder redigerbar. Utvidet test og refaktorert ut noe felleskode til testUtils.
Mulighet for å legge til ekstra deltakere kommer senere.
> Endringer i deltakere i referatet iht skisser

- cypress/integration/dialogmoter/ferdigstill-dialogmote.spec.ts
- mock/isdialogmote/mockIsdialogmote.ts
- src/components/dialogmote/referat/Referat.tsx
- src/components/dialogmote/referat/ReferatButtons.tsx
- src/components/dialogmote/referat/ReferatTextareaFieldColumn.tsx
- src/data/dialogmote/dialogmote.ts
- src/data/dialogmote/dialogmoteSagas.ts
- src/data/dialogmote/dialogmote_actions.ts
- src/data/dialogmote/types/dialogmoteReferatTypes.ts
- test/dialogmote/ReferatTest.tsx
Sender inn uten document - det kommer ifm forhåndsvisning senere.
> Submit referat ferdigstiller møte

- .eslintrc.js
- package-lock.json
- package.json
- src/components/Prediksjon/PrediksjonVisning.tsx
- src/components/dialogmote/DialogmoteSideContainer.tsx
- src/components/mote/components/Motelandingsside.tsx
- src/components/nokkelinformasjon/Nokkelinformasjon.tsx
- src/components/nokkelinformasjon/container/NokkelinformasjonContainer.tsx
- src/components/oppfolgingsplan/container/OppfoelgingsPlanerOversiktContainer.js
- src/components/oppfolgingsplan/container/OppfoelgingsplanContainer.js
- src/components/oppfolgingsplan/oppfoelgingsdialoger/Oppfolgingsplan.tsx
- src/components/oppfolgingsplan/oppfoelgingsdialoger/OppfolgingsplanerOversikt.tsx
- src/components/pengestopp/PengestoppModal.tsx
- src/components/personkort/Personkort.tsx
- src/components/speiling/sykepengsoknader/container/SykepengesoknaderSide.tsx
- src/components/speiling/sykmeldinger/container/DinSykmeldingContainer.tsx
- src/components/speiling/sykmeldinger/container/SykmeldingerContainer.tsx
- src/components/utdragFraSykefravaeret/UtdragOppfolgingsplaner.tsx
- src/components/vedtak/VedtakEkspanderbartPanel.tsx
- src/components/vedtak/container/VedtakContainer.tsx
- src/data/logging/loggingHooks.ts
- src/data/pengestopp/flaggperson_hooks.ts
- src/decorator/Decorator.tsx
- src/routers/AppRouter.tsx
- src/sider/Side.tsx
- src/sider/SideFullbredde.tsx
Dukket opp feil i Sentry med evig loop, som skyldes hooks. 
La til eslint hooks rules for å sikre dette litt bedre i fremtiden, og fikset opp i de tingene som den klagde på.
> Fix some bugs

- cypress/integration/dialogmoter/avlys-dialogmoter.spec.ts
- cypress/integration/dialogmoter/ferdigstill-dialogmote.spec.ts
- cypress/integration/dialogmoter/motelandingsside.spec.ts
- cypress/support/constants.ts
- src/components/dialogmote/Forhandsvisning.tsx
- src/components/dialogmote/avlys/AvlysDialogmoteSkjema.tsx
- src/components/dialogmote/endre/EndreDialogmoteSkjema.tsx
- src/components/dialogmote/endre/EndreDialogmoteTekster.tsx
- src/components/dialogmote/innkalling/DialogmoteInnkallingSkjema.tsx
- src/components/dialogmote/innkalling/DialogmoteInnkallingTekster.tsx
- src/components/dialogmote/motehistorikk/MotehistorikkPanel.tsx
- src/components/dialogmote/referat/Referat.tsx
- src/components/dialogmote/referat/StandardTekster.tsx
- src/data/dialogmote/dialogmoteTexts.ts
- src/data/dialogmote/types/dialogmoteTypes.ts
- src/hooks/dialogmote/useForhandsvisAvlysning.ts
- src/hooks/dialogmote/useForhandsvisInnkalling.ts
- src/hooks/dialogmote/useForhandsvisReferat.ts
- src/hooks/dialogmote/useForhandsvisTidSted.ts
- src/utils/documentComponentUtils.ts
- test/dialogmote/AvlysDialogmoteSkjemaTest.tsx
- test/dialogmote/DialogmoteInnkallingSkjemaTest.tsx
- test/dialogmote/ForhandsvisningTest.tsx
- test/dialogmote/ReferatTest.tsx
- test/dialogmote/dialogmoteTextsTest.ts
Forhåndsvisning av referatet inkl. alle standardtekster med nøkler. Også gjort litt refaktorering av Forhandsvisning-komponenten og renamet funksjoner i forhandsvisning-hooks.
> Preview referat

- src/components/dialogmote/innkalling/DialogmoteInnkallingTekster.tsx
- src/components/dialogmote/innkalling/DialogmoteInnkallingTeksterAlert.tsx
- src/hooks/dialogmote/useForhandsvisAvlysning.ts
- src/hooks/dialogmote/useForhandsvisTidSted.ts
- src/utils/datoUtils.js
- test/dialogmote/AvlysDialogmoteSkjemaTest.tsx
- test/utils/datoUtilsTest.js
Justeringer iht skisser:
- Endringer i info-boksen i innkalling
- Dato-tid-format i brevene
> Dm2 text adjustments

- src/components/pengestopp/PengestoppModal.tsx
Aktivitetskrav has been moved in the law from paragraph 8-4 to paragraph 8-8.
> Update text for SykepengestoppArsak AKTIVITETSKRAV

- server.js
Ispengestopp has been moved from namespace default to team namespace teamsykefravr
> Update namespace of Ispengestopp

- cypress/integration/dialogmoter/motelandingsside.spec.ts
- cypress/support/constants.ts
- package-lock.json
- package.json
- src/components/mote/components/Motelandingsside.tsx
- src/components/mote/components/innkalling/NyttDialogMote.tsx
- src/data/unleash/unleash.ts
..fikk evig loading av møteplanleggersiden dersom veilederinfo returnerte 500 fra server.
> Laster nå frem møteplanleggerside uten at veilederinfo er lastet

- server.js
Syfobehandlendeenhet has been moved from namespace default to team namespace teamsykefravr
> Update namespace of Syfobehandlendeenhet

- server.js
Modiasyforest has been moved from namespace default to team namespace teamsykefravr
> Update namespace of Modiasyforest

- server.js
Ispersonoppgave has been moved from namespace default to team namespace teamsykefravr
> Update namespace of Ispersonoppgave

- server.js
Syfomotebehov has been moved from namespace default to team namespace teamsykefravr
> Update namespace of Syfomotebehov

- mock/ispersonoppgave/mockIspersonoppgave.ts
- server.js
- src/data/personoppgave/personoppgaveSagas.ts
Makes requests to Ispersonoppgave with token in bearer header instead of token in cookie
> Change authentication for requests to Ispersonoppgave

- .nais/naiserator-dev.yaml
- .nais/naiserator-prod.yaml
- public/index.html
- server/config.js
- server/proxy.js
Enable fetching of internarbeidsflatedecorator from laptop with naisdevice and use correct version of internarbeidsflatedecorator in dev-fss.
> Update dev and prod url of internarbeidsflatedecorator

- .env.template
- .nais/naiserator-dev.yaml
- .nais/naiserator-prod.yaml
Update to clientId provisioned by azurerator in AzureAD
> Update clientId of Syfoveileder

- src/components/BrukerKanIkkeVarslesText.tsx
- src/components/SideLaster.tsx
- src/components/dialogmote/BrukerKanIkkeVarslesPapirpostAdvarsel.tsx
- src/components/dialogmote/DialogmoteSideContainer.tsx
- src/components/dialogmote/innkalling/DialogmoteInnkallingContainer.tsx
- src/components/mote/components/innkalling/InnkallingDialogmotePanel.tsx
- src/components/mote/components/innkalling/Moteplanleggeren.tsx
- src/components/mote/components/innkalling/NyttDialogMote.tsx
- src/data/unleash/unleash_hooks.ts
- test/dialogmote/InnkallingDialogmotePanelTest.tsx
> Lagt til advarsel-boks om papirbrev på dialogmote-sider (avhengig av feature toggle)

- src/components/mote/skjema/FlereTidspunktSkjema.js
- src/components/mote/skjema/MotebookingSkjema.js
Har ikke fått til å gjenskape feilene rapportert i https://sentry.gc.nav.no/organizations/nav/issues/?environment=Production&project=84&query=is%3Aunresolved. Sånn koden fungerer så skal det valideres at verdiene ikke er undefined før man får sendt inn skjema. Legger på et par undefined-sjekker for sikkerhets skyld.
> Lagt på undefined-sjekker

- mock/isdialogmelding/behandlereDialogmeldingMock.ts
- src/data/behandlerdialogmelding/BehandlerDialogmeldingDTO.ts
- test/dialogmote/DialogmoteInnkallingSkjemaTest.tsx
Justert iht https://github.com/navikt/isdialogmelding/pull/29. Merges samtidig med denne.
> Justert BehandlerDialogmeldingDTO

- cypress/integration/dialogmoter/endre-dialogmoter.spec.ts
- src/components/dialogmote/avlys/AvlysDialogmoteSkjema.tsx
- src/components/dialogmote/endre/EndreDialogmoteSkjema.tsx
- src/components/dialogmote/endre/EndreDialogmoteTekster.tsx
- src/data/dialogmote/dialogmoteTexts.ts
- src/hooks/dialogmote/useForhandsvisAvlysning.ts
- src/hooks/dialogmote/useForhandsvisTidSted.ts
- src/utils/valideringUtils.ts
Lager tester i videre PR (med endringer fra https://github.com/navikt/syfomodiaperson/pull/477)
> Add behandler med tekster og begrunnelse til avlysning/endring 

- package-lock.json
- package.json
- src/components/personkort/Personkort.tsx
- src/components/personkort/SnowButton.tsx
- src/utils/festiveUtils.ts
Vis snø i 10 sekunder når man trykker på knappen.
Kun vis knappen hvis det er desember.
> Add button for snow in december

- src/hooks/dialogmote/useForhandsvisAvlysning.ts
- src/hooks/dialogmote/useForhandsvisInnkalling.ts
- src/hooks/dialogmote/useForhandsvisTidSted.ts
- src/hooks/dialogmote/useForhandsvisningIntro.ts
- test/dialogmote/AvlysDialogmoteSkjemaTest.tsx
- test/dialogmote/EndreDialogmoteSkjemaTest.tsx
For innkalling/avlysning/endring skal brevene starte med:
- til AT: Hei Artig Trane
- til NL og lege: Gjelder Artig Trane, f.nr. 12345678912
> Konsistent intro i innkalling/endre/avlys

- src/components/dialogmote/referat/BehandlersOppgave.tsx
- src/components/dialogmote/referat/Deltakere.tsx
- src/components/dialogmote/referat/Referat.tsx
- src/data/dialogmote/dialogmoteTexts.ts
- src/data/dialogmote/types/dialogmoteReferatTypes.ts
- src/hooks/dialogmote/useForhandsvisReferat.ts
- src/hooks/dialogmote/useForhandsvisTidSted.ts
- src/utils/behandlerUtils.ts
- src/utils/valideringUtils.ts
- test/dialogmote/ReferatTest.tsx
- test/utils/valideringUtilsTest.ts
Vis behandler som deltaker i skjema og brev
Felt for behandlers oppgave i skjema og brev
> Referat med behandler

- src/components/dialogmote/avlys/AvlysDialogmoteSkjema.tsx
- src/components/dialogmote/endre/EndreDialogmoteSkjema.tsx
- src/components/dialogmote/innkalling/DialogmoteInnkallingSkjema.tsx
- src/components/dialogmote/referat/Referat.tsx
- src/utils/valideringUtils.ts
- test/dialogmote/AvlysDialogmoteSkjemaTest.tsx
- test/dialogmote/DialogmoteInnkallingSkjema/ArbeidsgiverInnkallingTest.tsx
- test/dialogmote/DialogmoteInnkallingSkjema/BehandlerInnkallingTest.tsx
- test/dialogmote/DialogmoteInnkallingSkjema/DialogmoteInnkallingSkjemaTest.tsx
- test/dialogmote/EndreDialogmoteSkjemaTest.tsx
- test/dialogmote/ReferatTest.tsx
- test/dialogmote/testData.ts
- test/testUtils.ts
- test/utils/valideringUtilsTest.ts
Refaktorert validering av fritekster. Tester på maks-lengde fritekstfelter, test på submit av innkalling med behandler. Rydding i tester slik at de bruker testdata.
> Validere maks-lengde fritekst behandler innkalling

- mock/data/vedtakMock.ts
- src/components/vedtak/VedtakOppsummering.tsx
- src/data/vedtak/vedtakTypes.ts
- Fix nullable property in VedtakType 
- Update deprecated properties of VedtakDTO
> Fix vedtakdto

- src/components/dialogmote/DeltakereSvarInfo.tsx
- test/dialogmote/DeltakereSvarInfoTest.tsx
> Endret tilbake til grønn hake hvis innkalling er åpnet. Fjernet tekst om gitt svar (venter til respons fra AT/NL er på plass)

- mock/data/dialogmoterMock.ts
- src/components/dialogmote/DeltakereSvarInfo.tsx
- src/components/mote/components/DialogmotePanel.tsx
- src/data/dialogmote/types/dialogmoteTypes.ts
- test/dialogmote/DeltakereSvarInfoBehandlerTest.tsx
- test/dialogmote/DeltakereSvarInfoTest.tsx
- test/dialogmote/testData.ts
> Vise svar fra behandler på innkalling

- cypress/integration/dialogmoter/motelandingsside.spec.ts
Testen feiler sporadisk på at den ikke får opp OAuth2Login-felter. Lagt på retries for å kurere problemet.
> Lagt til retries på flaky cypress-test

- mock/common/mockConstants.ts
- mock/data/behandlendeEnhetMock.ts
- mock/data/brukerinfoMock.ts
- mock/data/dialogmoterMock.ts
- mock/data/historikkmoterMock.ts
- mock/data/ledereMock.ts
- mock/data/motebehovMock.ts
- mock/data/moterMock.ts
- mock/data/oppfolgingstilfelleperioderMock.ts
- mock/data/sykmeldingerMock.ts
- mock/data/veilederMock.ts
- mock/fastlegerest/fastlegerMock.ts
- mock/ispengestopp/mockIspengestopp.ts
- mock/ispersonoppgave/mockIspersonoppgave.ts
- mock/modiacontextholder/mockModiacontextholder.ts
- mock/syfomoteadmin/mockSyfomoteadmin.ts
- mock/syfomotebehov/mockSyfomotebehov.ts
- mock/syfooppfolgingsplanservice/oppfolgingsplanLPSMock.ts
- mock/syfooppfolgingsplanservice/oppfolgingsplanMock.ts
Start to create mock constant for reuseability between mocks and/or tests.
> Reuse constants in mocks

- src/components/dialogmote/referat/Situasjon.tsx
> Increase character limit for Situasjon in referat

- src/utils/datoUtils.js
- src/utils/sykmeldinger/sykmeldingUtils.ts
- test/utils/datoUtilsTest.js
Ta høyde for dag i måneden når man regner ut antall måneder mellom datoer
> Show all sykmeldinger without status NY as tidligere

- src/components/dialogmote/innkalling/DialogmoteInnkallingSkjema.tsx
- src/hooks/dialogmote/useForhandsvisInnkalling.ts
- test/dialogmote/DialogmoteInnkallingSkjema/BehandlerInnkallingTest.tsx
- test/dialogmote/DialogmoteInnkallingSkjema/DialogmoteInnkallingPreviewTest.tsx
- test/dialogmote/DialogmoteInnkallingSkjema/DialogmoteInnkallingSkjemaTest.tsx
- test/dialogmote/testDataDocuments.ts
Innkallingen som ble sendt til arbeidstaker/nærmeste leder sa at behandler ikke var innkalt selv om behandler var det 😞
> Fixed missing behandler text in innkalling

- src/components/dialogmote/innkalling/DialogmoteInnkallingTekster.tsx
- test/dialogmote/DialogmoteInnkallingTeksterTest.tsx
> Advarsel over fritekster hvis bruker ikke kan varsles digitalt

- package-lock.json
- src/components/speiling/sykepengsoknader/container/SykepengesoknadContainer.tsx
- src/components/speiling/sykepengsoknader/soknad-arbeidstaker/KorrigertAv.tsx
- src/components/speiling/sykepengsoknader/soknad-felles-oppsummering/OppsummeringKvittering.tsx
- src/components/speiling/sykepengsoknader/soknad-felles-oppsummering/OppsummeringSporsmal.tsx
- src/components/speiling/sykepengsoknader/soknad-felles-oppsummering/OppsummeringTall.tsx
- src/components/speiling/sykepengsoknader/soknad-reisetilskudd/SykepengesoknadReisetilskudd.tsx
- src/components/speiling/sykepengsoknader/soknader/SoknadTeaser.tsx
- src/data/sykepengesoknad/types/SykepengesoknadDTO.ts
Create own Reisetilskudd soknad component, with correct title and without VaerKlarOverAt section.
Add case and oppsummering for Kvittering spørsmål.
Add SvarType BELOP and KILOMETER to tall.
Add SvarType DATOER to dato.
Fix bug in KorrigertAv where linked søknad was itself instead of actual newer søknad.
> Show soknader of type reisetilskudd

- src/components/mote/container/MotebookingContainer.tsx
Lagt til prop som forsvant i https://github.com/navikt/syfomodiaperson/pull/560
> Add missing fnr prop

- src/data/sykepengesoknad/sykepengesoknadQueryHooks.ts
- src/utils/sykepengesoknadUtils.ts
Lagt inn igjen parsingen av datoer som forsvant ved omskriving fra redux til react-query.
> Fix parsing av datoer på sykepengesoknad

- mock/fastlegerest/fastlegerMock.ts
- src/components/personkort/PersonkortLege.tsx
- src/data/fastlege/fastlegerQueryHooks.ts
- src/data/fastlege/types/Fastlege.ts
- test/components/personkort/PersonkortLegeTest.tsx
- test/data/fastlegerQueryHooksTest.tsx
> Show Fastlege and FaslegeVikarer in Personkort

- src/components/Layout.tsx
- src/components/utdragFraSykefravaeret/UtdragFraSykefravaeret.tsx
- src/components/utdragFraSykefravaeret/UtdragOppfolgingsplaner.tsx
- src/components/vedtak/SpinnsynLenke.tsx
- src/components/vedtak/container/VedtakContainer.tsx
- test/components/UtdragFraSykefravaeretTest.tsx
- test/containers/VedtakContainerTest.tsx
> Lenke til vedtak hos Flex fra Nøkkelinformasjon og Vedtak

- src/components/motebehov/BehandleMotebehovKnapp.tsx
- src/data/motebehov/useBehandleMotebehov.ts
Oppdaterer motebehov når kallet har fullført og gått bra. Refetcher møtebehov neste gang komponenten rendres.
> Simplify behandle motebehov mutation

- src/components/dialogmote/innkalling/DialogmoteInnkallingSkjema.tsx
- src/data/dialogmote/types/dialogmoteTypes.ts
- test/dialogmote/DialogmoteInnkallingSkjema/BehandlerInnkallingTest.tsx
- test/dialogmote/DialogmoteInnkallingSkjema/DialogmoteInnkallingSkjemaTest.tsx
Feltet brukes ikke i isdialogmote
> Remove tildeltEnhet from innkalling

- mock/common/mockConstants.ts
- mock/data/sykmeldingerMock.ts
- src/utils/sykmeldinger/sykmeldingUtils.ts
- test/mockdata/mockLedere.js
Fix bug with isSykmedingActiveToday causing the function to return false when tom is today.
> Bugfix PersonkortLedere Virskomhet without NarmesteLeder

- mock/data/dialogmoterMock.ts
- src/components/Layout.tsx
- src/components/dialogmote/referat/AndreDeltakere.tsx
- src/components/dialogmote/referat/Deltakere.tsx
- src/components/dialogmote/referat/Referat.tsx
- src/data/dialogmote/types/dialogmoteReferatTypes.ts
- src/data/dialogmote/types/dialogmoteTypes.ts
- src/hooks/dialogmote/useForhandsvisReferat.ts
- src/hooks/dialogmote/useInitialValuesReferat.ts
- src/utils/behandlerUtils.ts
- src/utils/valideringUtils.ts
- test/dialogmote/ReferatMellomlagreTest.tsx
- test/dialogmote/ReferatTest.tsx
- test/dialogmote/testData.ts
- test/dialogmote/testDataDocuments.ts
- test/testUtils.ts
> DM2 referat: Redesign av deltakerliste + behandler oppmøte/motta referat

- src/components/historikk/HistorikkEventItem.tsx
- src/components/historikk/container/HistorikkContainer.tsx
- src/data/historikk/historikk.ts
- src/data/historikk/historikkQueryHooks.ts
- src/data/historikk/historikkSagas.ts
- src/data/historikk/historikk_actions.ts
- src/data/historikk/historikk_hooks.ts
- src/data/historikk/types/historikkTypes.ts
- src/data/mote/moterSagas.ts
- test/data/historikkQueryHooksTest.tsx
- test/stubs/stubSyfomotebehov.ts
- test/stubs/stubSyfooppfolgingsplan.ts
Avventer møte-historikk til vi fjerner møteplanlegger-kode
> Bruker react query for historikk motebehov og oppfolgingsplaner

- src/hooks/dialogmote/useForhandsvisningHilsen.ts
- test/dialogmote/testDataDocuments.ts
Endrer hilsen til:
```
Vennlig hilsen
Kari Saksbehandler
NAV
```
> Fjern behandlende enhet fra hilsen i brev

- cypress/integration/dialogmoter/motelandingsside.spec.ts
- mock/unleash/mockUnleash.ts
- src/components/dialogmote/innkalling/DialogmoteInnkallingContainer.tsx
- src/components/mote/components/innkalling/InnkallingDialogmotePanel.tsx
- src/data/unleash/unleash_types.ts
- test/dialogmote/DialogmoteInnkallingContainerTest.tsx
- test/dialogmote/InnkallingDialogmotePanelTest.tsx
Enable Dialogmoteinnkalling for all user by removing toggle syfo.syfomodiaperson.dm2.
> Enable Dialogmoteinnkalling for all users

- mock/data/dialogmoterMock.ts
- src/components/dialogmote/motehistorikk/MotehistorikkPanel.tsx
- src/components/mote/components/innkalling/DialogmoteMoteStatusPanel.tsx
- src/data/dialogmote/types/dialogmoteTypes.ts
- src/hooks/dialogmote/useDialogmoteReferat.ts
- src/hooks/dialogmote/useInitialValuesReferat.ts
- test/dialogmote/MotehistorikkTest.tsx
- test/dialogmote/testData.ts
Foreløpig vil lista kun ha 0 eller 1 element.
Iht endringene i isdialogmote: https://github.com/navikt/isdialogmote/pull/261
> Endret til å bruke referatList i dto

- cypress/integration/dialogmoter/avlys-dialogmoter.spec.ts
- cypress/integration/dialogmoter/endre-dialogmoter.spec.ts
- cypress/integration/dialogmoter/ferdigstill-dialogmote.spec.ts
- cypress/integration/dialogmoter/innkalling-dialogmote.spec.ts
- cypress/integration/dialogmoter/motelandingsside.spec.ts
- cypress/support/index.ts
- cypress/support/motelandingsside-commands.ts
- mock/common/mockConstants.ts
- mock/data/ledereMock.ts
- mock/data/oppfolgingstilfellePersonMock.ts
- mock/data/sykmeldingerMock.ts
- mock/data/virksomhetMock.ts
- mock/syfomoteadmin/mockSyfomoteadmin.ts
- src/components/dialogmote/DeltakereSvarInfo.tsx
- src/components/dialogmote/FritekstSeksjon.tsx
- src/components/dialogmote/endre/EndreDialogmoteTekster.tsx
- src/components/dialogmote/innkalling/DialogmoteInnkallingVelgArbeidsgiver.tsx
- src/components/mote/NoNarmestLederAlert.tsx
- src/components/mote/components/innkalling/DialogmoteMoteStatusPanel.tsx
- src/components/mote/skjema/ArbeidsgiverDropdown.tsx
- src/utils/ledereUtils.ts
- test/dialogmote/DialogmoteInnkallingContainerTest.tsx
- test/dialogmote/DialogmoteInnkallingSkjema/DialogmoteInnkallingSkjemaTest.tsx
- test/dialogmote/testData.ts
- test/testQueryClient.ts
Vis alertstripe i innkalling og endring om at vi sender til Altinn, hvis nærmeste leder ikke er registrert.
Vis "Ingen leder" i dropdown for respons fra arbeidsgiver på statussiden.
Co-authored-by: June Henriksen <june.henriksen2@nav.no>
> Show virksomheter with no leader in møteinnkalling

- mock/data/dialogmoterMock.ts
- mock/isdialogmote/mockIsdialogmote.ts
- src/components/dialogmote/motehistorikk/MotehistorikkPanel.tsx
- src/components/dialogmote/referat/DialogmoteReferatContainer.tsx
- src/components/dialogmote/referat/Referat.tsx
- src/components/dialogmote/referat/ReferatFritekster.tsx
- src/components/mote/components/innkalling/DialogmoteMoteStatusPanel.tsx
- src/data/dialogmote/dialogmoteTexts.ts
- src/data/dialogmote/types/dialogmoteReferatTypes.ts
- src/data/dialogmote/useEndreReferat.ts
- src/hooks/dialogmote/useDialogmoteReferat.ts
- src/hooks/dialogmote/useForhandsvisReferat.ts
- src/hooks/dialogmote/useInitialValuesReferat.ts
- test/dialogmote/DialogmoteMoteStatusPanelTest.tsx
- test/dialogmote/ReferatEndreTest.tsx
- test/dialogmote/ReferatMellomlagreTest.tsx
- test/dialogmote/ReferatTest.tsx
- test/dialogmote/testData.ts
- test/dialogmote/testDataDocuments.ts
Tilpasninger i møtelandingsside med inngang til endre-skjema + historikk kommer i PR etter denne.
> Tilpasset referat-skjema til endring av referat

- src/components/dialogmote/motehistorikk/MotehistorikkPanel.tsx
- src/hooks/dialogmote/useDialogmoteReferat.ts
- test/dialogmote/MotehistorikkTest.tsx
> Designjusteringer historikk og visning av flere referater

- img/ImageComponents.ts
- img/svg/bluedocument.svg
- src/components/dialogmote/DialogmoteFerdigstilteReferatPanel.tsx
- src/components/dialogmote/referat/DialogmoteEndreReferatContainer.tsx
- src/components/mote/components/Motelandingsside.tsx
- src/data/dialogmote/types/dialogmoteReferatTypes.ts
- src/hooks/dialogmote/useInitialValuesReferat.ts
- src/routers/AppRouter.tsx
- src/utils/datoUtils.js
- test/components/BrodsmulerTest.tsx
- test/components/DatovelgerTest.tsx
- test/dialogmote/DialogmoteFerdigstilteReferatPanelTest.tsx
- test/dialogmote/DialogmoteMoteStatusPanelTest.tsx
- test/dialogmote/InnkallingDialogmotePanelTest.tsx
- test/dialogmote/ReferatEndreTest.tsx
- test/dialogmote/ReferatMellomlagreTest.tsx
- test/dialogmote/ReferatTest.tsx
- test/dialogmote/testData.ts
- test/testUtils.ts
> Endre referat fra møte-landingsside

- src/api/errors.ts
Unngår evig redirect til login dersom man ikke har aktiv bruker i Modia
> Ignore login required errors

- src/components/Easter.tsx
Den var litt rar og fungerte ikke hvis man bytte fanen i global navigasjon, men nå ser det ut til å være greit.
> Fix broken gif replay on mouse click

- src/components/dialogmote/Forhandsvisning.tsx
Se skisser https://www.figma.com/file/L6DPvt6dU1XzypeiQoQ54C/MODIA-Person?node-id=2392%3A343
> Use Systemtittel (h2) for HeaderH2 component + adjust padding

- src/utils/festiveUtils.ts
Nå er det påske fra kl 12 6. april
> Update easter definition

- src/components/dialogmote/endre/EndreDialogmoteSkjema.tsx
- src/components/dialogmote/innkalling/DialogmoteInnkallingSkjema.tsx
- src/data/dialogmote/types/dialogmoteTypes.ts
- src/data/dialogmote/types/skjemaTypes.ts
- src/hooks/dialogmote/useSkjemaValuesToDto.ts
- src/utils/documentComponentUtils.ts
- test/dialogmote/DialogmoteInnkallingSkjema/DialogmoteInnkallingSkjemaTest.tsx
- test/dialogmote/EndreDialogmoteSkjemaTest.tsx
Refaktorert til hook for mapping fra tid-sted-skjemafelter til dto (inkl trimming)
> Trim videolink i dto og documentcomponents som sendes til api

- src/utils/frnValideringUtils.ts
- test/utils/fnrValideringUtilsTest.ts
Godta både fra NAV (+40 på måned) og fra Skatteetaten (+80 på måned).
Kun godkjent hvis man er i preprod.
> Allow synthetic IDs

- mock/unleash/mockUnleash.ts
Reuse string constants of unleash toggles in mock.
> Refactor MockUnleash

- mock/isdialogmotekandidat/dialogmotekandidatMock.ts
- mock/isdialogmotekandidat/mockIsdialogmotekandidat.ts
- mock/mockEndepunkter.ts
- src/apiConstants.ts
- src/data/dialogmotekandidat/dialogmotekandidatQueryHooks.ts
- src/data/dialogmotekandidat/dialogmotekandidatTypes.ts
- test/dialogmote/InnkallingDialogmotePanelTest.tsx
- test/stubs/stubIsdialogmotekandidat.ts
- test/testUtils.ts
Get Kandidat for PersonIdent from Isdialogmotekandidat and only show view of Dialogmoteunntak if PersonIdent is Kandidat for Dialogmote
> Only show view of Dialogmoteunntak if PersonIdent is Kandidat

- src/data/unleash/unleash_types.ts
Change name of toggle to be reused across multiple applications.
> Change name of toggle for Dialogmotekandidat

- src/components/personkort/Personkort.tsx
- src/utils/festiveUtils.ts
> Add decoration for Pride Oslo week

- src/data/dialogmote/dialogmoteTexts.ts
Align text with information on Nav.no
> Update text about Oppfolgingstiltak

- .github/workflows/cypress.yaml.txt
- .github/workflows/dispatch.yaml
- .github/workflows/main.yaml
- docker-compose.yaml
- start-dev.sh
Fix ImagePullBackOff issues when deploying
> Migrate docker workflows to ghcr

- mock/syfoperson/brukerinfoMock.ts
- src/components/dialogmote/DialogmoteSideContainer.tsx
- src/components/dialogmote/innkalling/DialogmoteInnkallingContainer.tsx
- src/components/dialogmote/innkalling/DialogmoteInnkallingTekster.tsx
- src/components/mote/components/innkalling/InnkallingDialogmotePanel.tsx
- src/data/navbruker/navbrukerQueryHooks.ts
- src/data/navbruker/navbruker_hooks.ts
- src/data/navbruker/types/BrukerinfoDTO.ts
- test/dialogmote/DialogmoteInnkallingTeksterTest.tsx
- test/dialogmote/InnkallingDialogmotePanelTest.tsx
Vis frem varsel om reservasjon i Kontakt- og reservasjonsregisteret
> Use correct brukerinfo dto

- src/components/motebehov/BehandleMotebehovKnapp.tsx
Confetti får syfomodiaperson til å krasje - antakelig etter oppgradering til React 18
> Remove confetti for now

- src/components/endresykmelding/EndreSykmelding.tsx
vi tenker å prodsette dette på mandag, dev kan kjøres ut med en gang :smiley:
> oppdater URL til nye smregistrering-ingresser

- mock/isoppfolgingstilfelle/oppfolgingstilfellePersonMock.ts
- src/data/oppfolgingstilfelle/person/oppfolgingstilfellePersonQueryHooks.ts
Hvis flere tilfeller har samme startdato, legger vi det med senest sluttdato først.
> Improve sorting of oppfolgingstilfelle

- mock/isdialogmelding/behandlereDialogmeldingMock.ts
- mock/isdialogmelding/mockIsdialogmelding.ts
- package-lock.json
- package.json
- server/routes/unleashRoutes.ts
- src/api/axios.ts
- src/components/dialogmote/innkalling/BehandlerRadioGruppe.tsx
- src/components/dialogmote/innkalling/BehandlerSearch.tsx
- src/components/dialogmote/innkalling/BehandlerSearchResult.tsx
- src/data/behandler/behandlereQueryHooks.ts
- src/data/unleash/unleash_types.ts
- test/dialogmote/DialogmoteInnkallingBehandlerTest.tsx
Unleashed in prod. 
Co-authored-by: Eirik Dahlen <eirik.dahlen@nav.no>
> Add search field for behandler

- src/components/dialogmote/innkalling/DialogmoteInnkallingContainer.tsx
- test/dialogmote/DialogmoteInnkallingContainerTest.tsx
Nå er innkalling kun tilgjengelig i modia, så da trenger vi ikke denne alerten.
> Remove unneeded alert about new vs old system

- src/components/dialogmote/innkalling/BehandlerSearch.tsx
- src/components/dialogmote/innkalling/BehandlerSearchResult.tsx
Sett maks bredde på søk og resultat, så de er like lange. Maks høyde på søkeresultat, med scroll.
Co-authored-by: Eirik Dahlen <eirik.dahlen@nav.no>
> Make behandler search result scrollable

- src/components/dialogmote/innkalling/BehandlerRadioGruppe.tsx
- src/components/dialogmote/innkalling/BehandlerSearch.tsx
- src/components/dialogmote/innkalling/DialogmoteInnkallingBehandler.tsx
- src/components/dialogmote/innkalling/DialogmoteInnkallingSkjema.tsx
- src/utils/valideringUtils.ts
- test/dialogmote/DialogmoteInnkallingBehandlerTest.tsx
- test/dialogmote/DialogmoteInnkallingSkjema/DialogmoteInnkallingSkjemaTest.tsx
- test/testQueryClient.ts
Sjekk at man faktisk har valgt en behandler, hvis man velger "Legg til en behandler". Man får ikke feil hvis ingen radioknapper er huket av.
Co-authored-by: Eirik Dahlen <eirik.dahlen@nav.no>
> Validate behandler choice in DM2-innkalling

- src/components/dialogmote/innkalling/virksomhet/DialogmoteInnkallingVelgArbeidsgiver.tsx
- src/components/dialogmote/innkalling/virksomhet/VirksomhetChooser.tsx
- src/components/dialogmote/innkalling/virksomhet/VirksomhetRadioGruppe.tsx
- test/dialogmote/DialogmoteInnkallingVelgBehandler/DialogmoteInnkallingVelgBehandlerTest.tsx
> Allow virksomhetinput when tilfelle exist

- src/components/dialogmote/DialogmoteTidOgSted.tsx
- src/utils/datoUtils.js
- test/utils/datoUtilsTest.js
Frist vises nå kun dersom brukeren er en kandidat for DM2.
Ser slik ut:
> Add frist for dm2 in innkalling

- src/components/personkort/Personkort.tsx
- src/components/personkort/PersonkortHeader.tsx
- src/styles/_personKort.less
Co-authored-by: June Henriksen <june.henriksen2@nav.no>
> Use EkspanderbartPanel instead of Utvidbar

- mock/common/mockConstants.ts
- mock/syfobehandlendeenhet/behandlendeEnhetMock.ts
- mock/syfobehandlendeenhet/mockSyfobehandlendeenhet.ts
- mock/util/requestUtil.ts
- src/components/personkort/PersonkortChangeEnhet.tsx
- src/components/personkort/PersonkortEnhet.tsx
- src/components/personkort/useChangeEnhet.tsx
- src/data/behandlendeenhet/types/BehandlendeEnhet.ts
- test/components/personkort/PersonkortEnhetTest.tsx
- test/setup.js
- test/stubs/stubSyfobehandlendeEnhet.ts
> Add button for changing enhet to NAV Utland

- src/components/motebehov/MulighetForArbeid.tsx
- src/components/motebehov/Perioder.tsx
- src/components/utdragFraSykefravaeret/UtdragFraSykefravaeret.tsx
- src/components/utdragFraSykefravaeret/UtdragOppfolgingsplaner.tsx
- src/styles/_sykmeldingMotebehovVisning.less
- src/styles/_utdragFraSykefravaeret.less
I tillegg er det enkelte estetiske endringer som følge av dette.
> Change from Utvidbar to Ekspanderbartpanel

- server/routes/unleashRoutes.ts
Etter ønske fra teknisk fika om bedre kontroll på togglene våre.
Blir seende slik ut:
> Add new unleash-strategy by environment

- server/routes/unleashRoutes.ts
Etter ønske fra teknisk fika om bedre kontroll på togglene våre.
> Add new unleash-strategy by enhet

- package-lock.json
- package.json
https://devblogs.microsoft.com/typescript/announcing-typescript-4-9/
> Upgrade typescript

- src/components/personkort/PersonkortHeader/SyketilfelleSummary.tsx
- src/components/personkort/PersonkortHeader/Varighet.tsx
- src/utils/datoUtils.js
> Add syketilfelle varighet to Syketilfellesummery

- src/components/personkort/PersonkortHeader/Diagnosekode.tsx
Show diagnosekode from the latest sykmelding, including if the latest is 
a new, and thus not active, sykmelding.
> Show diagnosekode from ny sykmelding

- src/components/dialogmote/innkalling/DialogmoteInnkallingContainer.tsx
- test/dialogmote/DialogmoteInnkallingContainerTest.tsx
Endrer testen slik at vi bare rendrer komponenten som testes. Da slipper vi å rendre Side med Personkortet som feiler pga lasting av julemusikk i testen 🤷‍♂️
> Fix test failing due to xmas

- src/components/aktivitetskrav/AktivitetskravContainer.tsx
- src/components/aktivitetskrav/AktivitetskravPanel.tsx
- src/components/aktivitetskrav/AktivitetskravSide.tsx
- src/components/aktivitetskrav/vurdering/AktivitetskravVurderingAlert.tsx
- src/components/aktivitetskrav/vurdering/VurderAktivitetskrav.tsx
- src/components/aktivitetskrav/vurdering/VurderAktivitetskravButtons.tsx
- src/data/aktivitetskrav/aktivitetskravQueryHooks.ts
- test/aktivitetskrav/AktivitetskravSideTest.tsx
- test/aktivitetskrav/testDataUtils.ts
Aktivitetskrav-side med knapper som ikke gjør noe + alertstriper for siste vurdering.
> Begynt på aktivitetskrav-side

- src/components/aktivitetskrav/vurdering/OppfyltAktivitetskravSkjema.tsx
- src/components/aktivitetskrav/vurdering/VurderAktivitetskravArsakRadioGruppe.tsx
- src/components/aktivitetskrav/vurdering/VurderAktivitetskravSkjemaButtons.tsx
- src/data/aktivitetskrav/aktivitetskravTexts.ts
- src/data/aktivitetskrav/aktivitetskravTypes.ts
- test/aktivitetskrav/VurderAktivitetskravTest.tsx
- test/aktivitetskrav/testDataUtils.ts
Forenklet også visning av valideringsfeil i modal: Dropper SkjemaFeiloppsummering siden det kun er to felter i "skjema" og valideringsfeil-link ikke fungerer så bra med radioknapper.
> Lagt til årsak-radiogruppe i Oppfylt-modal

- mock/isdialogmotekandidat/mockIsdialogmotekandidat.ts
- src/data/dialogmotekandidat/dialogmoteunntakQueryHooks.ts
Ref https://github.com/navikt/isdialogmotekandidat/pull/95
> Renamed hackathon api

- server/routes/unleashRoutes.ts
- src/components/personkort/PersonkortHeader/PersonkortHeader.tsx
- src/data/oppfolgingstilfelle/person/oppfolgingstilfellePersonQueryHooks.ts
- src/data/unleash/unleash_types.ts
- src/utils/datoUtils.js
- src/utils/oppfolgingstilfelleUtils.ts
- test/aktivitetskrav/testDataUtils.ts
- test/components/personkort/PersonkortHeaderTest.tsx
- test/utils/datoUtilsTest.js
- test/utils/oppfolgingstilfelleUtilsTest.ts
Co-authored-by: June Henriksen <june.henriksen2@nav.no>
> Add icon to personkort when innbygger has gjentakende sykefravar

- src/components/aktivitetskrav/AktivitetskravContainer.tsx
- src/components/aktivitetskrav/AktivitetskravPanel.tsx
- src/components/aktivitetskrav/AktivitetskravSide.tsx
- src/components/mote/components/Motelandingsside.tsx
- src/components/nokkelinformasjon/Nokkelinformasjon.tsx
- src/components/nokkelinformasjon/container/NokkelinformasjonContainer.tsx
- src/components/utdragFraSykefravaeret/UtdragFraSykefravaeret.tsx
- test/aktivitetskrav/AktivitetskravSideTest.tsx
- test/components/UtdragFraSykefravaeretTest.tsx
> Utdrag fra sykefraværet i aktivitetskrav

- src/components/nokkelinformasjon/SyketilfelleList.tsx
- src/components/sykmeldingsgrad/Sykmeldingsgrad.tsx
- src/data/oppfolgingstilfelle/person/oppfolgingstilfellePersonQueryHooks.ts
- src/utils/oppfolgingstilfelleUtils.ts
- test/utils/oppfolgingstilfelleUtilsTest.ts
> Show start and end of ten last oppfolgingstilfeller

- mock/isaktivitetskrav/aktivitetskravMock.ts
- src/components/aktivitetskrav/AktivitetskravSide.tsx
- src/components/aktivitetskrav/historikk/AktivitetskravHistorikk.tsx
- test/aktivitetskrav/AktivitetskravHistorikkTest.tsx
- test/aktivitetskrav/testDataUtils.ts
> Historikk på aktivitetskrav

- mock/isdialogmote/dialogmoterMock.ts
- src/components/mote/components/innkalling/DialogmoteMoteStatusPanel.tsx
- src/components/mote/components/innkalling/VurderOppgaveForDialogmotesvarKnapp.tsx
- src/utils/dialogmoteUtils.ts
Also change behandle oppgave text.
Co-authored-by: June Henriksen <june.henriksen2@nav.no>
> Allow behandling of motesvaroppgave when behandler changes response

- src/components/aktivitetskrav/AktivitetskravSide.tsx
- src/components/aktivitetskrav/vurdering/VurderAktivitetskrav.tsx
- src/components/aktivitetskrav/vurdering/VurderAktivitetskravButtons.tsx
- test/aktivitetskrav/AktivitetskravSideTest.tsx
- test/aktivitetskrav/VurderAktivitetskravTest.tsx
Også lagt på tekst som viser datoer for oppfølgingstilfellet aktivitetskravet gjelder.
> Skal kunne vurdere siste aktivitetskrav (også om det ikke gjelder siste oppfølgingstilfelle)

- src/components/aktivitetskrav/historikk/AktivitetskravHistorikk.tsx
- src/components/aktivitetskrav/vurdering/AktivitetskravVurderingAlert.tsx
- src/components/aktivitetskrav/vurdering/AvventAktivitetskravSkjema.tsx
- src/components/aktivitetskrav/vurdering/IkkeOppfyltAktivitetskravSkjema.tsx
- src/components/aktivitetskrav/vurdering/OppfyltAktivitetskravSkjema.tsx
- src/components/aktivitetskrav/vurdering/UnntakAktivitetskravSkjema.tsx
- src/components/aktivitetskrav/vurdering/VurderAktivitetskravButtons.tsx
- src/components/aktivitetskrav/vurdering/VurderAktivitetskravModal.tsx
- src/components/aktivitetskrav/vurdering/VurderAktivitetskravSkjema.tsx
- src/data/aktivitetskrav/aktivitetskravTypes.ts
- src/hooks/aktivitetskrav/useAktivitetskravVurderingSkjema.ts
- test/aktivitetskrav/AktivitetskravHistorikkTest.tsx
- test/aktivitetskrav/AktivitetskravSideTest.tsx
- test/aktivitetskrav/VurderAktivitetskravTest.tsx
- test/testDataUtils.ts
> Vurder aktivitetskrav Ikke oppfylt

- src/components/aktivitetskrav/vurdering/VurderAktivitetskrav.tsx
- test/aktivitetskrav/VurderAktivitetskravTest.tsx
> Hjelpetekst tooltip i vurder aktivitetskrav

- package-lock.json
- package.json
- src/components/dialogmote/referat/Referat.tsx
- src/utils/datoUtils.js
- test/dialogmote/ReferatEndreTest.tsx
- test/dialogmote/ReferatMellomlagreTest.tsx
- test/dialogmote/ReferatTest.tsx
Debounce is ignoring signals that happen too often, to avoid spamming isdialogmote.
Save referat 5 seconds after last change, or after max 20 seconds.
> Auto save referat after every change, with debounce

- src/components/dialogmote/referat/Referat.tsx
Now it should be a bit easier to read.
> Change isLoading check in Referat with De Morgan's law

- src/components/nokkelinformasjon/SyketilfelleList.tsx
- src/components/sykmeldingsgrad/Sykmeldingsgrad.tsx
- src/utils/sykmeldinger/sykmeldingUtils.ts
- test/utils/sykmeldingUtilsTest.ts
Use small radio buttons to allow veileder to choose.
Only include sykmeldinger that started within the tilfelle, instead of all that started after tilfelle start.
> Change graf when user chooses different tilfelle in list

- .nais/naiserator-dev.yaml
- .nais/naiserator-prod.yaml
Ref https://trello.com/c/FkW6EYQZ/1232-endringer-i-default-brukertilganger-for-azure-ad-apper
> allowAllUsers true

- src/components/dialogmote/referat/Referat.tsx
Only some fields are relevant when checking emptyness, since some fields are always filled. This will also stop saving automatically when opening the form for the first time. (We will still auto save when opening the referat and already saved text exists.)
> Don't auto save referat if it's empty.

- mock/syfoperson/brukerinfoMock.ts
- src/components/personkort/PersonkortHeader/PersonkortHeader.tsx
- src/data/navbruker/navbrukerQueryHooks.ts
- src/data/navbruker/types/BrukerinfoDTO.ts
- test/components/personkort/PersonkortHeaderTest.tsx
- test/stubs/stubSyfoperson.ts
> Show label with date of death in Personkort

- mock/isaktivitetskrav/aktivitetskravMock.ts
- src/components/aktivitetskrav/vurdering/AktivitetskravVurderingAlert.tsx
> Remove empty space from avventer alertstripe

- package-lock.json
- package.json
For å kunne ta i bruk https://aksel.nav.no/komponenter/core/datepicker til Aktivitetskrav - Avventer-datovelger
> Upgrade new designssystem deps

- src/components/aktivitetskrav/vurdering/AktivitetskravVurderingAlert.tsx
- src/data/aktivitetskrav/aktivitetskravTypes.ts
- test/aktivitetskrav/AktivitetskravSideTest.tsx
- test/testDataUtils.ts
> Show "Avventer til" in vurdering alert

- .nais/naiserator-dev.yaml
- src/components/behandlerdialog/meldingtilbehandler/MeldingTilBehandlerSkjema.tsx
- src/data/behandlerdialog/behandlerdialogQueryHooks.ts
- src/data/behandlerdialog/behandlerdialogTypes.ts
- src/data/behandlerdialog/useMeldingTilBehandler.tsx
- test/behandlerdialog/MeldingTilBehandlerTest.tsx
- test/setup.js
- test/testQueryClient.ts
Endring som gjør selve POST-kallet til backenden.
Har også snakket med designerne om at vi må ha en eller annen slags bekreftelse og evt clear form når man sender inn. Men vil ta det i egen PR.
Funker å sende melding i dev! ✅ 🎉
> Add send melding POST-mutation

- src/components/aktivitetskrav/vurdering/AktivitetskravVurderingAlert.tsx
- test/aktivitetskrav/AktivitetskravSideTest.tsx
- test/testDataUtils.ts
Viser ingen dato for de som har status Avventer uten frist når vi skrur på frist i prod.
> Don't show vurdering createdAt for avventer when frist toggled on

- package-lock.json
- server/routes/unleashRoutes.ts
- src/components/nokkelinformasjon/SyketilfelleList.tsx
- src/data/unleash/unleash_types.ts
- src/utils/sykmeldinger/sykmeldingUtils.ts
- test/utils/sykmeldingUtilsTest.ts
> Show diagnosekode next to tilfeller in sykmeldingsgrad

- src/components/behandlerdialog/meldingtilbehandler/MeldingTilBehandlerSkjema.tsx
- src/data/behandlerdialog/behandlerMeldingTexts.ts
- src/data/behandlerdialog/behandlerdialogTypes.ts
- src/hooks/behandlerdialog/document/useMeldingTilBehandlerDocument.ts
- test/behandlerdialog/MeldingTilBehandlerTest.tsx
- test/behandlerdialog/testDataDocuments.ts
Basert på hvordan pdf-eksempelet ser ut her: https://github.com/navikt/dialogmeldingpdfgen/pull/3#issuecomment-1486671558
> Add preview melding til behandler and post document-components

- mock/isbehandlerdialog/behandlerdialogMock.ts
- src/components/behandlerdialog/meldinger/Samtaler.tsx
- test/behandlerdialog/MeldingerTest.tsx
> Add GuidePanel for when there are no meldinger on person

- src/components/dialogmote/referat/Referat.tsx
> Use info AlertStripe instead of warning on referat page

- src/components/dialogmote/referat/ReferatInfoColumn.tsx
> Use gray background on help text panels in referat

- .github/workflows/dispatch.yaml
- .github/workflows/main.yaml
- .github/workflows/redis.yaml
- .nais/naiserator-dev.yaml
- .nais/naiserator-prod.yaml
- .nais/redis/redis.yaml
- mock/sykepengesoknad/mockSykepengesoknadBackend.ts
- server/auth/utils.ts
- server/config.ts
- server/proxy.ts
- src/apiConstants.ts
- src/data/sykepengesoknad/sykepengesoknadQueryHooks.ts
- test/stubs/stubSykepengesoknadBackend.ts
Tar en stund før denne kan merges (det er mange app'er som må få tilpasset inbound rules)
> Migrate gcp

- src/data/behandlerdialog/behandlerMeldingTexts.ts
- src/hooks/behandlerdialog/document/useMeldingTilBehandlerDocument.ts
- test/behandlerdialog/testDataDocuments.ts
Iht https://trello.com/c/tbsZMlGp/1350-avklare-innhold-som-skal-f%C3%B8lge-med-en-dialogmelding-takst-rett-til-klage-ikke-oppgi-for-mye-opplysninger-etc
> Update behandlerMelding texts

- src/components/endresykmelding/EndreSykmelding.tsx
Also change the order of the ternary so prod url is the default.
> Change to new ingress intern.dev

- src/components/SkjemaInnsendingFeil.tsx
- src/components/behandler/BehandlerAlert.tsx
- src/components/behandlerdialog/meldingtilbehandler/MeldingTilBehandler.tsx
- src/components/behandlerdialog/meldingtilbehandler/MeldingTilBehandlerSkjema.tsx
- test/behandlerdialog/MeldingTilBehandlerTest.tsx
Og byttet ut noen gamle alertstriper med nytt DS alert
> Add alert info i skriv til behandler

- mock/isbehandlerdialog/behandlerdialogMock.ts
- src/components/aktivitetskrav/AktivitetskravSide.tsx
- src/components/behandlerdialog/meldinger/MeldingInnholdPanel.tsx
- src/components/behandlerdialog/meldinger/VisMelding.tsx
- src/data/behandlerdialog/behandlerdialogTypes.ts
- test/behandlerdialog/MeldingerTest.tsx
> Melding fra behandler: Vedlegg-tekst

- .env.template
- .nais/naiserator-dev.yaml
- .nais/naiserator-prod.yaml
- mock/esyfovarsel/mockEsyfovarsel.ts
- mock/mockEndepunkter.ts
- server/config.ts
- server/proxy.ts
- src/apiConstants.ts
- src/data/maksdato/useMaksdatoQuery.ts
- test/data/maksdatoQueryTest.tsx
- test/stubs/stubEsyfovarsel.ts
Tar i bruk query og viser i personkortet når https://github.com/navikt/esyfovarsel/pull/286/ er klar
> Setup code for fetching maksdato from esyfovarsel

- src/components/personkort/PersonkortHeader/Diagnosekode.tsx
- src/components/personkort/PersonkortHeader/Maksdato.tsx
- src/components/personkort/PersonkortHeader/PersonkortHeader.tsx
- src/components/personkort/PersonkortHeader/SyketilfelleSummary.tsx
- src/components/personkort/PersonkortHeader/TilfellePeriod.tsx
- src/components/personkort/PersonkortHeader/Varighet.tsx
- test/components/personkort/PersonkortHeaderTest.tsx
OBS: Vent med å merge denne til esyfo-apiet er i prod: https://github.com/navikt/esyfovarsel/pull/286
> Show maksdato in personkort header

- mock/isbehandlerdialog/behandlerdialogMock.ts
- mock/ispersonoppgave/personoppgaveMock.ts
- src/components/behandlerdialog/meldinger/MeldingerISamtale.tsx
- src/components/behandlerdialog/meldinger/SamtaleAccordion.tsx
- src/components/behandlerdialog/meldinger/SamtaleTags.tsx
- src/data/behandlerdialog/behandlerdialogTypes.ts
- src/utils/personOppgaveUtils.ts
- test/behandlerdialog/MeldingerTest.tsx
> Tags for status på samtaler

- src/data/dialogmote/dialogmoteTexts.ts
Se https://trello.com/c/JCX4KIwM/1156-endring-i-brevtekster-innkalling
> Adjust innkalling and referat texts

- src/components/behandlerdialog/meldingtilbehandler/MeldingTilBehandler.tsx
- test/behandlerdialog/MeldingTilBehandlerTest.tsx
> Justere tekst om takst og endre til warning

- mock/isbehandlerdialog/behandlerdialogMock.ts
- src/components/behandlerdialog/meldinger/MeldingInnholdPanel.tsx
- src/components/behandlerdialog/meldinger/SamtaleTags.tsx
- src/components/behandlerdialog/paminnelse/PaminnelseWarningIcon.tsx
- src/data/behandlerdialog/behandlerdialogTypes.ts
- src/utils/documentComponentUtils.ts
- test/behandlerdialog/MeldingerTest.tsx
- test/behandlerdialog/meldingTestdataGenerator.ts
> Vis påminnelse-overskrift i samtale (med ikon) + påminnelse-tag

- src/components/DocumentComponentVisning.tsx
- src/components/Forhandsvisning.tsx
- src/components/behandlerdialog/paminnelse/PaminnelseMelding.tsx
- test/behandlerdialog/PaminnelseTest.tsx
Knappen "Send påminnelse til behandler" skal åpne modal med forhåndsvisning av påminnelsen og knapper for å sende eller avbryte.
> Vis og send påminnelse

- src/utils/festiveUtils.ts
- test/utils/festiveUtilsTest.ts
Matches dates for Oslo Pride 2023
Add tests
> Update pride dates

- mock/isbehandlerdialog/behandlerdialogMock.ts
- src/components/behandlerdialog/meldinger/MeldingInnholdPanel.tsx
- src/components/behandlerdialog/meldingtilbehandler/SelectMeldingType.tsx
- src/data/behandlerdialog/behandlerdialogTexts.ts
- test/behandlerdialog/MeldingTilBehandlerTest.tsx
- test/behandlerdialog/MeldingerTest.tsx
- test/behandlerdialog/meldingTestdataGenerator.ts
> Viser meldingstype med takst i MeldingInnholdPanel-detaljer

- mock/isbehandlerdialog/behandlerdialogMock.ts
- src/components/behandlerdialog/legeerklaring/ReturLegeerklaringWarningIcon.tsx
- src/components/behandlerdialog/meldinger/MeldingInnholdPanel.tsx
- src/components/behandlerdialog/meldinger/SamtaleTags.tsx
- test/behandlerdialog/MeldingerTest.tsx
- test/behandlerdialog/SamtalerTagsTest.tsx
- test/behandlerdialog/meldingTestdataGenerator.ts
- test/utils/behandlerdialogUtils.ts
> Retur sendt tag og ikon på samtale

- src/components/behandlerdialog/meldingtilbehandler/MeldingTilBehandlerSkjema.tsx
Endrer makslengde på behandlermeldinger til 5000
> Endre lengde på behandlermelding

- README.md
Legger til info om event tracking i amplitude og feature toggling i unleash.
> IS: Add info on amplitude and unleash

- mock/isbehandlerdialog/behandlerdialogMock.ts
- src/components/behandlerdialog/meldinger/PdfVedleggLink.tsx
- src/data/behandlerdialog/behandlerdialogTypes.ts
Merge etter https://github.com/navikt/isbehandlerdialog/pull/126
> Use isFirstVedleggLegeerklaring

- src/components/aktivitetskrav/historikk/AktivitetskravHistorikk.tsx
- src/components/aktivitetskrav/vurdering/AktivitetskravVurderingAlert.tsx
- src/components/aktivitetskrav/vurdering/VurderAktivitetskravModal.tsx
- src/data/aktivitetskrav/aktivitetskravTypes.ts
Må håndtere ny status for aktivitetskrav som lukkes ifm høstdugnad :fallen_leaf:
> Add aktivitetskrav-status LUKKET

- src/components/aktivitetskrav/AktivitetskravAlertstripe.tsx
- src/components/aktivitetskrav/vurdering/AktivitetskravVurderingAlert.tsx
- test/aktivitetskrav/AktivitetskravSideTest.tsx
- test/testDataUtils.ts
> Add success alert for forhandsvarsel

- mock/isaktivitetskrav/aktivitetskravMock.ts
- src/components/aktivitetskrav/vurdering/AktivitetskravVurderingAlert.tsx
- src/data/aktivitetskrav/aktivitetskravTypes.ts
- test/aktivitetskrav/AktivitetskravSideTest.tsx
- test/testDataUtils.ts
Fikset slik at vi bruker svarfrist-feltet knyttet til forhåndsvarselet i alert.
> IS-1640 use forhandsvarsel frist

- src/components/globalnavigasjon/GlobalNavigasjon.tsx
- src/utils/amplitude.ts
Legger til navigering i menyen slik at vi kan få et fullt bilde av hvordan bevegelsesmønsteret til brukerne våre er.
> IS: Legg til navigere event for navigering i sidemenyen

- src/api/axios.ts
- src/components/huskelapp/HuskelappModal.tsx
- src/data/huskelapp/useRemoveHuskelapp.tsx
- test/huskelapp/HuskelappModalTest.tsx
- test/setup.js
- test/stubs/stubIshuskelapp.ts
Implementert knapp som fjerner huskelapp på person
> IS-1664: Knapp for å fjerne huskelapp

- mock/ispersonoppgave/personoppgaveMock.ts
- src/components/aktivitetskrav/vurdering/AktivitetskravVurderingAlert.tsx
- test/aktivitetskrav/AktivitetskravSideTest.tsx
- test/aktivitetskrav/AktivitetskravVurderingAlertTest.tsx
Endrer alert som vises når siste vurdering er forhåndsvarsel. Viser først info om oppgave, deretter advarsel når ubehandlet vurder stans-oppgave finnes (fristen er utløpt).
> IS-1620: Forhandsvarsel alert info and warning

- src/components/personkort/Personkort.tsx
It doesn't work in veilederes browser.
> Remove halloween decoration

- src/components/aktivitetskrav/vurdering/SendForhandsvarselSkjema.tsx
- test/aktivitetskrav/VurderAktivitetskravTest.tsx
- test/aktivitetskrav/varselDocuments.ts
Refaktorert til react-hook-form i forhandsvarsel-skjema
> IS-1714: React hook form in forhandsvarsel

- src/components/personkort/OversiktLenker.tsx
Endret rekkefølgen på lenkene:
enhetens oversikt, min oversikt, mine møter -> min oversikt, enhetens oversikt, mine møter
> Change link order

- src/components/behandlerdialog/legeerklaring/ReturLegeerklaring.tsx
- test/behandlerdialog/ReturLegeerklaringTest.tsx
Migrert til react-hook-form i retur legeerklaring-skjema
> IS-1747: Retur legeerklaring react hook form

- src/components/aktivitetskrav/vurdering/AvventAktivitetskravSkjema.tsx
- test/aktivitetskrav/VurderAktivitetskravTest.tsx
- Fjernet at begrunnelse feltet er obligatorisk for avvent vurdering
> IS-1727: Remove mandatory begrunnelse field for avvent vurdering

- src/components/aktivitetskrav/vurdering/OppfyltAktivitetskravSkjema.tsx
- src/components/aktivitetskrav/vurdering/SendForhandsvarselSkjema.tsx
- src/components/aktivitetskrav/vurdering/UnntakAktivitetskravSkjema.tsx
- test/aktivitetskrav/VurderAktivitetskravTest.tsx
- test/stubs/stubIsaktivitetskrav.ts
Fikk inn en Jira-sak om at verdiene i skjemaet ble værende etter innsending. Vi har jo tidligere hatt dette i modaler, og da trengte man ikke å cleare formet. Det funker ikke _helt_ ut av boksen, så vi må legge på noen defaultvalues som den kan resette seg tilbake til.
https://github.com/navikt/syfomodiaperson/assets/37441744/6ab266f9-8930-4f75-83da-fe159773c18d
> IS-1751: Reset aktkrav-form when submitting

- server/unleash.ts
Fjerner toggle som er skrudd på for alle i prod
> Remove unused toggle

- src/components/aktivitetskrav/historikk/AktivitetskravHistorikk.tsx
- src/components/aktivitetskrav/vurdering/AktivitetskravVurderingAlert.tsx
- src/data/aktivitetskrav/aktivitetskravTypes.ts
Legger til aktivitetskrav-status `NY_VURDERING`
> IS-1749: Add aktivitetskrav NY_VURDERING status

- mock/isaktivitetskrav/aktivitetskravMock.ts
- src/components/aktivitetskrav/AktivitetskravSide.tsx
- src/components/aktivitetskrav/vurdering/StartNyVurdering.tsx
- src/components/aktivitetskrav/vurdering/VurderAktivitetskrav.tsx
- src/data/aktivitetskrav/aktivitetskravTexts.ts
- src/data/aktivitetskrav/aktivitetskravTypes.ts
- src/data/aktivitetskrav/useCreateAktivitetskrav.ts
- src/utils/aktivitetskravUtils.ts
- test/aktivitetskrav/AktivitetskravSideTest.tsx
- test/aktivitetskrav/StartNyVurderingTest.tsx
- test/aktivitetskrav/VurderAktivitetskravTest.tsx
- test/testDataUtils.ts
- test/utils/aktivitetskravUtils.test.ts
Side for å starte ny vurdering av aktivitetskravet etter sluttilstand
NB: Merge etter https://github.com/navikt/syfomodiaperson/pull/1069
> IS-1676: Start ny vurdering når aktivitetskrav er i sluttilstand

- src/components/AktivBrukerTilgangLaster.tsx
- src/components/PersonsokSide.tsx
- src/components/SideLaster.tsx
- src/components/behandlerdialog/meldinger/AvvistMelding.tsx
- src/components/behandlerdialog/meldinger/SamtaleAccordionItem.tsx
- src/components/behandlerdialog/meldinger/SamtaleTags.tsx
- src/components/behandlerdialog/meldingtilbehandler/MeldingsTypeInfo.tsx
- src/components/dialogmote/motehistorikk/MotehistorikkPanel.tsx
- src/components/dialogmote/referat/ReferatButtons.tsx
- src/components/historikk/Historikk.tsx
- src/components/mote/components/Motelandingsside.tsx
- src/components/motebehov/BedreArbeidsevnen.tsx
- src/components/motebehov/SykmeldingMotebehovVisning.tsx
- src/components/motebehov/TilbakeIArbeid.tsx
- src/components/personkort/PersonkortHeader/MaksdatoSummary.tsx
- src/components/personkort/PersonkortHeader/PersonkortHeader.tsx
- src/components/speiling/sykepengsoknader/soknad-selvstendig/SykmeldingutdragForSelvstendige.tsx
- src/components/speiling/sykmeldinger/sykmeldingstatuspanel/SykmeldingStatuspanelOpplysning.tsx
- src/components/utdragFraSykefravaeret/UtdragFraSykefravaeret.tsx
- src/data/maksdato/useMaksdatoQuery.ts
- Håndhever flere tilfeller av linting regel `no-useless-fragments`.
- Har flere steder flyttet ut conditional rendering funksjonen for å gjøre det tydeligere om en komponent renderes eller ikke.
- Har også noen steder byttet ut `<></>` med `<div></div>` ettersom jeg ikke ville bruke masse tid på å finne en bedre løsning.
> IS-1757: Fix lint error in UtdragFraSykefravaeret

- src/components/aktivitetskrav/vurdering/AktivitetskravVurderingAlert.tsx
- Endrer tekst på infotekst som vises når forhåndsvarsel er sendt til noe Lisa foreslo var tydeligere
> IS-1808: Changed text

- mock/isaktivitetskrav/aktivitetskravMock.ts
- mock/isaktivitetskrav/mockIsaktivitetskrav.ts
- src/components/aktivitetskrav/AktivitetskravSide.tsx
- src/components/aktivitetskrav/VarselBrev.tsx
- src/components/aktivitetskrav/historikk/AktivitetskravHistorikk.tsx
- src/components/aktivitetskrav/vurdering/ForhandsvarselOppsummering.tsx
- test/aktivitetskrav/AktivitetskravSideTest.tsx
En oppsummeringsboks som dukker opp når man har sendt et forhåndsvarsel.
Med mye tekst i begrunnelsen:
> IS-1791: Add oppsummering av forhåndvarsel box

- server/unleash.ts
- src/components/motebehov/BehandleMotebehovKnapp.tsx
- src/data/unleash/unleash_types.ts
- Fjerner toggle kode for `isMotebehovTilbakemeldingEnabled`
> IS-1807: Remove toggle code

- server/unleash.ts
- src/components/aktivitetskrav/vurdering/VurderAktivitetskravTabs.tsx
- src/data/unleash/unleash_types.ts
- Sletter kode som henger sammen med toggle som styrer om man kan sende forhåndsvarsel (`isSendingAvForhandsvarselEnabled`)
> IS-1798: Remove toggle code

- src/components/dialogmote/motehistorikk/MoteHistorikkUnntak.tsx
- test/dialogmote/MotehistorikkTest.tsx
Plukket en veldig gammel veilederwin-lapp, der det var et behov for å vise hvilken veileder som hadde satt unntak for dialogmøte. Behovet dukket opp fordi den sykmeldte hadde flyttet, og veileder ville vite hvem som satt forrige unntak. 
OBS! Dette gjelder bare unntak, men vi burde kanskje hatt det for "Referat" også. Avlyst møte viser selve avlysningen (brevet) og der står veilederens navn på slutten under `Mvh ...`.
Mønsteret følger samme prinsipp som "Vurdert av" på aktivitetskrav, men jeg la også på identen til veilderen. Vet ikke om det er nødvendig, men men 🤷🏼‍♂️ Må ta en sjekk med Andrea om hun synes det ser greit ut også.
> IS-1541: Show veiledernavn and veilederident on historikk for unntak dialogmøte

- package-lock.json
- package.json
- src/components/LeggTilKnapp.tsx
- src/components/SlettKnapp.tsx
- src/components/dialogmote/DeltakereSvarInfo.tsx
- src/components/dialogmote/referat/Deltakere.tsx
- src/components/globalnavigasjon/VedtakMenypunkt.tsx
- src/components/motebehov/MulighetForArbeid.tsx
- src/components/nokkelinformasjon/SyketilfelleList.tsx
- src/components/personkort/PersonkortHeader/Diagnosekode.tsx
- src/components/personkort/PersonkortHeader/PersonkortHeader.tsx
- src/components/speiling/sykmeldinger/sykmeldinger/SykmeldingTeaser.tsx
- src/components/vedtak/SpinnsynLenke.tsx
- src/styles/_personKort.less
- test/dialogmote/ReferatMellomlagreTest.tsx
- test/dialogmote/ReferatTest.tsx
[ds-icons](https://www.npmjs.com/package/@navikt/ds-icons) er utdatert -> migrerer til [aksel-icons](https://www.npmjs.com/package/@navikt/aksel-icons)
> IS-1626: Use aksel-icons

- src/components/huskelapp/OpenHuskelappModalButton.tsx
- src/sider/Side.tsx
- Flytter knapp for huskelapp under navigasjon menyen.
- Legger også på ikon som er i nytt design.
> IS-1824: Move button

- src/components/ForhandsvisningModal.tsx
- src/components/aktivitetskrav/vurdering/AvventAktivitetskravSkjema.tsx
- src/components/aktivitetskrav/vurdering/IkkeAktuellAktivitetskravSkjema.tsx
- src/components/aktivitetskrav/vurdering/VurderAktivitetskravModal.tsx
- src/components/behandlerdialog/legeerklaring/ReturLegeerklaring.tsx
- src/components/behandlerdialog/paminnelse/PaminnelseMelding.tsx
- src/components/document/DocumentComponentHeaderH1.tsx
- src/components/document/DocumentComponentVisning.tsx
- src/hooks/behandlerdialog/document/useMeldingTilBehandlerDocument.ts
Videre arbeid etter https://github.com/navikt/syfomodiaperson/pull/1095
Forbedret bruk av Modal i aktivitetskrav og behandlerdialog.
- Bruker header avventer/ikke aktuell-modaler
- Bruker header og footer til knapper i retur og påminnelse-modaler.
> IS-1626 modal improvements

- src/components/motebehov/GenerellSykmeldingInfo.tsx
- test/components/UtdragFraSykefravaeretTest.tsx
Jeg hadde glemt å sjekke hvordan det så ut etter en refakturering til å bruke `KeyValueVisning`. `key` er jo en default prop på komponenter, så det ble ikke vist 😞
> IS-1764: Show sykmelder and arbeidsgiver keyword

- mock/isaktivitetskrav/aktivitetskravHistorikkMock.ts
- mock/isaktivitetskrav/mockIsaktivitetskrav.ts
- src/components/historikk/HistorikkEventItem.tsx
- src/components/historikk/container/HistorikkContainer.tsx
- src/data/aktivitetskrav/aktivitetskravQueryHooks.ts
- src/data/aktivitetskrav/aktivitetskravTypes.ts
- src/data/historikk/historikk_hooks.ts
- src/data/historikk/types/historikkTypes.ts
Henter inn historikk for aktivitetskravet til å bruke på Logg-siden
> IS-1878: Fetch aktivitetskravhistorikk

- src/components/huskelapp/HuskelappModal.tsx
- src/utils/amplitude.ts
- Legger til event som logger hvilken oppfolgingsgrunn bruker velger når hen sender inn "trenger oppfolging".
- Vi får oppfolgingsgrunn som er sendt inn og vi får url'en brukeren var på når den ble sendt inn.
> IS-1886: Add sending of event when user sends in trenger oppfolging note

- src/components/aktivitetskrav/AktivitetskravContainer.tsx
- Gjør at tredje kolonne i tredelingen blir sticky til toppen når bruker scroller slik at bruker alltid har informasjon i tredje kolonne tilgjengelig.
https://github.com/navikt/syfomodiaperson/assets/11747383/3bc36423-d707-4953-ab79-0d8318cde405
> IS-1882: Add sticky styling to third column

- src/components/huskelapp/HuskelappModal.tsx
- src/components/huskelapp/OpenHuskelappModalButton.tsx
- test/huskelapp/HuskelappModalTest.tsx
- Påpekt av Stine at det ikke er bra at knappenavn og overskrift fortsatt heter "Huskelapp".
- Endrer midlertidig til "trenger oppfølging" før vi lander endelig konseptnavn
> IS-1893: Rename from huskelapp to trenger oppfolging

- src/components/personkort/PersonkortHeader/Varighet.tsx
- src/data/oppfolgingstilfelle/person/oppfolgingstilfellePersonQueryHooks.ts
- src/data/oppfolgingstilfelle/person/types/OppfolgingstilfellePersonDTO.ts
- test/dialogmote/DialogmoteInnkallingContainerTest.tsx
- test/testDataUtils.ts
- test/utils/oppfolgingstilfelleUtilsTest.ts
- test/utils/sykmeldingUtilsTest.ts
Bruker varighet for oppfølgingstilfelle utregnet i backend
> Oppfolgingstilfelle varighet

- src/components/dialogmote/DeltakereSvarInfo.tsx
- test/dialogmote/DeltakereSvarInfo/DeltakereSvarInfoBehandlerTest.tsx
Bruker Aksel DS og tailwind i dialogmøte-deltaker-svar-komponent
> Use Aksel DS in dialogmotesvar-expandables

- src/components/aktivitetskrav/vurdering/IkkeAktuellAktivitetskravSkjema.tsx
- src/utils/amplitude.ts
- Legger til logging av ikke aktuell vurderingsårsak
> IS-1845: Add logging of arsak to ikke aktuell vurdering 

- src/components/huskelapp/Huskelapp.tsx
- src/components/huskelapp/HuskelappModal.tsx
- src/components/huskelapp/OpenHuskelappModalButton.tsx
- test/huskelapp/HuskelappModalTest.tsx
Endrer navn fra huskelapp/trenger oppfølfing til Oppfølgingsoppgave i tekster.
Fortsatt mye huskelapp i koden, men tenker vi evt kan ta det i en senere PR (og kanskje vente til navnet har satt seg litt :sweat_smile: )
> IS-1733: Rename to oppfølgingsoppgave

- src/components/aktivitetskrav/vurdering/UnntakAktivitetskravSkjema.tsx
- src/data/aktivitetskrav/aktivitetskravTypes.ts
- src/hooks/aktivitetskrav/useAktivitetskravVarselDocument.ts
- test/aktivitetskrav/VurderAktivitetskravTest.tsx
- test/aktivitetskrav/varselDocuments.ts
Sender med document-tekster til journalføring ved aktivitetskrav-vurdering unntak.
Merge etter https://github.com/navikt/isaktivitetskrav/pull/187
> IS-1904: Add document texts to unntak vurdering

- src/components/aktivitetskrav/vurdering/IkkeAktuellAktivitetskravSkjema.tsx
- src/components/aktivitetskrav/vurdering/OppfyltAktivitetskravSkjema.tsx
- src/data/aktivitetskrav/aktivitetskravTypes.ts
- src/hooks/aktivitetskrav/useAktivitetskravVarselDocument.ts
- test/aktivitetskrav/VurderAktivitetskravTest.tsx
- test/aktivitetskrav/varselDocuments.ts
Lagt til document for vurderinger IKKE_AKTUELL og OPPFYLT.
> IS-1904: Add document texts to oppfylt and ikke aktuelt vurdering

- src/data/huskelapp/huskelappTypes.ts
- test/huskelapp/HuskelappModalTest.tsx
- Endret navn på avhukingsboks i oppfølgingsoppgave modal
> IS-1924: Rename avhukingsvalg need for dialogmøte

- src/data/huskelapp/huskelappTypes.ts
> Fjernet pilotgruppa-tekst fra Annet-avhukingsvalg i oppfølgingsoppgave

- src/components/aktivitetskrav/AktivitetskravContainer.tsx
- src/components/dialogmote/innkalling/DialogmoteInnkallingContainer.tsx
- src/components/mote/components/Motelandingsside.tsx
- src/sider/Side.tsx
- src/sider/TredeltSide.tsx
- tailwind.config.js
- test/setup.js
- Legger til [standard brekkpunkter fra Aksel](https://aksel.nav.no/grunnleggende/styling/brekkpunkter) i `tailwind.config.js`
- Legger til ny komponent for å bruke for tredeling. Gjerne kom med forslag for hvordan denne kunne blitt strukturert bedre😊
> IS-1933: Replace old Tredelt component with new

- server/unleash.ts
- src/data/unleash/unleash_types.ts
- src/sider/Side.tsx
> IS-1965: Remove huskelapp toggle

- src/components/personkort/ledere/PersonKortVirksomhetLedere.tsx
Reverterer endring i nærmeste-leder-fanen gjort i https://github.com/navikt/syfomodiaperson/pull/1151
Ref: https://jira.adeo.no/browse/FAGSYSTEM-313914
> Reverter noe gammelt DS-migrering for å se om det hjelper på visning av nærmeste leder-fanen

- src/components/oppfolgingsoppgave/OppfolgingsoppgaveModal.tsx
- test/oppfolgingsoppgave/OppfolgingsoppgaveModalTest.tsx
- Endret fra `RadioGroup` til `Select` element. Står utfyllende om hvorfor i [trello oppg](https://trello.com/c/Da6XbLv1/1976-endre-fra-radio-group-til-select-p%C3%A5-oppf%C3%B8lgingsgrunn).
https://github.com/navikt/syfomodiaperson/assets/11747383/b87a8bcc-76c7-4216-abfb-05a09d351213
> IS-1976: Change from radio group to select element

- src/sider/aktivitetskrav/historikk/AktivitetskravHistorikk.tsx
- test/aktivitetskrav/AktivitetskravHistorikkTest.tsx
Viser også avventer-"vurderinger" (med beskrivelse og årsak(er)) i historikken slik at veileder får innsikt i hva som er gjort i saken tidligere.
> IS-1968: Show avventer in historikk

- src/components/flexjar/Flexjar.tsx
- src/hooks/useLocalStorageState.ts
- src/sider/Side.tsx
- test/flexjar/FlexjarTest.tsx
- test/setup.js
Lagrer info om når det ble gjort en vurdering i localstorage. Bruker denne til å bestemme om flexjar skal vises eller ikke.
Bilde som viser localstorage
> IS-1995: Don't show flexjar if user has answered last day

- server/config.ts
Vi har kommet gjennom Azure-muren til flexjar, men har feil path til endepunktet. Dette burde fikse det 👍🏼
> Fix flexjar api-path

- src/components/flexjar/Flexjar.tsx
I stedet for å bruke "knapp trykket" så er det bedre med "alternatitv valgt" for å gruppere dette på en penere måte i amplitude.
> Change how to track flexjar-score in amplitude

- src/components/dialogmote/innkalling/DialogmoteInnkallingContainer.tsx
- src/context/malform/MalformContext.tsx
- src/hooks/useLocalStorageState.ts
We want to use useMalform-hook to switch between nynorsk and bokmal in brevmaler, eg. for dialogmoteinnkalling
> IS-1189: Save malform in global state and localstorage

- src/sider/mote/components/endre/EndreDialogmoteContainer.tsx
> Use ø instead of o in dialogmøte

- mock/isdialogmote/dialogmoterMock.ts
- src/components/dialogmote/referat/DialogmoteEndreReferatContainer.tsx
- src/components/dialogmote/referat/DialogmoteReferatContainer.tsx
- src/components/dialogmote/referat/Referat.tsx
- src/components/dialogmote/referat/StandardTekster.tsx
- src/data/dialogmote/dialogmoteTexts.ts
- src/hooks/dialogmote/document/useInnkallingDocument.ts
- src/hooks/dialogmote/document/useReferatDocument.ts
- src/hooks/dialogmote/useInitialValuesReferat.ts
- src/utils/behandlerUtils.ts
- test/dialogmote/DialogmoteInnkallingSkjema/DialogmoteInnkallingSkjemaTest.tsx
- test/dialogmote/ReferatEndreTest.tsx
- test/dialogmote/ReferatMellomlagreTest.tsx
- test/dialogmote/ReferatTest.tsx
- test/dialogmote/dialogmoteTextsTest.ts
- test/dialogmote/testData.ts
- test/dialogmote/testDataDocuments.ts
Nynorsk i dialogmøtereferatet. Mangler noen tekster på nynorsk, vet ikke hvor lang tid det tar å skaffe, eller om vi bare skal oversette selv :ivaraasen:
La den inn her, trenger nok litt innspill på den fra Peter!
> IS-2068: Add nynorsk texts to referat

- src/data/arbeidsuforhet/forhandsvarsel84Texts.ts
- src/hooks/arbeidsuforhet/useArbeidsuforhetVarselDocument.ts
Med en del tekst i begrunnelsen:
Uten begrunnelse (som er påkrevd):
> IS-2103: Use correct texts for arbeidsuforhet

- src/sider/arbeidsuforhet/SendForhandsvarselSkjema.tsx
> Add helptexts for 8-4 forhåndsvarsel

- src/components/oppfolgingsoppgave/OppfolgingsoppgaveModal.tsx
- Setter ny grense for antall tegn i tekstfelt for oppfølgingsoppgave
> IS-2127: Increase number of chars in oppfolgingsoppgave

- server/config.ts
> Fix typo in env variable in config

- server/unleash.ts
- src/components/globalnavigasjon/GlobalNavigasjon.tsx
- src/data/unleash/unleash_types.ts
- src/sider/arbeidsuforhet/ArbeidsuforhetSide.tsx
- src/utils/globalNavigasjonUtils.ts
Lagt inn toggle og menypunkt for 8-4, toggle er også aktiv i dev.
> IS-2137: Add toggle for arbeidsuforhet-side

- src/sider/arbeidsuforhet/ArbeidsuforhetSide.tsx
- src/sider/arbeidsuforhet/SendForhandsvarselSkjema.tsx
- test/arbeidsuforhet/ArbeidsuforhetForhandsvarselTest.tsx
- test/arbeidsuforhet/documents.ts
- test/stubs/stubIsarbeidsuforhet.ts
Ta i bruk react query for sending/mutate i forhandsvarselSkjema.
> IS-2134: Send 8-4 forhandsvarsel to backend

- src/sider/behandlerdialog/paminnelse/PaminnelseMelding.tsx
Oppdaget noe som så litt rart ut, mulig dette kom etter migrering til ny Modal-versjon i Aksel.
Før:
Etter:
> Change width for påminnelse-modal

- mock/isarbeidsuforhet/arbeidsuforhetMock.ts
- mock/isarbeidsuforhet/mockIsarbeidsuforhet.ts
- src/data/arbeidsuforhet/arbeidsuforhetQueryHooks.ts
- src/data/arbeidsuforhet/arbeidsuforhetTypes.ts
- src/sider/arbeidsuforhet/ArbeidsuforhetSide.tsx
Bruk riktig type på responsen.
Legg til mock ev get-endepunktet.
> IS-2151: Fetch vurderinger in ArbeidsuforhetSide

- src/data/arbeidsuforhet/arbeidsuforhetTypes.ts
Basert på endringene her: https://github.com/navikt/isarbeidsuforhet/pull/40/files#diff-0afbcfc5aa8ddbbe09d991d48a0507aea5d279b2ea721de49b6f204b4c7fc9aa
> IS-2167: Update DTO after backend refactoring

- .nais/naiserator-dev.yaml
- .nais/naiserator-prod.yaml
- server/config.ts
- server/proxy.ts
- src/apiConstants.ts
- src/components/utdragFraSykefravaeret/UtdragOppfolgingsplaner.tsx
- src/data/oppfolgingsplan/oppfolgingsplanQueryHooks.ts
- src/sider/oppfolgingsplan/lps/OppfolgingsplanerOversiktLPS.tsx
- test/stubs/stubSyfooppfolgingsplan.ts
eSyfo har flyttet API for LPS-planer til ny app. DTO/alt er det samme, men hentes da altså fra ny ingress/app.
> Use new endpoint for fetching LPS follow-up plans

- src/components/globalnavigasjon/GlobalNavigasjon.tsx
- src/sider/arbeidsuforhet/ArbeidsuforhetSide.tsx
> Change title arbeidsuforhet -> forhandsvarsel §8-4

- mock/isarbeidsuforhet/arbeidsuforhetMock.ts
- mock/isarbeidsuforhet/mockIsarbeidsuforhet.ts
- src/data/arbeidsuforhet/arbeidsuforhetQueryHooks.ts
- src/data/arbeidsuforhet/arbeidsuforhetTypes.ts
- src/data/arbeidsuforhet/useSendVurderingArbeidsuforhet.ts
- src/sider/arbeidsuforhet/SendForhandsvarselSkjema.tsx
- test/arbeidsuforhet/ArbeidsuforhetForhandsvarselTest.tsx
Bytter til å bruke `/vurderinger`-endpoint. Gi gjerne innspill på navngivning.
Venter på https://github.com/navikt/isarbeidsuforhet/pull/54
> IS-2184: Use vurderinger-endpoint for 8-4

- src/components/oppfolgingsoppgave/OppfolgingsoppgaveModal.tsx
- Fikser at tekst ikke ble sendt med når oppfølgingsgrunn var `ANNET`
> IS-2187: Fix sending of tekst for annet oppfolgingsgrunn

- src/components/Paragraph.tsx
- src/sider/aktivitetskrav/historikk/AktivitetskravHistorikk.tsx
- src/sider/arbeidsuforhet/ArbeidsuforhetSide.tsx
- src/sider/arbeidsuforhet/historikk/VurderingHistorikk.tsx
- test/arbeidsuforhet/ForhandsvarselSendtTest.tsx
- test/arbeidsuforhet/VurderingHistorikkTest.tsx
- test/arbeidsuforhet/arbeidsuforhetTestData.ts
Lagt til visning av tidligere vurderinger av arbeidsuførhet i Historikk
> IS-2185: Historikk vurderinger

- src/sider/aktivitetskrav/vurdering/IkkeAktuellAktivitetskravSkjema.tsx
- src/sider/aktivitetskrav/vurdering/OppfyltAktivitetskravSkjema.tsx
- src/sider/aktivitetskrav/vurdering/SendForhandsvarselSkjema.tsx
- src/sider/aktivitetskrav/vurdering/UnntakAktivitetskravSkjema.tsx
- src/sider/aktivitetskrav/vurdering/VurderAktivitetskrav.tsx
Hjelpetekster for å informere veileder om hva som journalføres på aktivitetskravet.
> IS-1922: Add texts about journalføring for inputfields aktivitetskrav

- src/sider/arbeidsuforhet/ForhandsvarseAfterDeadline.tsx
- test/arbeidsuforhet/ForhandsvarselSendtTest.tsx
> Use new design for frist ugatt in arbeidsuforhet

- mock/common/mockConstants.ts
- mock/isaktivitetskrav/aktivitetskravMock.ts
- mock/isarbeidsuforhet/arbeidsuforhetMock.ts
- mock/isbehandlerdialog/behandlerdialogMock.ts
- mock/syfoveileder/mockSyfoveileder.ts
- mock/syfoveileder/veilederMock.ts
- src/apiConstants.ts
- src/components/dialogmote/motehistorikk/MoteHistorikkUnntak.tsx
- src/components/dialogmote/referat/Deltakere.tsx
- src/components/oppfolgingsoppgave/Oppfolgingsoppgave.tsx
- src/components/personoppgave/BehandlePersonOppgaveKnapp.tsx
- src/data/veilederinfo/types/Veileder.ts
- src/data/veilederinfo/types/VeilederinfoDTO.ts
- src/data/veilederinfo/veilederinfoQueryHooks.ts
- src/hooks/dialogmote/document/useAvlysningDocument.ts
- src/hooks/dialogmote/document/useInnkallingDocument.ts
- src/hooks/dialogmote/document/useReferatDocument.ts
- src/hooks/dialogmote/document/useTidStedDocument.ts
- src/hooks/useDocumentComponents.ts
- src/sider/aktivitetskrav/historikk/AktivitetskravHistorikk.tsx
- src/sider/behandlerdialog/meldinger/MeldingInnholdPanel.tsx
- test/aktivitetskrav/AktivitetskravHistorikkTest.tsx
- test/aktivitetskrav/varselDocuments.ts
- test/arbeidsuforhet/documents.ts
- test/behandlerdialog/MeldingerTest.tsx
- test/behandlerdialog/testDataDocuments.ts
- test/dialogmote/ReferatTest.tsx
- test/dialogmote/testDataDocuments.ts
- test/oppfolgingsoppgave/OppfolgingsoppgaveModalTest.tsx
- test/stubs/stubSyfoveileder.ts
- Tar i bruk nye V3 endepunkter fra `syfoveileder` som ble lagt til i [denne PR'en](https://github.com/navikt/syfoveileder/pull/84).
> IS-2061: Use syfoveileder v3 endpoints

- mock/oppfolgingsoppgave/mockOppfolgingsoppgave.tsx
- src/components/oppfolgingsoppgave/OpenOppfolgingsoppgaveModalButton.tsx
- src/components/oppfolgingsoppgave/Oppfolgingsoppgave.tsx
- src/components/oppfolgingsoppgave/OppfolgingsoppgaveModal.tsx
- src/data/oppfolgingsoppgave/types.ts
- src/data/oppfolgingsoppgave/useCreateOppfolgingsoppgave.tsx
- src/data/oppfolgingsoppgave/useEditOppfolgingsoppgave.tsx
- src/utils/amplitude.ts
- src/utils/datoUtils.ts
- test/oppfolgingsoppgave/OppfolgingsoppgaveModalTest.tsx
- Legger til mulighet for å endre dato på en eksisterende oppfølgingsoppgave.
- Har tatt meg noen friheter med designet, men har prøvd å gjør det så enkelt som mulig i første omgang.
Se [tilhørende PR](https://github.com/navikt/ishuskelapp/pull/38) i `ishuskelapp`
https://github.com/navikt/syfomodiaperson/assets/11747383/706adc14-5869-46db-8475-d4f246c8fc8a
> IS-2043: Add ability to edit frist on existing oppfolgingsoppgave

- src/sider/arbeidsuforhet/ForhandsvarselBeforeDeadline.tsx
> IS: Disable oppfylt untit it works

- src/sider/arbeidsuforhet/ArbeidsuforhetOppfylt.tsx
- src/sider/arbeidsuforhet/ForhandsvarseAfterDeadline.tsx
- src/sider/arbeidsuforhet/ForhandsvarselBeforeDeadline.tsx
- src/sider/arbeidsuforhet/OppfyltForm.tsx
- test/arbeidsuforhet/ArbeidsuforhetOppfyltTest.tsx
- test/arbeidsuforhet/ForhandsvarselSendtTest.tsx
- test/arbeidsuforhet/OppfyltFormTest.tsx
- test/arbeidsuforhet/documents.ts
Oppfylt-knapper sender bruker til "oppfylt" route.
Vis skjema når siste status i 8-4 er forhåndsvarsel.
> IS-2200: Add form for oppfylt arbeidsuforhet

- src/components/oppfolgingsoppgave/Oppfolgingsoppgave.tsx
- src/sider/Side.tsx
> Move easteregg below oppfolgingsoppgave

- mock/oppfolgingsoppgave/mockOppfolgingsoppgave.tsx
- src/components/oppfolgingsoppgave/OppfolgingsoppgaveModal.tsx
- Legger til mulighet for å endre tekst på en eksisterende oppfølgingsoppgave.
- Se [tilhørende PR i backend](https://github.com/navikt/ishuskelapp/pull/44)
https://github.com/navikt/syfomodiaperson/assets/11747383/918b0bd4-540b-4be8-b951-a4251735292d
> IS-2110: Change text on existing oppfolgingsoppgave

- src/sider/arbeidsuforhet/SendForhandsvarselSkjema.tsx
Øker antall tegn for beskrivelsen basert på tilbakemelding fra pilot-veileder.
> IS-2243: Increase number of allowed symbols in forhåndsvarsel arbeidsuførhet

- src/sider/arbeidsuforhet/SendForhandsvarselSkjema.tsx
Øker antall tegn igjen basert på tilbakemeldinger
> IS-2249: Increase forhandsvarsel max char length to 5000

- src/components/flexjar/Flexjar.tsx
Vi ønsket å gjøre knappen mer synlig, og bytter fra grå til blå i første omgang for å se om det øker konverteringen.
> IS-2265: Make flexjar-button more visible

- src/data/arbeidsuforhet/arbeidsuforhetDocumentTexts.ts
- src/hooks/arbeidsuforhet/useArbeidsuforhetVurderingDocument.ts
- src/hooks/useDocumentComponents.ts
Legger inn tekster til dokumentet for innstilling om avslag. Skal tas i bruk i skjema for å skrive innstilling om avslag senere. Der vil innstillingen lagres og journalføres automatisk (uten innsyn til bruker) slik at NAY kan gjøre selve avslaget i Gosys.
> IS-2285: Avslag document texts

- mock/isarbeidsuforhet/arbeidsuforhetMock.ts
- src/components/VisBrev.tsx
- src/data/arbeidsuforhet/arbeidsuforhetDocumentTexts.ts
- src/data/arbeidsuforhet/arbeidsuforhetTypes.ts
- src/hooks/arbeidsuforhet/useArbeidsuforhetVurderingDocument.ts
- src/sider/arbeidsuforhet/Arbeidsuforhet.tsx
- src/sider/arbeidsuforhet/ForhandsvarseAfterDeadline.tsx
- src/sider/arbeidsuforhet/ForhandsvarselBeforeDeadline.tsx
- src/sider/arbeidsuforhet/NyVurdering.tsx
- src/sider/arbeidsuforhet/historikk/VurderingHistorikk.tsx
- test/arbeidsuforhet/ForhandsvarselSendtTest.tsx
- test/arbeidsuforhet/VurderingHistorikkTest.tsx
Legger til knapp for å forhåndsvise `document` på de ulike vurderingene. Foreløpig er da `AVSLAG` en tom modal.
Jeg har sendt melding til Peter om navn på knappene, men kom gjerne med innspill her ettersom jeg måtte freestyle litt 👍🏼
EDIT: Peter var happy med tekstene ✅
<details>
<summary>Screenshots 📸✨</summary>
</details>
> IS-2266: Add button for showing sent document in historikk

- server/unleash.ts
- src/components/globalnavigasjon/GlobalNavigasjon.tsx
- src/data/unleash/unleash_types.ts
- src/routers/AppRouter.tsx
- src/sider/frisktilarbeid/FriskmeldingTilArbeidsformidlingSide.tsx
- src/utils/globalNavigasjonUtils.ts
> IS-2160: Add toggle and menypunkt frisktilarbeid with route and side

- mock/isfrisktilarbeid/mockIsfrisktilarbeid.ts
- src/data/frisktilarbeid/frisktilarbeidTypes.ts
- src/data/frisktilarbeid/useFattVedtak.ts
- src/data/frisktilarbeid/vedtakQuery.ts
- src/sider/frisktilarbeid/FriskmeldingTilArbeidsformidlingSide.tsx
Lagt til kode for å hente vedtak fra api på frisktilarbeid-siden
> IS-2314: Add vedtak query

- src/routers/AppRouter.tsx
- src/sider/arbeidsuforhet/ArbeidsuforhetOppfylt.tsx
- src/sider/arbeidsuforhet/NyVurdering.tsx
- src/sider/arbeidsuforhet/OppfyltForm.tsx
- src/sider/arbeidsuforhet/avslag/AvslagForm.tsx
- test/arbeidsuforhet/ArbeidsuforhetOppfyltTest.tsx
- test/arbeidsuforhet/ArbeidsuforhetTest.tsx
- test/arbeidsuforhet/ForhandsvarselSendtTest.tsx
- test/arbeidsuforhet/OppfyltFormTest.tsx
- test/arbeidsuforhet/arbeidsuforhetTestUtils.tsx
- test/arbeidsuforhet/avslag/ArbeidsuforhetAvslagTest.tsx
- test/arbeidsuforhet/avslag/AvslagFormTest.tsx
Viser notification alert etter sendt innstilling om avslag og oppfylt
> IS-2320: Notification on oppfylt and avslag

- src/components/motebehov/BehandleMotebehovKnapp.tsx
- src/components/pengestopp/PengestoppModal.tsx
- src/components/personoppgave/BehandlePersonOppgaveKnapp.tsx
- src/sider/sykmeldinger/sykmeldinger/VelgSykmeldingSorteringDropdown.tsx
Litt lavthengende Aksel-migrering
> Migrate from nav-frontend-skjema to Aksel

- src/components/pengestopp/Pengestopp.tsx
- src/components/pengestopp/PengestoppModal.tsx
- test/pengestopp/PengestoppTest.tsx
Fjerner mulighet for å velge tilbakedatering og bestridelse som årsaker i stoppknappen
> IS-2302: Hide arsaker and some Aksel migration

- src/sider/frisktilarbeid/AvsluttOppgave.tsx
- src/sider/frisktilarbeid/FattVedtak.tsx
- src/sider/frisktilarbeid/FattVedtakSkjema.tsx
- src/sider/frisktilarbeid/FriskmeldingTilArbeidsformidling.tsx
- src/sider/frisktilarbeid/FriskmeldingTilArbeidsformidlingSide.tsx
- src/sider/frisktilarbeid/VedtakForberedelser.tsx
- src/sider/frisktilarbeid/VedtakVenter.tsx
- src/sider/frisktilarbeid/VurderVedtak.tsx
- test/frisktilarbeid/FattVedtakTest.tsx
- test/frisktilarbeid/FriskmeldingTilArbeidsformidlingTest.tsx
- test/frisktilarbeid/frisktilarbeidTestData.ts
Lagt til steg i 8-5 som i [prototypen](https://www.figma.com/proto/sPmsOTiLhgACeNt4TElE4P/iSYFO-Modia?page-id=6117%3A35985&type=design&node-id=7250-14625&viewport=-21522%2C-1507%2C0.32&t=QITr96OVS8Gs12EU-1&scaling=min-zoom&starting-point-node-id=7250%3A14625&mode=design).
Lager nye lapp(er) på å implementere det som skal skje i Avslutt oppgave-steget når man trykker på knappen og videre derfra (Nytt vedtak osv).
> IS-2314: Stepper and pages

- src/data/frisktilarbeid/frisktilarbeidDocumentTexts.ts
- src/hooks/frisktilarbeid/useFriskmeldingTilArbeidsformidlingDocument.ts
- src/sider/frisktilarbeid/FattVedtakSkjema.tsx
- test/frisktilarbeid/FattVedtakTest.tsx
- test/frisktilarbeid/frisktilarbeidTestData.ts
Lagt til document for behandlermelding og sender dette til api.
> IS-2317: Add behandler document

- mock/isarbeidsuforhet/arbeidsuforhetMock.ts
- src/data/arbeidsuforhet/arbeidsuforhetDocumentTexts.ts
- src/hooks/arbeidsuforhet/useArbeidsuforhetVurderingDocument.ts
- src/sider/arbeidsuforhet/ArbeidsuforhetOppfylt.tsx
- src/sider/arbeidsuforhet/OppfyltForm.tsx
- test/arbeidsuforhet/OppfyltFormTest.tsx
- test/arbeidsuforhet/documents.ts
- Legger til maltekst for oppylt vurdering av §8-4.
<details>
<summary>Screenshots 📸✨</summary>
Før
Etter
</details>
> IS-2253: Add oppfylt vurdering template text

- src/sider/arbeidsuforhet/OppfyltForm.tsx
- test/arbeidsuforhet/ArbeidsuforhetOppfyltTest.tsx
- Legger til støttetekst for oppfylt vurdering og endrer tittel
Før
Etter
> IS-2327: Add guidance text for 8-4 oppfylt vurdering

- src/data/frisktilarbeid/frisktilarbeidDocumentTexts.ts
- src/hooks/frisktilarbeid/useFriskmeldingTilArbeidsformidlingDocument.ts
- src/hooks/useDocumentComponents.ts
- src/sider/frisktilarbeid/FattVedtakSkjema.tsx
- test/frisktilarbeid/FattVedtakTest.tsx
- test/frisktilarbeid/frisktilarbeidTestData.ts
Lagt inn tekster for vedtak-document. Gjenstår å avklare endelig hvordan linkene skal vises.
> IS-2211: Vedtak document

- src/data/frisktilarbeid/frisktilarbeidDocumentTexts.ts
- src/hooks/frisktilarbeid/useFriskmeldingTilArbeidsformidlingDocument.ts
- test/frisktilarbeid/frisktilarbeidTestData.ts
Tilbakemelding fra Stine: Lagt til en ekstra setning i et avsnitt og fjernet noen bindestreker.
> IS-2211: Adjust vedtak document

- src/data/frisktilarbeid/frisktilarbeidDocumentTexts.ts
- src/hooks/frisktilarbeid/useFriskmeldingTilArbeidsformidlingDocument.ts
- test/frisktilarbeid/frisktilarbeidTestData.ts
La på en setning i tekstmalen for meldingen som går til behandler. Skal få verifisert i dev-db, men så riktig ut i network-tabben i devtools hvertfall 👍🏼
> IS-2317: Add sentence about no new sykmelding in behandlermelding

- src/sider/frisktilarbeid/FattVedtakSkjema.tsx
- src/utils/datoUtils.ts
- test/frisktilarbeid/FattVedtakTest.tsx
Ettersom datoene er til-og-med, så må vi trekke fra en dag i dato-utregningen.
Da blir dette riktig?
> IS-2348: Fix tom-date

- src/data/frisktilarbeid/frisktilarbeidDocumentTexts.ts
- src/hooks/frisktilarbeid/useFriskmeldingTilArbeidsformidlingDocument.ts
- src/sider/frisktilarbeid/FattVedtakSkjema.tsx
- test/frisktilarbeid/FattVedtakTest.tsx
- test/frisktilarbeid/frisktilarbeidTestData.ts
Legger til ekstra setning i vedtaksbrevet dersom tildato på vedaket er samme som maks-dato.
> IS-2349: Add sentence if tom-dato is maks-dato

- src/data/oppfolgingsoppgave/types.ts
Legger til nye oppfolgingsgrunner, fikset backend i https://github.com/navikt/ishuskelapp/pull/51
> IS-2383: Add new oppfolgingsgrunner

- test/nokkelinformasjon/SykmeldingsgradTest.tsx
Manglet tester på denne, men vanskelig å teste selve plottet fordi det krever mocking av ResponsiveContainer via Rechart-biblioteket
> Add tests for sykmeldingsgrad in nokkelinformasjon

- src/components/oppfolgingsoppgave/Oppfolgingsoppgave.tsx
- test/oppfolgingsoppgave/OppfolgingsoppgaveModalTest.tsx
> IS-2389: Viser dato for sist oppdatert på oppfølgingsoppgave

- mock/isaktivitetskrav/aktivitetskravMock.ts
- src/data/aktivitetskrav/forhandsvarselTexts.ts
- src/hooks/aktivitetskrav/useAktivitetskravVarselDocument.ts
- test/aktivitetskrav/varselDocuments.ts
Tekster i forhåndsvarsel relatert til aktivitetskrav.
> IS-2396: Update aktivitetskrav tekst

- src/data/aktivitetskrav/forhandsvarselTexts.ts
> IS: Corrected typo in aktivitetskrav forhandsvarsel

- package-lock.json
- package.json
- Oppdaterer webpack-cli og unleash-client
> IS: Update dependencies

- .nais/naiserator-dev.yaml
- .nais/naiserator-prod.yaml
- Fikk feil i nais console siden vi tillot trafikk fra `syfomodiaperson`, men ikke tillot utgående trafikk til `ismeroppfolging`
> IS: Add outbound rule to syfomodiaperson

- src/sider/frisktilarbeid/FattNyttVedtak.tsx
- src/sider/frisktilarbeid/VedtakFraDato.tsx
Fjernet også setning om at det ikke kan fattes tilbakevirkende øverst.
> IS-2450: Fjern fra-dato-begrensning

- mock/isarbeidsuforhet/arbeidsuforhetMock.ts
- mock/isarbeidsuforhet/mockIsarbeidsuforhet.ts
- src/data/arbeidsuforhet/arbeidsuforhetTypes.ts
- src/hooks/arbeidsuforhet/useArbeidsuforhetVurderingDocument.ts
- src/routers/AppRouter.tsx
- src/sider/arbeidsuforhet/ArbeidsuforhetButtons.tsx
- src/sider/arbeidsuforhet/NyVurdering.tsx
- src/sider/arbeidsuforhet/historikk/VurderingHistorikk.tsx
- src/sider/arbeidsuforhet/ikkeaktuell/ArbeidsuforhetIkkeAktuell.tsx
- src/sider/arbeidsuforhet/ikkeaktuell/ArbeidsuforhetIkkeAktuellSide.tsx
- src/sider/arbeidsuforhet/ikkeaktuell/ArbeidsuforhetIkkeAktuellSkjema.tsx
- test/arbeidsuforhet/ArbeidsuforhetIkkeAktuellTest.tsx
- test/arbeidsuforhet/ArbeidsuforhetTest.tsx
- test/arbeidsuforhet/ForhandsvarselSendtTest.tsx
- test/arbeidsuforhet/VurderingHistorikkTest.tsx
- test/arbeidsuforhet/arbeidsuforhetTestData.ts
- test/arbeidsuforhet/documents.ts
Ny knapp og side for ikke aktuell når det er sendt et forhåndsvarsel
> IS-2454: Arbeidsuforhet ikke aktuell

- server/unleash.ts
- src/components/globalnavigasjon/GlobalNavigasjon.tsx
- src/data/unleash/unleash_types.ts
- src/routers/AppRouter.tsx
- src/sider/senoppfolging/SenOppfolgingSide.tsx
- src/utils/globalNavigasjonUtils.ts
Legger til ny tom side som bruker toggle. Heter foreløpig `Oppfølging i sen fase`.
Begynner å gå inflasjon i antall sider snart 😢 Oppfølgingsoppgaven flyttes lenger og lenger ned.
> IS-2364: Add new sen oppfolging side

- mock/meroppfolging-backend/SenOppfolgingMock.ts
- mock/mockEndepunkter.ts
- src/components/globalnavigasjon/GlobalNavigasjon.tsx
- src/data/senoppfolging/SenOppfolgingTypes.ts
- src/data/senoppfolging/useSenoppfolgingSvarQuery.ts
- src/routers/AppRouter.tsx
- src/sider/senoppfolging/SenOppfolging.tsx
- src/sider/senoppfolging/SenOppfolgingSide.tsx
- test/senoppfolging/SenOppfolgingTest.tsx
Henter inn spørsmål og svar fra `meroppfolging-backend`. Side med svarene og noen guidelines dersom man har fått svar, og egen side med info dersom bruker ikke har svart.
Med svar
Uten svar
> IS-2364: Get sen oppfolging spørsmål and svar

- .env.template
- .nais/naiserator-dev.yaml
- .nais/naiserator-prod.yaml
- mock/mockEndepunkter.ts
- mock/veilarboppfolging/mockVeilarboppfolging.ts
- server/config.ts
- server/proxy.ts
- src/apiConstants.ts
- src/components/personkort/PersonkortHeader/PersonkortHeaderTags.tsx
- src/data/veilarboppfolging/useUnderArbeidsrettetOppfolgingQuery.ts
- src/data/veilarboppfolging/veilarboppfolgingTypes.ts
- test/components/personkort/PersonkortHeaderTest.tsx
Henter info fra `veilarboppfolging` og viser i personkortet dersom personen er under arbeidsrettet oppfølging. Viser ingenting dersom de ikke er det, eller om vi får feil fra APIet.
> IS-2387: Show tag if person under arbeidsrettet oppfølging

- mock/sykepengesoknad/mockSykepengesoknadBackend.ts
- src/data/sykepengesoknad/hentVeilederSoknaderRequest.ts
- src/data/sykepengesoknad/sykepengesoknadQueryHooks.ts
- test/data/sykepengesoknadQueryHooksTest.tsx
- test/stubs/stubSykepengesoknadBackend.ts
- Updates deprecated request for getting søknader
> IS-2535: Update request for getting soknader

- .nais/naiserator-dev.yaml
- .nais/naiserator-prod.yaml
- Legger til auto-instrumentering
> IS-2546: Add auto instrumentation

- .nais/naiserator-dev.yaml
- Legger til ingress for å eksponere app for interne brukere uten naisdevice
> IS-2505: Add ingress to expose app to internal users without naisdevice

- src/sider/behandlerdialog/meldingtilbehandler/MeldingTilBehandlerSkjema.tsx
- src/sider/behandlerdialog/meldingtilbehandler/PreviewButton.tsx
- Legger på indikator for hvor mange tegn som er igjen.
> IS-2566: Add error message when too long text in input

- mock/unleashMocks.ts
- src/components/globalnavigasjon/GlobalNavigasjon.tsx
- src/utils/globalNavigasjonUtils.ts
- test/components/GlobalNavigasjonTest.tsx
- test/testQueryClient.ts
- Legger til rød prikk når en person er en aktiv oppfølging i sen fase kandidat.
> IS-2526: Red dot indication when active sen fase kandidat

- mock/unleashMocks.ts
`npm start` fungerer ikke med importen som var
> IS: Fix running npm start

- src/sider/senoppfolging/SenOppfolging.tsx
Justert punkter og lagt til nytt punkt i vurder sen oppfølging.
> IS-2616: Tekstendringer vurder sen oppfolging

- mock/isfrisktilarbeid/mockIsfrisktilarbeid.ts
- server/unleash.ts
- src/components/globalnavigasjon/GlobalNavigasjon.tsx
- src/data/unleash/unleash_types.ts
- src/routers/AppRouter.tsx
- src/sider/manglendemedvirkning/ManglendeMedvirkningSide.tsx
- src/utils/globalNavigasjonUtils.ts
Første del, setter bare opp en dummy side med ny path, bak en toggle 👍🏼
> IS-2620: Add manglende medvirkning page and hide behind toggle

- server/unleash.ts
Førte til at manglende medvirkning-siden ikke ble vist i dev
> Fix typo in toggle

- mock/ismanglendemedvirkning/mockIsmanglendemedvirkning.ts
- mock/mockEndepunkter.ts
- server/config.ts
- src/apiConstants.ts
- src/data/manglendemedvirkning/manglendeMedvirkningDocumentTexts.ts
- src/data/manglendemedvirkning/manglendeMedvirkningQueryHooks.ts
- src/data/manglendemedvirkning/manglendeMedvirkningTypes.ts
- src/data/manglendemedvirkning/useSendVurderingManglendeMedvirkning.tsx
- src/hooks/manglendemedvirkning/useManglendeMedvirkningVurderingDocument.ts
- src/sider/manglendemedvirkning/ForhandsvarselSide.tsx
- src/sider/manglendemedvirkning/ManglendeMedvirkningSide.tsx
- test/manglendemedvirkning/ManglendeMedvirkningTest.tsx
- test/manglendemedvirkning/vurderingDocuments.ts
- Ny side for forhåndsvarsel og innsending av dette
- Forhåndsvisning av brevet
- Feil hvis ingen begrunnelse skrevet inn og man trykker på Send
- Skjer foreløpig ingenting dersom man sender inn, kommer ikke til ny side. Tenkte egen PR for det.
https://github.com/user-attachments/assets/a1a463ff-36ea-4512-8017-3fcfc44e18fe
> IS-2620: Add manglende medvirkning forhandsvarsel page

- src/sider/arbeidsuforhet/Arbeidsuforhet.tsx
- src/sider/arbeidsuforhet/ForhandsvarselAfterDeadline.tsx
- src/sider/arbeidsuforhet/ForhandsvarselBeforeDeadline.tsx
- src/sider/arbeidsuforhet/ForhandsvarselSendt.tsx
- src/sider/arbeidsuforhet/avslag/AvslagForm.tsx
- src/sider/arbeidsuforhet/ikkeaktuell/ArbeidsuforhetIkkeAktuellSkjema.tsx
- src/sider/arbeidsuforhet/oppfylt/OppfyltForm.tsx
- test/arbeidsuforhet/ForhandsvarselSendtTest.tsx
Oppdaterer 8-4 sidene med mer riktig info, og tar i bruk Aksel-komponenter i større grad. Fikser også noe wonky ulikheter i tekststørrelser. Skal se ganske likt ut.
> IS-2620: Refactor arbeidsuforhet-sider

- Dockerfile
- mock/ismanglendemedvirkning/mockIsmanglendemedvirkning.ts
- src/data/manglendemedvirkning/manglendeMedvirkningDocumentTexts.ts
- src/data/manglendemedvirkning/manglendeMedvirkningQueryHooks.ts
- src/data/manglendemedvirkning/manglendeMedvirkningTypes.ts
- src/data/manglendemedvirkning/useSendVurderingManglendeMedvirkning.tsx
- src/hooks/manglendemedvirkning/useManglendeMedvirkningVurderingDocument.ts
- src/routers/AppRouter.tsx
- src/sider/manglendemedvirkning/ManglendeMedvirkning.tsx
- src/sider/manglendemedvirkning/ManglendeMedvirkningSide.tsx
- src/sider/manglendemedvirkning/forhandsvarsel/ForhandsvarselAfterDeadline.tsx
- src/sider/manglendemedvirkning/forhandsvarsel/ForhandsvarselBeforeDeadline.tsx
- src/sider/manglendemedvirkning/forhandsvarsel/ForhandsvarselSendt.tsx
- src/sider/manglendemedvirkning/forhandsvarsel/ForhandsvarselSkjema.tsx
- src/sider/manglendemedvirkning/oppfylt/OppfyltSide.tsx
- src/sider/manglendemedvirkning/oppfylt/OppfyltSkjema.tsx
- test/manglendemedvirkning/ManglendeMedvirkningTest.tsx
- test/manglendemedvirkning/OppfyltTest.tsx
- test/manglendemedvirkning/manglendeMedvirkningTestData.ts
- test/manglendemedvirkning/vurderingDocuments.ts
> IS-2620: Oppfylt

- src/data/manglendemedvirkning/manglendeMedvirkningDocumentTexts.ts
- src/hooks/manglendemedvirkning/useManglendeMedvirkningVurderingDocument.ts
- src/sider/manglendemedvirkning/ManglendeMedvirkningSide.tsx
- src/sider/manglendemedvirkning/ikkeaktuell/IkkeAktuellSide.tsx
- src/sider/manglendemedvirkning/ikkeaktuell/IkkeAktuellSkjema.tsx
- test/manglendemedvirkning/IkkeAktuellTest.tsx
- test/manglendemedvirkning/vurderingDocuments.ts
Mulighet for 8-8 ikke aktuell etter sendt forhåndsvarsel
> IS-2620: Ikke aktuell

- src/data/manglendemedvirkning/manglendeMedvirkningDocumentTexts.ts
- src/data/manglendemedvirkning/manglendeMedvirkningTypes.ts
- src/hooks/manglendemedvirkning/useManglendeMedvirkningVurderingDocument.ts
- src/routers/AppRouter.tsx
- src/sider/manglendemedvirkning/ManglendeMedvirkningButtons.tsx
- src/sider/manglendemedvirkning/ManglendeMedvirkningSide.tsx
- src/sider/manglendemedvirkning/unntak/UnntakSide.tsx
- src/sider/manglendemedvirkning/unntak/UnntakSkjema.tsx
- test/manglendemedvirkning/UnntakTest.tsx
- test/manglendemedvirkning/vurderingDocuments.ts
Venter litt på tilbakemelding fra Stine på tekster
> IS-2620: Add unntak manglende medvirkning side

- src/components/globalnavigasjon/GlobalNavigasjon.tsx
- src/utils/globalNavigasjonUtils.ts
- test/components/GlobalNavigasjonTest.tsx
Lagt til rød prikk når forhåndsvarselet går ut på manglende medvirkning. 
https://github.com/user-attachments/assets/f8f7fad7-6e20-4245-9951-817c1e027e10
> IS-2677: add rød prikk når forhåndsvarselet går ut på manglende medvirkning

- src/components/utdragFraSykefravaeret/Sykmeldinger.tsx
- src/sider/aktivitetskrav/vurdering/AktivitetskravVurderingAlert.tsx
- src/sider/aktivitetskrav/vurdering/VurderAktivitetskravTabs.tsx
- src/utils/aktivitetskravUtils.ts
- src/utils/globalNavigasjonUtils.ts
- Refactor util method slik at man bruker den samme funksjonen for å sjekke utgått forhåndsvarsel i aktivitetskrav som i manglende medvirkning. 
- fiksa styling på viktig informasjon knappen på utdrag fra sykefravær i hver sykmelding boks under sykmeldinger.
> Refactor util method

- src/data/manglendemedvirkning/manglendeMedvirkningTypes.ts
- src/sider/manglendemedvirkning/ManglendeMedvirkning.tsx
- src/sider/manglendemedvirkning/ManglendeMedvirkningNyVurdering.tsx
- src/sider/manglendemedvirkning/ManglendeMedvirkningStartetVurdering.tsx
- test/manglendemedvirkning/ForhandsvarselTest.tsx
- test/manglendemedvirkning/ManglendeMedvirkningTest.tsx
- test/manglendemedvirkning/manglendeMedvirkningTestData.ts
Legger til komponent for å starte ny vurdering ala 8-4.
> IS-2669: Side for Ny vurdering manglende medvirkning

- src/data/manglendemedvirkning/manglendeMedvirkningDocumentTexts.ts
- src/sider/manglendemedvirkning/ikkeaktuell/IkkeAktuellSkjema.tsx
- src/sider/manglendemedvirkning/oppfylt/OppfyltSkjema.tsx
- src/sider/manglendemedvirkning/stans/StansSkjema.tsx
- src/sider/manglendemedvirkning/unntak/UnntakSkjema.tsx
- test/manglendemedvirkning/IkkeAktuellTest.tsx
- test/manglendemedvirkning/OppfyltTest.tsx
- test/manglendemedvirkning/StansTest.tsx
- test/manglendemedvirkning/UnntakTest.tsx
Justert noen tekster etter gjennomgang med Stine og flyttet på Avbryt-knappen slik at det er likt på alle sider.
> IS-2684: Adjust some texts and move avbryt-button

- src/components/SideLaster.tsx
- src/sider/manglendemedvirkning/ManglendeMedvirkningHistorikk.tsx
- src/sider/manglendemedvirkning/ManglendeMedvirkningSide.tsx
- test/manglendemedvirkning/ManglendeMedvirkningHistorikkTest.tsx
- test/manglendemedvirkning/manglendeMedvirkningTestData.ts
Lagt til historikk på manglende medvirkning 
Forhåndsvarsel
> IS-2668: add historikk på manglende medvirkning

- src/sider/manglendemedvirkning/stans/StansSkjema.tsx
- test/manglendemedvirkning/StansTest.tsx
Endret tekst i veiledningen for hvordan lage Gosys-oppgave til NAY under stansskjema på stanssiden på manglende medvirkning etter rettelse fra NAY.
> IS-2695: edit text in veiledningen på stanssiden manglende medvirkning

- src/sider/manglendemedvirkning/oppfylt/OppfyltSkjema.tsx
- src/sider/manglendemedvirkning/unntak/UnntakSkjema.tsx
- test/manglendemedvirkning/OppfyltTest.tsx
- test/manglendemedvirkning/UnntakTest.tsx
Lagt til en tekst om å huske å informere bruker når man setter et unntak i manglende medvirkning.
> IS-2699: add informer bruker text

- src/data/frisktilarbeid/frisktilarbeidTypes.ts
- src/mocks/isfrisktilarbeid/mockIsfrisktilarbeid.ts
- src/sider/frisktilarbeid/VedtakFattet.tsx
- test/frisktilarbeid/VedtakFattetTest.tsx
- test/frisktilarbeid/frisktilarbeidTestData.ts
Viser warning alert dersom infotrygd-status ikke ok - dvs når registrering av vedtaket i infotrygd har feilet, vi ikke har mottatt kvittering fra infotrygd eller kvittering inneholder feil.
> IS-2660: Show warning alert if infotrygd status not ok

- src/sider/arbeidsuforhet/avslag/ArbeidsuforhetAvslag.tsx
- src/sider/arbeidsuforhet/avslag/AvslagDatePicker.tsx
- src/sider/arbeidsuforhet/avslag/AvslagForm.tsx
- test/arbeidsuforhet/avslag/AvslagFormTest.tsx
- test/dialogmote/AvlysDialogmoteSkjemaTest.tsx
- Begrens dato veileder kan stanse penger fra etter at et forhåndsvarsel om stans har gått ut.
https://github.com/user-attachments/assets/12e3f419-69cd-48a1-97ac-3d5308cedf0f
> IS-2713: Limit date for avslag of sykepenger

- src/mocks/syfosmregister/sykmeldingerMock.ts
- src/sider/sykmeldinger/VurderBistandsbehov.tsx
- test/sykmeldinger/VurderBistandsbehovTest.tsx
Forslag til hvordan felt 7.2 og 7.3 fra sykmeldingen kan vises.
> IS-2710: Vise flere felter fra sykmeldingen

- server/unleash.ts
- src/components/globalnavigasjon/GlobalNavigasjon.tsx
- src/data/unleash/unleash_types.ts
- test/components/GlobalNavigasjonTest.tsx
- Fjerner toggle for manglende medvirkning funksjonalitet
> IS-2730: Remove toggle for manglende medvirkning

- src/sider/senoppfolging/KandidatIkkeSvart.tsx
- src/utils/datoUtils.ts
- src/utils/globalNavigasjonUtils.ts
- src/utils/senOppfolgingUtils.ts
- test/senoppfolging/SenOppfolgingTest.tsx
- test/utils/senOppfolgingUtilsTest.ts
Lignende tekst som vi har i dag når den sykmeldte _ikke_ har fått varsel.
> IS-2733: Forbedret tekst når sykmeldte har fått varsel men ikke svart på snart slutt på sykepengene

- src/components/globalnavigasjon/GlobalNavigasjon.tsx
- src/data/historikk/types/historikkTypes.ts
- src/data/manglendemedvirkning/manglendeMedvirkningQueryHooks.ts
- src/sider/historikk/Historikk.tsx
- src/sider/historikk/container/HistorikkContainer.tsx
- src/sider/manglendemedvirkning/ManglendeMedvirkning.tsx
- src/sider/manglendemedvirkning/ManglendeMedvirkningHistorikk.tsx
- src/sider/manglendemedvirkning/ManglendeMedvirkningNyVurdering.tsx
- src/sider/manglendemedvirkning/ManglendeMedvirkningSide.tsx
- src/sider/manglendemedvirkning/ikkeaktuell/IkkeAktuellSide.tsx
- src/sider/manglendemedvirkning/oppfylt/OppfyltSide.tsx
- src/sider/manglendemedvirkning/stans/StansSide.tsx
- src/sider/manglendemedvirkning/unntak/UnntakSide.tsx
- Legger til manglende medvirkning i historikk
> IS-2748: Add manglende medvirkning vurdering to historikk

- src/sider/senoppfolging/SenOppfolging.tsx
Justerer teksten i Modia til å stemme med logikken hos esyfo for utsending av varsel.
Før:
Nå:
> IS-2742: Correct snart slutt på sykepengene text

- src/components/globalnavigasjon/GlobalNavigasjon.tsx
- src/sider/arbeidsuforhet/ForhandsvarselAfterDeadline.tsx
- src/sider/arbeidsuforhet/ForhandsvarselBeforeDeadline.tsx
- src/sider/arbeidsuforhet/ForhandsvarselSendt.tsx
- src/sider/arbeidsuforhet/NyVurdering.tsx
- src/sider/arbeidsuforhet/StartetVurdering.tsx
- src/sider/arbeidsuforhet/avslag/ArbeidsuforhetAvslag.tsx
- src/sider/manglendemedvirkning/ManglendeMedvirkningNyVurdering.tsx
- test/arbeidsuforhet/ForhandsvarselSendtTest.tsx
Fikser noen tilfeller av oppslag i array som potensielt kan returnere undefined.
https://dev.to/yardenporat/typescripts-nouncheckedindexedaccess-strictnullchecks-4l1j
> IS-2030: Fix some noUncheckedIndexedAccess violations

- src/hooks/dialogmote/document/useReferatDocument.ts
Fikser bug i referat som gjorde at siden krasjet ved innsending/forhåndsvisning når man hadde krysset av for én standardtekst og mellomlagret dette.
Ref: https://jira.adeo.no/browse/FAGSYSTEM-352920
> IS-2759: Fix referat bug

- src/data/historikk/types/historikkTypes.ts
- src/sider/historikk/Historikk.tsx
- src/sider/historikk/container/HistorikkContainer.tsx
Lagt til 8.5 friskmelding til arbeidsformidling i historikken
> IS-2741: add 8.5 to historikk

- src/data/aktivitetskrav/aktivitetskravQueryHooks.ts
- src/data/dialogmotekandidat/dialogmotekandidatQueryHooks.ts
- src/data/dialogmotekandidat/dialogmotekandidatTypes.ts
- src/data/historikk/types/historikkTypes.ts
- src/mocks/isdialogmotekandidat/mockIsdialogmotekandidat.ts
- src/sider/historikk/Historikk.tsx
- src/sider/historikk/container/HistorikkContainer.tsx
Lagt til dialogmøte-kandidat-historikk.
Avhengig av api i https://github.com/navikt/isdialogmotekandidat/pull/182
> IS-2752: Dialogmøte-kandidat historikk

- server/unleash.ts
- src/components/flexjar/EmojiRatingFlexjar.tsx
- src/components/flexjar/senfase/AndreTilbakemeldingerTextArea.tsx
- src/components/flexjar/senfase/HvordanBrukerDuArenaTextArea.tsx
- src/components/flexjar/senfase/SenFaseFlexjar.tsx
- src/data/unleash/unleash_types.ts
- src/hooks/useLocalStorageState.ts
- src/sider/Side.tsx
- src/sider/senoppfolging/NewVurderingForm.tsx
- src/sider/senoppfolging/SenOppfolging.tsx
- src/utils/amplitude.ts
- test/flexjar/FlexjarTest.tsx
Lagt til flexjar på sen fase siden etter at man har gjort en vurdering.
> IS-2755: Add flexjar to sen fase page

- src/components/flexjar/senfase/SenFaseFlexjar.tsx
Gjorde om tekstfeltene i feedback input i sen fase flexjar fra å være undefined til tom streng når bruker ikke skriver inn noe tekst i feltet.
> IS-2755: changed feedback input sen fase flexjar

- src/data/historikk/types/historikkTypes.ts
- src/hooks/historikk/useHistorikk.ts
- src/hooks/historikk/useSenOppfolgingHistorikk.ts
- src/sider/historikk/Historikk.tsx
- test/historikk/HistorikkTest.tsx
Lagt til sen oppfølging i historikken
> IS-2767 Lagt til sen oppfølging i historikken

- src/data/dialogmote/dialogmoteQueryHooks.ts
- src/data/dialogmote/dialogmoteStatusEndringHistorikkQuery.ts
- src/data/dialogmote/types/dialogmoteStatusEndringTypes.ts
- src/hooks/historikk/useDialogmoteStatusEndringHistorikk.ts
- src/hooks/historikk/useHistorikk.ts
- src/mocks/isdialogmote/dialogmoterMock.ts
- src/mocks/isdialogmote/mockIsdialogmote.ts
- test/historikk/HistorikkTest.tsx
Lagt inn endringer i statuser for dialogmøte. Tett knyttet til https://github.com/navikt/isdialogmote/pull/554.
> IS-1879: Add historikk for dialogmote statusendringer

- src/sider/senoppfolging/VeiledningRutine.tsx
Bruker lenke som også logger til amplitude. Skal høre med jurist-Ingrid også om teksten gir mening. Men hva synes dere?
Blir også litt wonky med den `ExternalLinkIcon` når lenka brytes opp over flere linjer. Alternativet er å ta den inntil teksten, men sliter med å aligne figuren til teksten da. Mulig det er noe css-triks jeg ikke kan som fikser det.
> IS-2771: Add link to rutine for § 14a

- src/mocks/ismeroppfolging/mockIsmeroppfolging.ts
- src/sider/senoppfolging/SenOppfolging.tsx
- src/sider/senoppfolging/VurdertAv.tsx
- src/sider/senoppfolging/VurdertKandidat.tsx
- src/sider/senoppfolging/historikk/SenOppfolgingHistorikk.tsx
- src/sider/senoppfolging/historikk/SenOppfolgingHistorikkItem.tsx
- test/senoppfolging/SenOppfolgingHistorikkTest.tsx
- test/senoppfolging/SenOppfolgingTest.tsx
Lagt til historikk-komponent nederst på siden. 
Viser dato for varsel (eller dato for svar dersom vi ikke har varsel) i accordion header.
Viser info om varsel, svar og evt vurdering i accordion body.
Gjenstår en avsjekk på design og innhold.
> IS-2786: Historikk på side for Snart slutt på sykepengene

- src/components/globalnavigasjon/GlobalNavigasjon.tsx
- test/components/GlobalNavigasjonTest.tsx
Endret rekkefølgen på menypunktene.
> IS-2820: edit rekkefølgen menypunkter

- server/unleash.ts
- src/components/globalnavigasjon/GlobalNavigasjon.tsx
- src/data/unleash/unleash_types.ts
- test/components/GlobalNavigasjonTest.tsx
Friskmelding til arbeidsformidling og sen fase er skrudd på for alle i prod så tenker disse kan fjernes
> Remove toggles no longer in use

- src/data/arbeidsuforhet/arbeidsuforhetTypes.ts
- src/sider/arbeidsuforhet/SendForhandsvarselSkjema.tsx
- test/aktivitetskrav/varselDocuments.ts
- test/arbeidsuforhet/ArbeidsuforhetForhandsvarselTest.tsx
- test/arbeidsuforhet/documents.ts
Utvidet frist for forhåndsvarsel arbeidsuførhet i forbindelse med jul
> IS-2817: Utvidet frist jul (arbeidsuforhet)

- src/sider/manglendemedvirkning/forhandsvarsel/ForhandsvarselSkjema.tsx
Tror vi bør tilpasse svarfristen her også (og det er enklere siden backend'en bruker det som kommer herfra fra før).
Avventer litt på tilbakemelding fra Stine.
> IS-2817: Utvidet frist jul (manglende medvirkning)

- src/sider/aktivitetskrav/vurdering/AktivitetskravVurderingAlert.tsx
Alert i forbindelse med lengre frist for forhåndsvarsel
> IS-2817: Alert utvidet frist jul (aktivitetskrav)

- src/components/InfoUtsattFristJuletid.tsx
- src/sider/aktivitetskrav/vurdering/AktivitetskravVurderingAlert.tsx
- src/sider/aktivitetskrav/vurdering/SendForhandsvarselSkjema.tsx
- src/sider/arbeidsuforhet/SendForhandsvarselSkjema.tsx
- src/sider/manglendemedvirkning/forhandsvarsel/ForhandsvarselSkjema.tsx
- src/utils/forhandsvarselUtils.ts
- Lagt til en alert før bruker sender forhåndsvarsel om at fristen er endret pga juletider. 
- Endret dato for når fristen går tilbake til 3 uker fra 16 desember til 19 desember. 
Se her for plassering på de ulike sidene: 
<details>
<summary>Aktivitetskrav</summary>
</details>
<details>
<summary>Manglende medvirkning</summary>
</details>
<details>
<summary>Arbeidsuførhet</summary>
</details>
> IS-2846: add alert om utsatt frist pga jul og røde dager

- src/components/PapirsykmeldingTag.tsx
- src/components/UtenlandskSykmeldingTag.tsx
- src/components/utdragFraSykefravaeret/Sykmeldinger.tsx
- src/sider/sykmeldinger/container/SykmeldingerContainer.tsx
- src/sider/sykmeldinger/sykmeldinger/DineSykmeldinger.tsx
- src/sider/sykmeldinger/sykmeldinger/SykmeldingLinkPanel.tsx
- src/sider/sykmeldinger/sykmeldinger/SykmeldingPeriodeInfo.tsx
- src/sider/sykmeldinger/sykmeldinger/Sykmeldinger.tsx
- test/components/SykmeldingPeriodeInfoTest.tsx
- Refaktorering som bygger på [denne](https://github.com/navikt/syfomodiaperson/pull/1566)
> IS-2852: Show viktig informasjon ikon on sykmelding

- src/api/axios.ts
- src/api/errors.ts
- src/components/SkjemaInnsendingFeil.tsx
Lagt til egen type feilmelding for status-kode 409 fra backend slik at vi kan gi en litt bedre feilmelding til bruker ved slike feil.
> IS-2848: Handle conflict error

- src/components/utdragFraSykefravaeret/UtdragFraSykefravaeret.tsx
- src/sider/arbeidsuforhet/ArbeidsuforhetSide.tsx
- src/sider/arbeidsuforhet/RundskrivLenke.tsx
- Lagt til lenke til rundskriv på 8-4 arbeidsuførhet
> IS-2458: Add lenke til rundskriv

- src/sider/historikk/Historikk.tsx
- test/historikk/HistorikkTest.tsx
Jobber fortsatt med å lande litt rundt hvordan det skal se ut.
Foreløpig ser det slik ut: 
Her er alternativet:
> IS-2874: Show link to tiltakshistorikk

- src/sider/aktivitetskrav/AktivitetskravContainer.tsx
- src/sider/aktivitetskrav/NyttigeLenkerBox.tsx
- lagt til lenke til rundskriv på aktivitetskravsiden
> IS-2604: add rundskriv lenke på aktivitetskravsiden

- src/sider/manglendemedvirkning/ManglendeMedvirkningSide.tsx
- src/sider/manglendemedvirkning/NyttigeLenkerBox.tsx
- Lagt til lenke til rundskriv på manglende medvirkning
> IS-2604: add rundskriv lenke på manglende medvirkning

- src/components/KunnskapsbankTrygdemedisinLenke.tsx
- src/sider/aktivitetskrav/NyttigeLenkerBox.tsx
- src/sider/arbeidsuforhet/ArbeidsuforhetSide.tsx
- src/sider/arbeidsuforhet/NyttigeLenkerBox.tsx
- Lagt til lenke til kunnskapsbank for trygdemedisin på aktivitetskrav og arbeidsuførhet
> IS-2653: add kunnskapsbank trygdemedisin lenke

- src/data/oppfolgingsoppgave/types.ts
Har lagt til `samtale med bruker` som ny oppfølgingsgrunn. Er avhengig (vil jeg tro) av backend PR: https://github.com/navikt/ishuskelapp/pull/90
> IS-2891: Lagt til samtale med bruker som ny oppfølgingsgrunn

- src/routers/AppRouter.tsx
- src/sider/oppfolgingsplan/container/OppfoelgingsPlanerOversiktContainer.tsx
- src/sider/oppfolgingsplan/container/OppfolgingsplanContainer.tsx
- src/sider/oppfolgingsplan/lps/BehandleOppfolgingsplanLPS.tsx
- src/sider/oppfolgingsplan/lps/OppfolgingsplanerOversiktLPS.tsx
- src/sider/oppfolgingsplan/oppfolgingsplaner/IngenPlaner.tsx
- src/sider/oppfolgingsplan/oppfolgingsplaner/Oppfolgingsplan.tsx
- src/sider/oppfolgingsplan/oppfolgingsplaner/OppfolgingsplanLink.tsx
- src/sider/oppfolgingsplan/oppfolgingsplaner/OppfolgingsplanVirksomhetTittel.tsx
- src/sider/oppfolgingsplan/oppfolgingsplaner/OppfolgingsplanerOversikt.tsx
- Forberedende refaktorering før man legger inn selve be om oppfølgingsplan funksjonaliteten
> IS-2999: Preparatory refactor

- src/data/dialogmote/dialogmoteTexts.ts
- src/hooks/dialogmote/document/useAvlysningDocument.ts
- src/hooks/dialogmote/document/useDialogmoteDocumentComponents.ts
- src/hooks/dialogmote/document/useInnkallingDocument.ts
- src/hooks/dialogmote/document/useReferatDocument.ts
- src/hooks/dialogmote/document/useTidStedDocument.ts
- test/dialogmote/testDataDocuments.ts
- Flyttet sendt dato nederst i alle brevene som hører til dialogmøte
Før:
Nå:
> IS-2470: Move sendt dato brev dialog møte

- src/sider/dialogmoter/components/DialogmoteFrist.tsx
- src/sider/dialogmoter/components/innkalling/InnkallingDialogmotePanel.tsx
- Lagt til fristdatoen for dialogmøte 2
> IS-3001: add fristdato for dialogmøte

- src/components/oppfolgingsoppgave/OppfolgingsoppgaveModal.tsx
- src/data/oppfolgingsoppgave/types.ts
- src/utils/amplitude.ts
- test/oppfolgingsoppgave/OppfolgingsoppgaveModalTest.tsx
Gjør det mulig å endre oppfølgingsgrunn på oppfølgingsoppgave
TODO:
> IS-2790: Edit oppfolgingsgrunn

- src/sider/dialogmoter/components/motehistorikk/MotebehovHistorikk.tsx
Spiller videre på https://github.com/navikt/syfomodiaperson/pull/1607 for å logge interaksjoner med accordions.
> IS-2888: Add amplitude logging of accordion interaction

- test/sider/oppfolgingsplaner/OppfolgingsplanerOversiktTest.tsx
- Legger til tester for be om oppfølgingsplan funksjonalitet
- Begynner smått å flytte hvordan vi strukturere testene slik at testene gjenspeiler mappestruktur til produksjonskoden ved å lage en `/sider` mappe
NB! Må nok lage mer tester etterhvert som utseende og oppførsel endrer seg før vi går i prod.
Gjelder funksjonalitet som er markert på skjermbilde
> IS-2999-2-Add-tests

- src/hooks/oppfolgingsplan/useOppfolgingsplanForesporselDocument.ts
- src/sider/oppfolgingsplan/oppfolgingsplaner/BeOmOppfolgingsplan.tsx
- test/sider/oppfolgingsplaner/OppfolgingsplanerOversiktTest.tsx
- test/sider/oppfolgingsplaner/oppfolgingsplanTestdata.ts
Sender inn dokument fra frontend, som deretter journalføres i backend.
Foreløpig verifisert i tester og i network-taben. Skal teste i dev.
> IS-2998: Add document for oppfolgingsplan foresporsel

- src/components/personkort/EpostButton.tsx
- src/components/personkort/ledere/PersonKortVirksomhetLedere.tsx
- Viser epost adresse i personkortet under nærmeste leder
Før: 
Nå:
> IS-3041: Show epost adresse personkort

- src/routers/AppRouter.tsx
- src/sider/sykepengsoknader/SykepengesoknaderSide.tsx
- src/sider/sykepengsoknader/SykmeldingUtdragContainer.tsx
- src/sider/sykepengsoknader/container/SykepengesoknadSide.tsx
- src/sider/sykepengsoknader/soknad-arbeidstaker-ny/SendtSoknadArbeidstakerNy.tsx
- src/sider/sykepengsoknader/soknader/Soknader.tsx
- src/sider/sykepengsoknader/soknader/SoknaderTeasere.tsx
- test/containers/SykepengesoknadSideTest.tsx
- Noen ikke så nyttige refaktoreringer som jeg gjorde imens jeg undersøkte om det var noe enkel speiling jeg kunne fjerne på sykepengesøknad sidene
- Skulle se om det var noe enkel speiling jeg fikk fjernet. Viste seg at noe av dette er en del av DTO'en som kommer fra [sykepengesoknad-backend](https://github.com/navikt/sykepengesoknad-backend)
Veldig interessant at denne👇 vises basert på hva som ligger i `SykepengesoknadDTO` som kommer fra `sykepengesoknad-backend`
> IS: Sykepengesoknad mini refactor

- src/components/personkort/OversiktLenker.tsx
I første omgang er rekkefølgen lik det som er for oversikten. Så skal jeg se hvor stor jobb det er å gjøre denne menyen lik som for oversikten, men det blir i så fall i en annen PR.
> IS-3097: Lagt til lenke til søk

- src/sider/sykmeldinger/sykmelding/DinSendteSykmelding.tsx
> IS-3102: Fjern accordion i visning av sendt sykmelding

- .env.template
- .nais/naiserator-dev.yaml
- .nais/naiserator-prod.yaml
- server/config.ts
- server/proxy.ts
- src/apiConstants.ts
- src/components/personkort/PersonkortHeader/PersonkortHeaderTags.tsx
- src/data/uforegrad/uforegradQueryHooks.ts
- src/data/uforegrad/uforegradTypes.ts
- src/mocks/handlers.ts
- src/mocks/uforegrad/mockUforegrad.ts
- test/components/personkort/PersonkortHeaderTest.tsx
Kaller `pensjon-pen` for å hente uføregrad. Ser ut til å funke i dev, men var redd det kunne bli noe greier der siden appen har ulike navn for dev og prod.
Foreløpig skrevet `Ufør xx%` i stedet for `Uføregrad xx%` for å spare plass, men vi kan diskutere det.
Co-authored by: @ingring
>  IS-3034: Get uforegrad from pesys

- src/sider/manglendemedvirkning/ManglendeMedvirkningButtons.tsx
- src/sider/manglendemedvirkning/stans/StansSkjema.tsx
- src/sider/manglendemedvirkning/stans/StansdatoDatePicker.tsx
- test/manglendemedvirkning/ForhandsvarselTest.tsx
- test/manglendemedvirkning/StansTest.tsx
Endret tekster og utseende i skjemaet for å skrive innstilling ifm. manglende medvirkning for å reflektere at man ikke lenger trenger å trykke manuelt på stoppknappen ettersom dette skal gjøres automatisk av backend ved innsendt innstilling.
Avhengig av denne (i en eller annen form): https://github.com/navikt/ispengestopp/pull/161
Satt denne som draft inntil videre, men er ferdig.
> IS-3110: Endret tekster og utseende i skjemaet for å skrive innstilling ifm. manglende medvirkning

- src/sider/behandlerdialog/meldingtilbehandler/MeldingTilBehandler.tsx
- src/sider/behandlerdialog/meldingtilbehandler/MeldingTilBehandlerSkjema.tsx
- test/behandlerdialog/MeldingTilBehandlerTest.tsx
Dette skulle være med på forrige PR om dialogmeldingssiden, men jeg glemte visst å commite det. Fant ut nå at det lå som unstaged så pushet det opp.
> IS-2867: Update texts for dialogmelding

- src/sider/manglendemedvirkning/stans/StansSkjema.tsx
- test/manglendemedvirkning/StansTest.tsx
Etter hvert som arbeidsuførhet og aktivitetskrav har blitt ferdigstilt så kom det noen justeringer på disse som ikke ble gjort i kontekst av manglende medvirkning. Denne PRen endrer det slik at disse har likt utseende og ordlyd der det skal være likt.
(Litt mindre tekst på punktlista under `Videre må du huske å`)
> IS-3110: Gjort noen små justeringer til skjema for stans av sykepenger ifm. manglende medvirkning

- src/sider/frisktilarbeid/VeiledningBox.tsx
> IS-3185: Endret rutinebeskrivelse for friskmelding til arbeidsformidling

- src/components/motebehov/BehandleMotebehovKnapp.tsx
- src/mocks/syfomotebehov/motebehovMock.ts
- src/utils/motebehovUtils.ts
- test/dialogmote/Motebehov/DialogmoteOnskePanelTest.tsx
- test/utils/motebehovUtilsTest.js
Endret slik at det informasjon om det siste behandlede møtebehovet som vises i stedet for tidligere behandlet møtebehov. Gjelder: https://jira.adeo.no/browse/FAGSYSTEM-375218
> IS-3203: Endret slik at det er informasjon om det siste behandlede møtebehovet som vises

- src/sider/senoppfolging/VeiledningRutine.tsx
14a er nå i Modia og ikke Arena. Stine så over teksten og landet på dette
Se menyen til høyre for endring.
> IS-3250: Refactor 14a-texts

- src/components/personkort/PersonkortChangeEnhet.tsx
- src/components/personkort/PersonkortEnhet.tsx
- src/data/behandlendeenhet/types/BehandlendeEnhetDTOs.ts
- src/mocks/syfobehandlendeenhet/behandlendeEnhetMock.ts
- src/mocks/syfobehandlendeenhet/mockSyfobehandlendeenhet.ts
- test/components/personkort/PersonkortEnhetTest.tsx
- test/data/behandlendeEnhetQueryHooksTest.tsx
Endrer logikken for å ta høyde for at oppfolgingsenhet ofte vil være null når denne endringen merges: 
https://github.com/navikt/syfobehandlendeenhet/pull/193
> Tilpasser til ny DTO from behandlende enhet

- public/index.html
> IS-3161: Legger til umami til dev

- src/components/personkort/PersonkortHeader/MaksdatoSummary.tsx
- test/components/personkort/PersonkortHeaderTest.tsx
Endret teksten `Utbetalt tom` til `Søknad behandlet tom`.
> IS-3224: Endret teksten Utbetalt tom til Søknad behandlet tom

- src/components/motebehov/BehandleMotebehovKnapp.tsx
- src/components/motebehov/HjelpetekstVedMeldtBehov.tsx
- src/mocks/syfomotebehov/motebehovMock.ts
- test/dialogmote/Motebehov/DialogmoteOnskePanelTest.tsx
Lagt til hjelpetekst ved når arbeidstaker eller arbeidsgiver melder behov for et møte.
Ubehandlet og valgt radiobutton:
Behandlet:
> IS-3070: Lagt til hjelpetekst ved innmeldt møtebehov

- src/hooks/arbeidsuforhet/useArbeidsuforhetVurderingDocument.ts
- src/sider/arbeidsuforhet/avslag/ArbeidsuforhetAvslag.tsx
- src/sider/arbeidsuforhet/avslag/AvslagForm.tsx
- src/sider/arbeidsuforhet/data/arbeidsuforhetDocumentTexts.ts
- test/arbeidsuforhet/avslag/AvslagFormTest.tsx
- test/arbeidsuforhet/documents.ts
Har lagt på en setning øverst i avslags-dokumentet.
> IS-3306: Add info about forhandsvarsel in avslagstekst

- public/index.html
> IS-3161: Add umami to prod

- CODEOWNERS
> IS: Set codeowner

- src/routers/AppRouter.tsx
- Refaktorerer routing for sykepengesoknad sider
> IS: Refactor routing for sykepenger page

- src/sider/arbeidsuforhet/oppfylt/ArbeidsuforhetOppfylt.tsx
- src/sider/arbeidsuforhet/oppfylt/OppfyltForm.tsx
- test/arbeidsuforhet/OppfyltFormTest.tsx
- Utvider fra 1000 til 8000 tillatte tegn
> IS-3266: Utvid antall tillatte tegn for oppfylt vurdering 8-4

- src/sider/arbeidsuforhet/SendForhandsvarselSkjema.tsx
- Øker antall tillatte tegn i et forhåndsvarsel.
- Fikser også slik at det blir space mellom forhåndsvarsel skjema og historikk.
Hvis ny synlig feature – ta screenshot!
> IS-3315: Ok antall tillatte tegn forhandsvarsel arbeidsuforhet

- src/sider/historikk/Historikk.tsx
- src/sider/historikk/container/HistorikkContainer.tsx
- test/historikk/HistorikkTest.tsx
- Velger fullstendig historikk som default valg på filtrering angående hvilke historiske hendelser man ønsker å se.
https://github.com/user-attachments/assets/ba85ef9b-4ad3-432c-90d5-6a6d18522bde
> IS-3331: Velg fullstendig historikk som default

- src/sider/arbeidsuforhet/VelgVurdering.tsx
- src/sider/arbeidsuforhet/avslag/AvslagForm.tsx
- src/sider/arbeidsuforhet/innstillingutenforhandsvarsel/InnstillingUtenForhandsvarsel.tsx
- test/arbeidsuforhet/avslag/AvslagFormTest.tsx
- Endrer tekst på 8-4
Før
Avslag uten forhåndsvarsel
Avslag etter forhåndsvarsel
Etter
Avslag etter forhåndsvarsel
Avslag uten forhåndsvarsel
> IS-3336: Text changes

- server/unleash.ts
- src/data/unleash/unleash_types.ts
- src/sider/oppfolgingsplan/oppfolgingsplaner/AktiveOppfolgingsplaner.tsx
- Fjerner toggle for å be om en oppfølgingsplan
> IS-3347: Fjern toggle for a be om oppfolgingsplan

- src/sider/frisktilarbeid/FattVedtakSkjema.tsx
- src/sider/frisktilarbeid/VeiledningBox.tsx
Infotekster om at Gosys-oppgave nå blir laget automatisk ved registrering av vedtak om friskmelding til arbeidsformidling.
> IS-3292: Infoboks om automatisk Gosys-oppgave

- src/mocks/isarbeidsuforhet/mockIsarbeidsuforhet.ts
- src/sider/arbeidsuforhet/SendForhandsvarselSkjema.tsx
- src/sider/arbeidsuforhet/avslag/AvslagForm.tsx
- src/sider/arbeidsuforhet/data/arbeidsuforhetTypes.ts
- src/sider/arbeidsuforhet/hooks/useArbeidsuforhetVurderingDocument.ts
- src/sider/arbeidsuforhet/hooks/useSaveVurderingArbeidsuforhet.ts
- src/sider/arbeidsuforhet/ikkeaktuell/ArbeidsuforhetIkkeAktuellSkjema.tsx
- src/sider/arbeidsuforhet/innstillingutenforhandsvarsel/InnstillingUtenForhandsvarsel.tsx
- src/sider/arbeidsuforhet/innstillingutenforhandsvarsel/OppgaveSendtFraNayDatepicker.tsx
- src/sider/arbeidsuforhet/oppfylt/OppfyltForm.tsx
- src/utils/datoUtils.ts
- test/arbeidsuforhet/ArbeidsuforhetForhandsvarselTest.tsx
- test/arbeidsuforhet/ArbeidsuforhetIkkeAktuellTest.tsx
- test/arbeidsuforhet/OppfyltFormTest.tsx
- test/arbeidsuforhet/avslag/AvslagFormTest.tsx
- Endrer valg fra hva årsaken til innstilling uten forhåndsvarsel er, til hvem som initierte vurderingen
- [Se tilhørende PR i](https://github.com/navikt/isarbeidsuforhet/pull/158) `isarbeidsuforhet`
Før
Etter
> IS-3337: Change radiogroup to igangsatt av

- src/components/oppfolgingsoppgave/FristDatePicker.tsx
- src/components/oppfolgingsoppgave/OpenOppfolgingsoppgaveModalButton.tsx
- src/components/oppfolgingsoppgave/Oppfolgingsoppgave.tsx
- src/components/oppfolgingsoppgave/OppfolgingsoppgaveModal.tsx
- src/components/side/Side.tsx
- src/data/oppfolgingsoppgave/types.ts
- test/oppfolgingsoppgave/OppfolgingsoppgaveModalTest.tsx
- Fristen for oppfølgingsoppgave er nå obligatorisk å sette.
- Flytter også selve datepickeren ut i en egen komponent
> IS-3004: Sett frist obligatorisk for oppfolgingsoppgave

- src/sider/arbeidsuforhet/VelgVurdering.tsx
- Fikser tekst som refererer til knapp med feil tekst
> IS: Fix text referencing button with wrong text

- src/sider/arbeidsuforhet/ikkeaktuell/ArbeidsuforhetIkkeAktuell.tsx
- src/sider/arbeidsuforhet/ikkeaktuell/ArbeidsuforhetIkkeAktuellSkjema.tsx
- test/arbeidsuforhet/ArbeidsuforhetIkkeAktuellTest.tsx
- Legger til instruksjoner om å opplyse bruker ettersom sykepenger ikke blir stanset likevel.
Før
Etter
> IS-3393: Legger til instruksjoner IKKE_AKTUELL vurdering arbeidsuforhet

- .nais/naiserator-dev.yaml
- .nais/naiserator-prod.yaml
- public/index.html
- Samme data vises for umami dashboardet i metabase. Gjør et forsøk på å fikse det. 
- Finnes det noe bedre måte å teste på enn å faktisk deploye til prod for å se om dashboardet får inn riktige data? 🤔
Se [dev](https://metabase.ansatt.nav.no/dashboard/716-nav-webstatistikk?dato=past30days~&nettside=syfomodiaperson.intern.dev.nav.no&url-sti_er_lik=*)
Se [prod](https://metabase.ansatt.nav.no/dashboard/716-nav-webstatistikk?dato=past30days~&nettside=syfomodiaperson.intern.nav.no&url-sti_er_lik=*)
> IS-3377: Fix umami tracking

- src/sider/aktivitetskrav/vurdering/InnstillingOmStansSkjema.tsx
- src/sider/arbeidsuforhet/VelgVurdering.tsx
- src/sider/arbeidsuforhet/avslag/AvslagForm.tsx
- src/sider/arbeidsuforhet/hooks/useArbeidsuforhetVurderingDocument.ts
- src/sider/frisktilarbeid/VeiledningBox.tsx
- src/sider/manglendemedvirkning/stans/StansSkjema.tsx
- test/aktivitetskrav/vurdering/AktivitetskravForhandsvarselTest.tsx
- test/aktivitetskrav/vurdering/VurderAktivitetskravTest.tsx
- test/arbeidsuforhet/ArbeidsuforhetTest.tsx
- test/arbeidsuforhet/avslag/ArbeidsuforhetAvslagTest.tsx
- test/arbeidsuforhet/avslag/AvslagFormTest.tsx
- test/manglendemedvirkning/StansTest.tsx
- Legger til informasjon for å tydeliggjøre når de skal gjøre hvilke vurderinger
- Endrer også bruk av NAY til "Nav arbeid og ytelser" etter prat med Sigurd og Stine
Før
Etter
> IS-3388: Legg til veiledning for nar man gjor hvilken vurdering

- src/data/frisktilarbeid/frisktilarbeidTypes.ts
- src/mocks/isfrisktilarbeid/mockIsfrisktilarbeid.ts
- src/sider/frisktilarbeid/VedtakInfoPanel.tsx
- test/frisktilarbeid/VedtakInfoPanelTest.tsx
- test/frisktilarbeid/frisktilarbeidTestData.ts
Viser riktig tilstand for journalforing og gosys-oppgave
> IS-3384: Viser riktig tilstand for journalforing og gosys-oppgave

- src/context/notification/NotificationContext.tsx
- src/sider/arbeidsuforhet/NyVurdering.tsx
- src/sider/arbeidsuforhet/innstillingutenforhandsvarsel/InnstillingUtenForhandsvarsel.tsx
- Legger til veiledning om at gosys oppgave fra NAY må svares på for "avslag uten forhåndsvarsel" -vurdering.
Før - Det som er fjernet er markert
Etter
https://github.com/user-attachments/assets/5697233e-adc3-419d-9f58-dbf3676aae40
> IS-3365: Legg til veiledning om at gosys oppgave ma svare pa

- server/unleash.ts
- src/data/unleash/unleash_types.ts
- Legger til toggle for kartleggingsspørsmål
> IS-3410: Add toggle for kartleggingssporsmal

- src/components/motebehov/MulighetForArbeid.tsx
- src/components/pengestopp/ManuellSykepengestoppItem.tsx
- src/components/personkort/PersonkortHeader/Diagnosekode.tsx
- src/components/personkort/ledere/PersonkortLedere.tsx
- src/components/utdragFraSykefravaeret/Sykmeldinger.tsx
- src/data/sykmelding/useGetSykmeldingerQuery.ts
- src/sider/nokkelinformasjon/Nokkelinformasjon.tsx
- src/sider/nokkelinformasjon/sykmeldingsgrad/SyketilfelleList.tsx
- src/sider/nokkelinformasjon/sykmeldingsgrad/Sykmeldingsgrad.tsx
- src/sider/sykepengsoknader/SykmeldingUtdragContainer.tsx
- src/sider/sykepengsoknader/container/SykepengesoknadSide.tsx
- src/sider/sykepengsoknader/soknad-arbeidstaker-ny/SendtSoknadArbeidstakerNy.tsx
- src/sider/sykmeldinger/VurderBistandsbehov.tsx
- src/sider/sykmeldinger/container/DinSykmeldingSide.tsx
- src/sider/sykmeldinger/container/SykmeldingerSide.tsx
- src/sider/sykmeldinger/sykmeldinger/DineSykmeldinger.tsx
- src/utils/sykmeldinger/sykmeldingUtils.ts
- test/components/SykmeldingUtdragTest.tsx
- test/containers/SykepengesoknadSideTest.tsx
- test/data/sykmeldingQueryHooksTest.tsx
- test/sykmeldinger/VurderBistandsbehovTest.tsx
- test/testQueryClient.ts
- test/utils/oppfolgingstilfelleUtils.ts
- test/utils/sykmeldingUtilsTest.ts
- Fjerner at sykmeldinger blir satt til tom liste som default (`sykmeldinger = []`). Er bare brukt et sted.
- Renamer en funksjon som gjør GET kall.
Veldig flisespikkeri altså. Kom bare borti når jeg skulle finne ut hvor vi henter sykmeldinger fra
> IS-3440: Preparatory refactor
