navikt/syfomodiaperson

- src/index.js
Dette kan skape forvirring, og det er bedre å bare havne på "mangler fnr"-siden.
> Remove code that redirects to user in contextholder.

- src/components/sykmeldinger/SykmeldingPeriodeInfo.js
Etter at innsendtArbeidsgivernavn ble endret, viste denne "sykmeldt fra null" da sykmeldingen ikke var sendt inn.
Jeg har også lagt til sjekk om sykmeldingen gjelder én eller flere dager.
> Fix text in sykmeldingteaser, so we only show AG name when we have it

- mock/data/oppfoelgingsdialoger.json
- src/components/GlobalNavigasjon.js
- src/components/UnfinishedTasks.js
- src/components/oppfoelgingsdialoger/OppfoelgingsPlanerOversikt.js
- src/components/oppfoelgingsdialoger/Oppfoelgingsplan.js
- src/containers/GlobalNavigasjonContainer.js
- src/containers/OppfoelgingsPlanerOversiktContainer.js
- src/styles/_antallNytt.less
- src/utils/GlobalNavigasjonUtils.js
Vis `(x aktive)` på oppfølgingsplaner-fanen i stedet for prikk.
Nå er det ikke lenger noe veilederen trenger å behandle, kun informasjon om det finnes én eller flere aktive planer.
> Remove veilederoppgaver for oppfolgingsplaner

- src/components/motebehov/BehandleMotebehovKnapp.js
- src/components/motebehov/Motebehov.js
Hvis ingen har svart, eller alle har svart nei, genereres det ingen oppgave, og da viser vi heller ikke checkboxen.
> Show behandleMotebehovKnapp only if there's an active or completed task

- mock/data/sykmeldinger.json
- package-lock.json
- src/components/personkort/Personkort.js
- src/components/personkort/PersonkortHeader.js
- src/containers/PersonKortContainer.js
- src/styles/_personKort.less
- src/utils/sykmeldinger/sykmeldingUtils.js
- test/components/personkort/PersonkortTest.js
- test/utils/sykmeldingUtilsTest.js
Kun vis merkelapp når den sykmeldte har minst én sykmelding med korona-diagnose, som er innsendt/bekreftet, og som er aktiv.
Fjern flex-grow, for å unngå at det ser rart ut når det bare er én merkelapp.
> Add tag in personkortHeader if sykmeldt has active corona diagnose

- src/mote/components/MotebookingStatus.js
- src/mote/skjema/MotebookingSkjema.js
After the change from DKIF's Webservice to REST-service, Syfomoteadmin no longer returns the kontakinfo.feilAarsak.
> Fix text for DKIF-reservertion according to response from syfomoteadmin

- mock/data/sykmeldinger.json
- src/utils/sykmeldinger/sykmeldingParser.js
- test/mockdata/sykmeldinger/mockSykmeldingExtraInfo.js
- test/utils/sykmeldingParserTest.js
Dette er et spørsmål som selvstendig næringsdrivende og frilansere får, om de var syke før perioden.
Da får de mulighet til å fylle ut én eller flere perioder.
Når vi så henter sykmeldinger fra `syfosmregister`, får vi denne listen med perioder som en json-string, og det feiler andre steder i koden, som forventer en liste med objekter.
Dette har ikke feilet oftere fordi det kun rammer de som faktisk har fylt ut minst én periode på det spørsmålet, i alle andre tilfeller har vi mappet til en tom liste, slik at alt har blitt vist som normalt for veileder.
> Parse sporsmal of type periode to object in stead of just string

- src/components/sykmelding/avvisteSykmeldinger/AvvistSykmeldingStatuspanel.js
- src/utils/sykmeldinger/sykmeldingParser.js
- test/mockdata/sykmeldinger/mockOldSykmeldinger.js
Bekreftetdatoen i statuspanelet på bekreftede sykmeldinger manglet, fordi koden ville ha `sendtDato`, men den ble bare satt hvis sykmeldingen var sendt (til AG). I forbindelse med avviste sykmeldinger, ble det lagt til et felt som heter `bekreftetDato`. Det siste er nå flettet inn i sendtDato-feltet, slik at man bruker samme datofelt til alt som har med innsending/bekreftelse å gjøre.
> Use same field in SM for sendtdato and bekreftetdato

- mock/data/oppfoelgingsdialoger.json
- package-lock.json
- src/containers/OppfoelgingsPlanerOversiktContainer.js
- src/utils/GlobalNavigasjonUtils.js
- src/utils/oppfolgingsplanerUtils.js
- test/mockdata/mockOppfolgingsplaner.js
- test/utils/oppfolgingsplanerUtilsTest.js
En plan er aktiv hvis den er delt med NAV, vi er innenfor gyldighetstidspunktet, og det ikke har kommet inn en ny plan for samme virksomhet.
Før forsvant den fra aktive med én gang AG eller AT begynte å gjøre endringer, selv om den nye ikke var sendt inn enda.
Det er alltid den planen som sist er sendt inn til NAV som er gjeldende for hver bedrift. Alle andre er "tidligere", uavhengig av om de er innenfor gyldighetsperioden.
"Prikker" for oppfølgingsplaner er også oppdatert til å bruke den nye måten å beregne aktive på.
> Change logic for active planer

- src/components/oppfoelgingsdialoger/OppfoelgingsPlanerOversikt.js
deltMedNavTidspunkt -> deltMedNAVTidspunkt, also simplify sorting.
> Use correct field name when sorting planer by deltMedNAVTidspunkt

- mock/data/sykmeldinger.json
- package-lock.json
- package.json
- src/components/sykmelding/SykmeldingSide.js
- src/components/sykmelding/koronasykmeldinger/KoronaSykmelding-Avbrutt.js
- src/components/sykmelding/koronasykmeldinger/KoronaSykmelding-Bekreftet.js
- src/components/sykmelding/koronasykmeldinger/KoronaSykmelding-Ny.js
- src/components/sykmeldingstatuspanel/SykmeldingStatuspanel.js
- src/containers/DinSykmeldingContainer.js
- src/utils/sykmeldinger/sykmeldingParser.js
- test/utils/sykmeldingParserTest.js
Legg til en egen if på sykmeldingvisning, slik at egenmeldte sykmeldinger håndteres separat fra vanlige.
Gjør også om på mappingen fra nytt til gammelt sykmeldingformat, slik at spørsmål som ikke er fylt ut settes til null i stedet for undefined; da unngår vi at en null-sjekk feiler, og felter i statuspanelet vises kun da de skal.
Endre sendtdato-feltet til å være dato for siste statusoppdatering, slik at vi også får dato for når en sykmelding ble avbrutt.
> Make egenmeldte sykmeldinger equal to Ditt Sykefravær

- mock/data/ledere.json
- mock/data/sykmeldinger.json
- src/components/personkort/PersonkortLedere.js
- src/utils/ledereUtils.js
- test/components/personkort/PersonkortVisningTest.js
- test/mockdata/mockLedere.js
- test/utils/ledereUtilsTest.js
Finn alle aktive sykmeldinger, deretter finn de virksomhetene som ikke har en tilknyttet leder, vis disse i PersonkortLeder med "ingen leder registrert"-infoboks.
Fjern duplikater, slik at selv om en virksomhet har mer enn én aktiv sykmelding, kommer virksomheten bare én gang i personkortet.
> Show virksomheter without leder from sykmeldinger in personkort

- package-lock.json
- package.json
- src/components/sykmelding/koronasykmeldinger/KoronaSykmelding-Ny.js
Legg til Bjørn, inkludert knapp for "Gå til utfyllingen". Den knappen skal egentlig bare være synlig for mobilbrukere på Ditt Sykefravær, men vi viser den hele tiden.
Også bump digisyfo-npm. Dette fjerner "Diagnosen vises ikke til arbeidsgiveren", som ikke trengs, siden den egenmeldte sykmeldingen kun gjelder for frilansere og selvstendig næringsdrivende.
> Let Bjorn tell extra info, instead of floating text

- src/components/motebehov/UtdragFraSykefravaeret.js
- src/components/sykmeldinger/SykmeldingTeaser.js
- src/styles/_inngangspanel.less
- src/styles/_utdragFraSykefravaeret.less
- src/styles/styles.less
Bruk merkelapp både på sykmeldingsiden, og på møtebehovsiden.
Bruk lysere gråfarge på bakgrunnen i merkelappen, for å være WCAG AAA-complient.
> Add label to papirsykmeldinger

- mock/data/ledere.json
- mock/mockModiasyforest.js
- src/reducers/ledere.js
- src/sagas/ledereSagas.js
- src/utils/ledereUtils.js
- test/reducers/ledereReducerTest.js
- test/sagas/ledereSagasTest.js
Nå får vi også inn tidligere ledere, men vi trenger ikke endre eksisterende kode for å ta høyde for endringen.
> Get all ledere, store current and former separately in reducer

- src/containers/HistorikkContainer.js
Denne legger fom-datoen på alle nåværende og tidligere ledere inn som en historikkhendelse i "Logg"-fanen.
Det skjer ingen filtrering, så hvis samme leder er meldt inn flere ganger, vil det også bli flere historikkhendelser.
> Show start date of both current and former ledere in Historikk

- src/mote/TextField.js
TextArea no longer takes in prop Feil of type object, but requires type ReactNode. This change was introduced after bumping nav-frontend-skjema to v.3.0.16
> Fix bug with prop feil for <TextArea>

- src/components/pengestopp/Pengestopp.tsx
- src/components/pengestopp/PengestoppDropdown.tsx
- src/components/pengestopp/PengestoppModal.tsx
- src/containers/SykmeldingerContainer.js
- src/reducers/flaggperson.ts
- src/types/FlaggPerson.ts
- src/utils/pengestoppUtils.ts
Bruk blå knapp, med spørsmålstegn
Vis ekstra informasjon under knappen
Ikke map dato i flaggPersonReducer, nå er det lettere å printe datoen
Oppdater tekster, bruk "stans" i stedet for "stopp"
Fjern avbryt-knapp fra modal etter innsending
> Make pengestopp button less angry, update texts

- src/components/motebehov/MotebehovKvittering.js
- src/utils/ledereUtils.js
- test/utils/ledereUtilsTest.js
Finn riktig leder for møtebehovsvar med aktørID ikke virksomhetsnummer
Vis bare nyeste leder hvis kun SM har svart, uavhengig av innsendtDato
> Show correct leder name in motebehovKvittering

- src/components/vedtak/VedtakEkspanderbartPanel.tsx
If Vedtak has a `orgnr` that is `null` the name of the `Virksomhet` is request from Syfomoteadmin, resulting in an error.  A check to see if `Orgnr` before calling `hentVirksomhet` for Vedtak is added to solve this issue.
> Do not get Virksomhetsnavn for orgnr=null

- src/components/pengestopp/Pengestopp.tsx
- src/utils/pengestoppUtils.ts
Thee name of the Virksomhet(orgnummer) should be shown from Sykmelding, not the name of JuridiskOrgnummer.
> Fix bug with name of Arbeidsgiver shown in Pengestopp

- mock/data/prediksjon.json
- src/components/Prediksjon/PrediksjonResultat.tsx
- src/data/prediksjon/prediksjon.ts
This field is not going to be used in initial data model from Isprediksjon and is therefore removed.
> Remove TreffsikkerhetProsent from Prediksjon

- src/components/motebehov/container/MotebehovContainer.tsx
- src/utils/motebehovUtils.ts
- test/utils/motebehovUtilsTest.js
Slå sammen alle tilfeller som henger sammen innenfor 16 dager, uavhengig av virksomhet
Finn startdatoen for det nyeste, aktive tilfellet, null hvis ingen tilfeller er aktive nå
Filtrer bort alle møtebehovsvar som ble opprettet etter den datoen, tom liste hvis startdato er null
> Show only motebehovsvar connected to the latest current syketilfelle

- src/components/speiling/sykmeldinger/sykmelding/sykmeldingOpplysninger/flereopplysninger/FlereOpplysninger.tsx
- src/components/speiling/sykmeldinger/sykmelding/sykmeldingOpplysninger/flereopplysninger/MulighetForArbeid.tsx
Do not show information of StartlegemeldtFravaer from Sykmelding to reflect changes in information shown to person in DittNav-DittSykefravaer
> Remove information for Sykmelding.startLegemeldtFravaer

- src/components/Prediksjon/Prediksjontittel.tsx
Et "langt" sykefravær er definert som 28 uker i backend.
> Change title to week 28 in Prediksjontittel.tsx

- mock/data/motebehov.json
- src/components/motebehov/MotebehovKvittering.tsx
- src/styles/_motebehovKvittering.less
OpprettetDato of Motebehov was accidentally removed and is therefore added again so the date Motebehov was submitted can be viewed be the user. In addition, som refactoring is done for simplicity and the styling of MotebehovKvitteringBoksInnhold is fixed to be according to specification.
> Fix removed Motebehov.opprettetDato for Arbeidsgiver

- src/utils/ledereUtils.ts
Legg på new Date rundt datoene, slik at vi sammenligner faktiske datoer, ikke string.
"20.05" > "30.01" === false // Her sammenlignes string "2" med string "3"
new Date("20.05") > New Date("30.01") === true
> Fix isNewerLeader util method

- src/components/motebehov/MeldingTilArbeidsgiver.tsx
- src/utils/sykmeldinger/sykmeldingUtils.ts
- test/utils/sykmeldingUtilsTest.js
Denne kan bli `undefined`, og da blir `!== null` true, selv om vi ikke egentlig har mer info.
Fjern unødvendig sjekk på innspillTilArbeidsgiver i MeldingTilArbeidsgiver-komponenten, siden den skal være true hvis `skalVise` er true.
> Use double exclamation to check if innspillTilArbeidsgiver is present

- src/components/Layout.tsx
- src/components/dialogmote/Forhandsvisning.tsx
- src/components/dialogmote/innkalling/DialogmoteInnkallingSkjema.tsx
- src/components/dialogmote/innkalling/DialogmoteInnkallingTekster.tsx
- src/components/dialogmote/innkalling/InnkallingArbeidsgiverForhandsvisning.tsx
- src/components/dialogmote/innkalling/InnkallingArbeidstakerForhandsvisning.tsx
- src/data/behandlendeenhet/behandlendeEnhet.ts
- src/data/behandlendeenhet/behandlendeEnhet_hooks.ts
- src/data/dialogmote/dialogmoteTexts.ts
- src/data/dialogmote/dialogmoteTypes.ts
- src/hooks/useForhandsvisInnkalling.ts
- test/dialogmote/DialogmoteInnkallingSkjemaTest.tsx
- Forhandsvisning-komponent som håndterer visning av liste med DocumentComponentDto i modal
- useForhandsvisInnkalling-hook som gir to funksjoner for å generere liste med med DocumentComponentDto for innkalling til arbeidsgiver og arbeidstaker basert skjema-verdier og standardtekster. Brukes ifm forhåndsvisning og sending til backend.
- standardtekster samlet i dialogmoteTexts.ts
Nå styres rekkefølgen på tekstene (og type) ut i fra hvordan liste med DocumentComponentDtos bygges opp i funksjonene som defineres i hooken, mens selve tekstene ligger i konstanter i dialogmoteTexts.ts. Mulig dette bør organiseres på en annen måte så absolutt åpen for forslag.
> Forhandsvis innkalling first edition

- src/components/dialogmote/DialogmoteSideContainer.tsx
- src/components/dialogmote/avlys/AvlysDialogmoteContainer.tsx
- src/components/dialogmote/referat/DialogmoteReferatContainer.tsx
- src/components/mote/components/innkalling/DialogmoteMoteStatusPanel.tsx
- src/routers/AppRouter.tsx
- Lagt til referat-container med egen url og link fra knapp i dialogmøte-status-panel.
- Refaktorert til DialogmoteSideContainer som henter dialogmote med id fra url. Brukes av avlys- og referat-container.
> Referat container with route and link

- src/colors.ts
- src/components/TextDropdown.tsx
- src/components/dialogmote/referat/ReferatInfoColumn.tsx
- src/components/pengestopp/PengestoppHistorikk.tsx
- src/components/personkort/ledere/PersonKortVirksomhetHeader.tsx
- src/components/vedtak/VedtakEkspanderbartPanel.tsx
- src/components/vedtak/VedtakInfoBox.tsx
- src/components/vedtak/VedtakUnselected.tsx
- webpack.prod.ts
Bruk av `import navFarger from "nav-frontend-core";` fungerte ikke i preprod/prod (verdiene blir undefined så farger mangler der de nå brukes). Endrer foreløpig tilbake til egendefinerte konstanter for nav-farger og lager egen sak på å få fikset webpack slik at vi kan bruke navFarger i preprod/prod.
> Fix navfarger

- server.js
Syfo-tilgangskontroll has been moved from namespace default to team namespace teamsykefravr
> Update namespace of Syfo-tilgangskontroll

- mock/data/dialogmoterMock.ts
- mock/data/ledereMock.ts
- src/components/dialogmote/innkalling/DialogmoteInnkallingContainer.tsx
- src/components/dialogmote/innkalling/DialogmoteInnkallingVelgArbeidsgiver.tsx
- src/components/dialogmote/referat/Referat.tsx
- src/components/historikk/container/HistorikkContainer.js
- src/components/mote/components/Motelandingsside.tsx
- src/components/mote/components/innkalling/DialogmoteMoteStatusPanel.tsx
- src/components/mote/container/MotebookingSkjemaContainer.js
- src/data/dialogmote/types/dialogmoteTypes.ts
- src/data/leder/ledere.ts
- src/data/leder/ledereSagas.ts
- src/data/leder/ledere_actions.ts
- src/data/oppfolgingstilfelle/oppfolgingstilfelleperioderSagas.ts
- src/hooks/useLedere.ts
- src/utils/ledereUtils.ts
- test/containers/MotebookingContainerTest.js
- test/containers/MotelandingssideContainerTest.js
- test/dialogmote/DialogmoteInnkallingSkjemaTest.tsx
- test/dialogmote/MotehistorikkTest.tsx
- test/dialogmote/ReferatTest.tsx
- test/mote/containers/MotebookingSkjemaContainerTest.js
- test/reducers/ledereReducerTest.js
- test/utils/ledereUtilsTest.js
- henter ledernavn fra nyeste nærmeste leder på virksomheten og viser dette i lest-status og nærmeste leder-felt på referatet.
- forbedret typer på ledere-reducer, actions og saga og renamet data til currentLedere.
> Håndterer nærmeste leder-navn på dialogmøter

- server/proxy.js
Når vi gjør post-kall blir fnr undefined, og da fungerer ikke kallet, og ingen får stoppet penger.
Bruk "parseReqBody" for å sjekke om det er post-kall eller ikke.
> Only add fnr-header for ispengestopp if not post request

- src/utils/sykmeldinger/sykmeldingParser.ts
Fikser feil med evig spinner for en sykmeldt med sykmelding som manglet hoveddiagnose. 
Forbedrer feilhåndtering i egen PR.
> Lagt til sjekk på at vi har hovedDiagnose før mapping av diagnose

- src/data/pengestopp/flaggPersonSagas.ts
Dette er en midlertidig løsning for å kunne bytte til ny header "nav-personident" i ispengestopp.
Nå sender vi begge headere samtidig, så vi trygt kan bytte i ispengestopp uten at noe feiler. Når vi har prodsatt ny versjon av pengestopp, kan vi fjerne "fnr" header fra proxy.js.
> Use nav-personident and fnr header when getting pengestopp status

- server/auth/utils.js
Do not reuse token if it expires in less than 10 seconds. This improvement is made to avoid expired tokens in consuming services.
> Improve expiration of OBO-token

- src/components/mote/skjema/FlereTidspunktSkjema.js
- src/utils/moteplanleggerUtils.ts
Da slipper vi forhåpentligvis feilen der veileder ikke får til å tidligere tidspunkt fordi de ikke eksisterer i databasen.
Nå vises en feilmelding hvis man forsøker å sende inn et nytt tidspunkt som er likt et eksisterende tidspunkt, både de "aktive" og de som ligger under tidligere tidspunkt.
Man får feilmelding så lenge minst ett av de nye foreslåtte tidspunktene matcher et eksisterende.
> Show error if user attempts to add an existing tidspunkt

- src/components/dialogmote/DialogmoteSideContainer.tsx
- src/components/dialogmote/innkalling/DialogmoteInnkallingContainer.tsx
- src/components/mote/components/MotebookingStatus.js
- src/components/mote/components/innkalling/InnkallingDialogmotePanel.tsx
- src/components/mote/components/innkalling/NyttDialogMote.tsx
- src/components/mote/container/MotestatusContainer.js
- src/components/mote/skjema/MotebookingSkjema.js
- src/data/navbruker/navbruker.ts
- src/data/navbruker/navbruker_hooks.ts
- src/data/navbruker/types/Brukerinfo.ts
- test/containers/SykepengesoknadContainerTest.js
skalHaVarsel ble satt til initielt til `false` i redux som gjorde at advarsel-boks ble vist et lite sekund før den forsvant (når data er hentet) for brukere som kan varsles. Fikset ved å sette initiell verdi til undefined og sjekke eksplisitt på false i koden.
> Setter skalHaVarsel initielt undefined

- .github/workflows/main.yaml
- cypress.json
- cypress/integration/dialogmoter/avlys-dialogmoter.spec.ts
- cypress/integration/dialogmoter/ferdigstill-dialogmote.spec.ts
- cypress/integration/dialogmoter/motelandingsside.spec.ts
- cypress/support/commands.ts
- cypress/support/index.ts
- package-lock.json
Godta Cross Origin-kall for at man skal kunne redirecte til MockOAuth2.
Legg til Command i Cypress som logger inn i MockOAuth2, bruk den i "before each" i alle testene.
Legg til Docker Compose i GitHub Actions workflow-filen.
Flytt innlogging i Docker lenger opp i workflow, for at man skal få tak i oauth2-pakken i docker compose.
Skriv .env.template-filen til `GITHUB_ENV`, så de er tilgjengelige når Cypress kjører.
> Make Cypress work with Docker Compose

- server/routes/unleashRoutes.js
- src/data/unleash/unleashSagas.ts
- src/data/unleash/unleash_actions.ts
- src/routers/AppRouter.tsx
Dersom kall til syfoveileder for å hente veielederIdent feilet hentet vi ikke feature toggles fra unleash. 
Vi bør hente disse uansett slik at veiledere som tilhører kontor hvor MVP er enabled får denne uavhengig av om vi klarer hente veileder fra syfoveileder.
> Henter unleash feature toggles selv om veilederIdent er undefined

- src/components/dialogmote/innkalling/DialogmoteInnkallingSkjema.tsx
- src/components/dialogmote/innkalling/DialogmoteInnkallingTekster.tsx
- src/data/dialogmote/dialogmoteTexts.ts
- src/hooks/dialogmote/useForhandsvisInnkalling.ts
Lag egne metoder og tekster for behandler, selv om det er litt overlapp med arbeidsgiver.
Endre outro-tekstene for innbygger og arbeidsgiver hvis behandler skal være med.
Ikke ta med behandler i dokumentet som genereres for sending til bakcend, det gjøres i neste oppgave.
> Add optional text input for behandler, generate preview document

- src/components/dialogmote/avlys/AvlysDialogmoteSkjema.tsx
- src/components/dialogmote/endre/EndreDialogmoteSkjema.tsx
- src/data/dialogmote/types/dialogmoteTypes.ts
API krever at behandler sendes med avlysning/endring dersom innkallingen hadde med behandler. Legger til foreløpig "tom" behandler for at innsending av endring/avlysning av møter med behandler skal fungere. Tekst og dokument til behandler kommer i egne oppgaver.
> Send med "tom" behandler i endre/avlys hvis møtet har behandler

- src/components/personkort/SnowButton.tsx
Nå skiller vi ikke på om man starter eller stopper snøen/musikken, det må man i så fall legge på senere, men da burde man kanskje gjøre noen endringer på hvordan Amplitude fungerer i appen.
> Track snowButton with Amplitude

- test/components/personkort/PersonkortVisningTest.js
- test/dialogmote/AvlysDialogmoteSkjemaTest.tsx
- test/dialogmote/ReferatTest.tsx
- test/setup.js
Kjøring av tester spyttet ut nettverks-feil i loggene ved api-kall fra react-query så skrur av dette som beskrevet her https://react-query.tanstack.com/guides/testing#turn-off-network-error-logging
> Turn off network error logging for react-query in tests. Add some missing stubs.

- cypress/integration/dialogmoter/motelandingsside.spec.ts
- src/components/dialogmote/innkalling/DialogmoteInnkallingContainer.tsx
- src/components/mote/components/Motelandingsside.tsx
- src/data/dialogmote/dialogmoteQueryHooks.ts
- src/data/unleash/unleash.ts
- src/data/unleash/unleash_hooks.ts
Dersom man skulle finne på å gå direkte til url for innkalling-skjema (ikke via modaler fra møte-landingssiden)
> Redirect to møteoversikt i innkalling-skjema dersom man har aktivt møte eller ikke tilgang til dm2-pilot

- server/routes/unleashRoutes.js
valgtEnhet ser ut til å være default tom streng.
dvs `isEnabled` returnerte true dersom man ikke får hentet enhet i Modia - (`parameters.valgtEnhet.indexOf("") === 0` og `valgtEnhetMatches` blir true). Endrer til å returnere false dersom valgtEnhet er falsy (f.eks. tom streng). Endrer også tilsvarende i sjekk på user.
> unleashRoutes isEnabled should return false for falsy values

- src/components/dialogmote/DeltakereSvarInfo.tsx
- src/components/mote/components/innkalling/DialogmoteMoteStatusPanel.tsx
- test/dialogmote/DeltakereSvarInfoTest.tsx
- test/dialogmote/testData.ts
Se https://www.figma.com/file/L6DPvt6dU1XzypeiQoQ54C/MODIA-Person?node-id=5433%3A32695
- Implementert nytt design fra skisser (foreløpig uten behandler og kun har åpnet/ikke åpnet), med ekspanderbart svar. 
- Håndterer at varsel kan være både innkalling og endring i tittel og i svar-panel.
- Tekst om ny løsning skal være vanlig tekst ikke advarsel
> Redesign visning av svar fra møtedeltakere (Arbeidstaker og arbeidsgiver)

- src/hooks/dialogmote/useForhandsvisReferat.ts
Dersom man krysset av for noen standardtekster og deretter fjernet avkrysningene ble overskrift værende i brevet.
> Referat bugfix: Legg til overskrift bare når man har krysset av for noen standardtekster

- mock/data/dialogmoterMock.ts
- src/components/dialogmote/avlys/AvlysDialogmoteSkjema.tsx
- src/components/dialogmote/endre/EndreDialogmoteSkjema.tsx
- src/components/dialogmote/innkalling/DialogmoteInnkallingSkjema.tsx
- src/components/dialogmote/referat/Referat.tsx
- src/components/dialogmote/referat/ReferatButtons.tsx
- src/components/mote/components/innkalling/DialogmoteMoteStatusPanel.tsx
- src/data/dialogmote/types/dialogmoteReferatTypes.ts
- src/data/dialogmote/useMellomlagreReferat.ts
- src/hooks/dialogmote/useInitialValuesReferat.ts
- src/hooks/useFeilUtbedret.ts
- test/dialogmote/DialogmoteMoteStatusPanelTest.tsx
- test/dialogmote/ReferatMellomlagreTest.tsx
- test/dialogmote/testData.ts
- test/stubs/stubIsdialogmote.ts
- Endret tekst på knapp "Skriv referat" på landdingsside når det finnes mellomlagret referat. Og endret header hvis møtedato passert.
- Knapp for "manuell" lagring av referatet i skjema
- Fyller skjema med verdier fra mellomlagret referat
- Flyttet forhåndsvisning-knapp over feilmeldinger/alerts i skjema.
> Knapp for å mellomlagre referat

- src/utils/sykmeldinger/sykmeldingUtils.ts
Dette skal fikse en feil hvor noen sykmeldinger havnet mellom to stoler: De har status "NY", men er akkurat 3 måneder gamle (på måneden).
> Show sykmeldinger as old if 3 or more months old

- src/utils/stringUtils.ts
- src/utils/valideringUtils.ts
- test/utils/valideringUtilsTest.ts
For å unngå at veileder legger til ekstra informasjon i feltet som gjør at pdf-generering feiler.
Trim space før og etter for å unngå at det blir med noe ekstra f.eks. ved innliming.
> Disallow whitespace in video url in dm2 forms

- .github/workflows/cypress.yaml
- .github/workflows/main.yaml
Flytter kjøring av cypress-tester til egen workflow så vi slipper å vente på disse for å få bygget docker image.
Kjører på pull request og push til master.
> Move cypress to separate workflow

- src/components/dialogmote/innkalling/BehandlerRadioGruppe.tsx
This should be deployed after we've added other types of behandlere in
isdialogmelding
> Use more correct infotext for behandlere radio group

- src/routers/AppRouter.tsx
When no matching route is found, redirect route to route /sykefravaer. This will prevent the user from coming to a blank page, if a wrong url is given as input.
> Add wildcard app route

- src/components/dialogmote/DialogmoteTidOgSted.tsx
- src/components/dialogmote/innkalling/DialogmoteInnkallingSkjema.tsx
AB tested functionality: show text for veiledere with idents ending in 5 or
higher.
Only show futuristic warning if innbygger can receive digital communication
> Show infotext if selected date is too far into the future

- src/utils/soknad-felles/hentSoknadStatustekst.js
- test/utils/soknad-felles/hentSoknadStatustekstTest.ts
Erstatter `!== null` med en sjekk av datoens boolske verdi, vha dobbel negasjon.
Dette var feil fordi vi i parsingen av innkommet json gjør om datoer som mangler til `undefined`, noe som blir true når man sjekker ikke lik null.
Ved å konvertere direkte til boolsk verdi, skal både null og undefined gi false.
> Fix broken sendtTilArbeidsgiver check in soknad

- src/components/mote/components/innkalling/InnkallingDialogmotePanel.tsx
Denne henger igjen fra før DM2-innkalling var tilgjengelig for alle, og har ikke vært i bruk på lenge.
> Remove unused text about DM2 in Arena

- src/components/dialogmote/innkalling/BehandlerSearchResult.tsx
Nå ligger teksten til venstre selv når den går over flere linjer.
Co-authored-by: Eirik Dahlen <eirik.dahlen@nav.no>
> Align behandler search result to the left

- mock/sykepengesoknad/soknaderMock.ts
- src/components/speiling/sykepengsoknader/soknad-felles-oppsummering/OppsummeringTall.tsx
Dataen kan i noen tilfeller henvise til timer i spørsmålet, men være av svartype = Tall. Tidligere løsningen ville da defaulte til prosent, mens nå setter vi heller ingen verdi enn å skrive feil. Vi har sagt ifra til team Flex om at det ville gitt mer mening om dataen vi får fra de hadde Svartype.TIMER når spørsmålet spør om timer, men det er utenfor vår kontroll å rette opp i.
Tidligere:
Nå (det er kun stringbasert mockdata, derfor er det forskjell på `37.50` og `37,5`):
> Add correct suffix to svartyper

- src/components/mote/NoNarmestLederAlert.tsx
- src/components/mote/components/innkalling/DialogmoteMoteStatusPanel.tsx
Remove superfluous text, and move 'no arbeidsgiver'-alert to the top. This will allow the behandle oppgave box to be closer to the motesvars it refers to.
> Clean up texts on motelandingsside

- src/components/dialogmote/innkalling/virksomhet/DialogmoteInnkallingVelgVirksomhet.tsx
- src/components/dialogmote/innkalling/virksomhet/VirksomhetChooser.tsx
- src/components/dialogmote/innkalling/virksomhet/VirksomhetInput.tsx
- test/dialogmote/DialogmoteInnkallingSkjema/DialogmoteInnkallingSkjemaTest.tsx
Due to many jira-cases where the veileder haven't checked if the AT is unemployed we add information on this in the alert text.
Also made sure the two alerts don't show at the same time, and added some space.
> Update alert text for no virksomhet

- src/components/aktivitetskrav/AktivitetskravSide.tsx
- src/components/aktivitetskrav/vurdering/OppfyltAktivitetskravSkjema.tsx
- src/components/aktivitetskrav/vurdering/VurderAktivitetskrav.tsx
- src/components/aktivitetskrav/vurdering/VurderAktivitetskravBegrunnelse.tsx
- src/components/aktivitetskrav/vurdering/VurderAktivitetskravButtons.tsx
- src/components/aktivitetskrav/vurdering/VurderAktivitetskravModal.tsx
- src/components/aktivitetskrav/vurdering/VurderAktivitetskravSkjemaButtons.tsx
- src/data/aktivitetskrav/useVurderAktivitetskrav.ts
- test/aktivitetskrav/VurderAktivitetskravTest.tsx
Sender vurdering til API ved Lagre. Foreløpig kun begrunnelse-felt uten validering. Radioknapper iht [skisse](https://www.figma.com/file/sPmsOTiLhgACeNt4TElE4P/iSYFO-Modia?node-id=999%3A104357&t=2uTOyu7FPNA7xKMV-0) kommer når backend støtter det.
> Modal with title, begrunnelse and buttons. Uses mutation on submit.

- src/components/aktivitetskrav/vurdering/UnntakAktivitetskravSkjema.tsx
- src/components/aktivitetskrav/vurdering/VurderAktivitetskravArsakRadioGruppe.tsx
- src/components/aktivitetskrav/vurdering/VurderAktivitetskravModal.tsx
- src/components/aktivitetskrav/vurdering/VurderAktivitetskravSkjema.tsx
- src/data/aktivitetskrav/aktivitetskravTexts.ts
- src/hooks/aktivitetskrav/useAktivitetskravVurderingSkjema.ts
- test/aktivitetskrav/VurderAktivitetskravTest.tsx
Refaktorert en del felles kode til `<VurderAktivitetskravSkjema>` og `useAktivitetskravVurderingSkjema` siden det er en del likt i disse skjemaene (UNNTAK/OPPFYLT/AVVENT)
> Vurder aktivitetskrav unntak

- mock/isaktivitetskrav/aktivitetskravMock.ts
- src/components/aktivitetskrav/vurdering/AktivitetskravVurderingAlert.tsx
- src/components/aktivitetskrav/vurdering/AvventArsakerCheckboxGruppe.tsx
- src/components/aktivitetskrav/vurdering/VurderAktivitetskravArsakRadioGruppe.tsx
- src/data/aktivitetskrav/aktivitetskravTexts.ts
- test/aktivitetskrav/AktivitetskravSideTest.tsx
- test/aktivitetskrav/testDataUtils.ts
Samt gjort litt forenkling/refaktorering av årsak-tekstene i src/data/aktivitetskrav/aktivitetskravTexts.ts
> Viser avkryssede årsaker til Avvent i alert

- src/components/aktivitetskrav/AktivitetskravSide.tsx
- test/aktivitetskrav/AktivitetskravHistorikkTest.tsx
- test/aktivitetskrav/AktivitetskravSideTest.tsx
- test/aktivitetskrav/VurderAktivitetskravTest.tsx
- test/testDataUtils.ts
- test/utils/oppfolgingstilfelleUtilsTest.ts
Moved testdataUtils and removed redundant method.
> Tillater vurdering av aktivitetskrav for siste oppfolgingstilfelle (uavhengig av om det er aktivt) - tilsvarende logikk for dm-kandidat og innkalling

- src/components/IconHeader.tsx
- src/components/Layout.tsx
- src/components/aktivitetskrav/AktivitetskravSide.tsx
- src/components/aktivitetskrav/vurdering/VurderAktivitetskrav.tsx
- src/components/mote/components/DialogmotePanel.tsx
- src/components/mote/components/Motelandingsside.tsx
- src/components/nokkelinformasjon/Nokkelinformasjon.tsx
- src/components/utdragFraSykefravaeret/UtdragFraSykefravaeret.tsx
For å slippe avhengighet til DialogmotePanel fra UtdragFraSykefravaeret og kunne bruke AktivitetskravPanel til å vise UtdragFraSykefravaeret på aktivitetskrav-siden.
> Refactor UtdragFraSykefravaeret and DialogmotePanel

- src/components/aktivitetskrav/historikk/AktivitetskravHistorikk.tsx
- test/aktivitetskrav/AktivitetskravHistorikkTest.tsx
- test/testDataUtils.ts
AVVENT is the only status that can have more than one årsak, but it won't show up in history. So we only care about the first årsak in the array, or no årsak if status is IKKE_OPPFYLT.
> Show årsak for aktivitetskravvurderinger in historikk

- src/components/aktivitetskrav/AktivitetskravContainer.tsx
- src/routers/AppRouter.tsx
Toggle sjekkes også for å vise menypunktet og hente aktivitetskrav-data så dette er bare en ekstra sjekk for å hindre at man kan få opp siden ved å gå til `/aktivitetskrav`-routen.
> Improve and move aktivitetskrav toggle check to container

- src/components/aktivitetskrav/AktivitetskravContainer.tsx
Ser ingen grunn til å vente med å vise Vurder aktivitetskrav til man har hentet oppfølgingsplaner - disse vil hentes og evt vises i Utdrag fra sykefraværet under vurderingen.
> Remove wait for oppfolgingsplaner

- src/components/aktivitetskrav/AktivitetskravSide.tsx
- src/components/aktivitetskrav/NoOppfolgingstilfelleAktivitetskravAlert.tsx
- src/components/aktivitetskrav/vurdering/VurderAktivitetskrav.tsx
- src/components/aktivitetskrav/vurdering/VurderAktivitetskravModal.tsx
- src/components/aktivitetskrav/vurdering/VurderAktivitetskravSkjema.tsx
- src/data/aktivitetskrav/useVurderAktivitetskrav.ts
- src/utils/aktivitetskravUtils.ts
- test/aktivitetskrav/AktivitetskravSideTest.tsx
- test/aktivitetskrav/VurderAktivitetskravTest.tsx
- test/utils/aktivitetskravUtils.test.ts
Flyttet noe logikk til `aktivitetskravUtils`.
Viser advarsel når vi ikke finner oppfølgingstilfelle.
> Skal kunne vurdere aktivitetskrav uten at det finnes oppfolgingstilfelle med aktivitetskrav

- src/components/dialogmote/referat/Referat.tsx
Also don't mellomlagre if ferdigstillDialogmote or endreReferat is already loading in React Query.
> Don't auto save after referat is sent

- src/components/mote/components/innkalling/DialogmoteMoteStatusPanel.tsx
- src/utils/dialogmoteUtils.ts
- test/utils/dialogmoteUtilsTest.ts
Always show if ubehandlet oppgave, because it has to be connected to the current statusEndring. If behandlet, show confirmation message until veileder sends endring or finishes meeting.
> Show check box for manual behandling of dialogmotesvaroppgave

- src/components/dialogmote/referat/Referat.tsx
No need to save twice, and this might possibly cause some problems when the user exits the form right after saving.
> Cancel auto save debounce on manual save

- src/components/sykmeldingsgrad/Sykmeldingsgrad.tsx
- src/utils/sykmeldinger/sykmeldingUtils.ts
- test/utils/sykmeldingUtilsTest.ts
This also affects UtdragFraSykefravaret, since that also uses the sykmeldingerInnenforOppfolgingstilfelle method.
Now it's up to the user of the util method to decide the limitations on which sykmeldinger should count, since it only checks dates as the method name implies.
Also add test, it didn't actually verify the filtering by virksomhet.
> Use all sykmeldinger in graf regardless of virksomhet

- src/components/aktivitetskrav/AktivitetskravSide.tsx
- test/aktivitetskrav/AktivitetskravSideTest.tsx
Nå er det uten den blå infoboksen:
Hvordan det så ut før (fra designskisser):
> Remove infobox for vurdering per arbeidsforhold/sykefravær

- src/components/aktivitetskrav/vurdering/AvventArsakerCheckboxGruppe.tsx
- src/components/aktivitetskrav/vurdering/VurderAktivitetskravArsakRadioGruppe.tsx
- src/components/aktivitetskrav/vurdering/VurderAktivitetskravBeskrivelse.tsx
Sånn at feltene og valideringsmeldingene får lik styling som det nye dato-input-feltet som kommer på Avventer. Eks:
Nytt:
Gammelt:
> Bruke nytt designsystem for skjema-input i aktivitetskravet

- src/data/behandler/BehandlerDTO.ts
Etter fika i går så fant vi ut at dette ikke var på plass i frontend. Visningen blir derimot rett dersom vi sender inn SYKMELDER fra backend, siden det i realiteten er en string når det parses. Men det er likevel fint å ha riktige verdier på enumen i frontend, selv om den stort sett (til nå) kun har blitt brukt i mock- og testdata.
> Add SYKMELDER to BehandlerDTO

- src/components/SkjemaInnsendingFeil.tsx
- src/components/behandlerdialog/meldingtilbehandler/MeldingTilBehandlerSkjema.tsx
Formet blir ikke clearet for radiogruppa - men vi tenker at det er sufficient å cleare meldingsfeltet i første omgang, ettersom at man da får en valideringsfeil hvis man prøver å trykke på "send melding" to ganger eller lignende.
✅ Bekreftet at riktig behandlerRef er satt i dev, selv om formet blir clearet.
Suksess:
Feil:
> Add feedback on successfull or erroneous sending of MeldingTilBehandler

- src/components/personkort/PersonkortChangeEnhet.tsx
- test/components/personkort/PersonkortEnhetTest.tsx
> Use different text when changing to geografisk enhet in personkort

- mock/isdialogmelding/behandlereDialogmeldingMock.ts
- src/components/behandlerdialog/meldingtilbehandler/MeldingTilBehandlerSkjema.tsx
- src/data/behandlerdialog/behandlerdialogTypes.ts
- test/behandlerdialog/MeldingTilBehandlerTest.tsx
We need the behandler's details when journalføring meldinger we send to him/her
- full name 
- ident
The name will be displayed in the document list in Gosys, and help identify the pdf version of the melding til behandler.
> Add behandler details to melding to behandler

- mock/ispersonoppgave/mockIspersonoppgave.ts
- src/components/behandlerdialog/meldinger/BehandleBehandlerdialogSvarOppgaveKnapp.tsx
- src/components/behandlerdialog/meldinger/Meldinger.tsx
- src/components/behandlerdialog/meldinger/SamtaleTags.tsx
- src/components/mote/components/innkalling/VurderOppgaveForDialogmotesvarKnapp.tsx
- src/components/motebehov/BehandleMotebehovKnapp.tsx
- src/components/personoppgave/BehandlePersonOppgaveKnapp.tsx
- src/data/personoppgave/types/BehandlePersonoppgaveRequestDTO.ts
- src/data/personoppgave/useBehandlePersonoppgave.ts
- src/styles/_checkboxKnappWrapper.less
- src/styles/styles.less
- src/utils/personOppgaveUtils.ts
- test/behandlerdialog/MeldingerTest.tsx
1. Flytter ut knappen for å behandle personoppgaver i en egen komponent
2. Tar inn checkbox fra nytt designsystem
- Litt mer padding på denne enn den forrige, må i så fall override litt styles for å få det likt som den gamle. 
Se bildet. I dag er feks `vurder møtebehov` et annet endepunkt og tok jeg ikke i bruk den nye `behandlePersonoppgave`-knappen her, selv om man fint kunne gjort det. Ville ikke gjøre for mye endringer på en gang, bare 🤔
> Behandle all personoppgaver for behandlerdialog svar

- src/api/axios.ts
- src/components/behandlerdialog/meldinger/MeldingInnholdPanel.tsx
- src/components/behandlerdialog/meldinger/MeldingerISamtale.tsx
- src/components/behandlerdialog/meldinger/PdfVedleggLink.tsx
- src/components/behandlerdialog/meldinger/SamtaleAccordion.tsx
- src/data/behandlerdialog/behandlerdialogQueryHooks.ts
- test/behandlerdialog/BehandlerdialogSideTest.tsx
- test/behandlerdialog/MeldingerTest.tsx
Her er variant som henter vedlegg-pdf direkte fra API ved klikk på lenke. For at dette skal fungere må vi endre på veileder-tilgangsjekken i APIet i isbehandlerdialog siden vi nå ikke sender med `personIdent` i request-header: https://github.com/navikt/isbehandlerdialog/compare/master...vedlegg-api-alt2 - lager PR her også hvis vi går for denne løsningen.
> Fetch vedlegg on click via direct link to pdf-url

- mock/isbehandlerdialog/behandlerdialogMock.ts
- src/components/behandlerdialog/meldinger/MeldingInnholdPanel.tsx
- src/components/behandlerdialog/meldinger/MeldingerISamtale.tsx
- src/components/behandlerdialog/meldinger/SamtaleAccordion.tsx
- src/components/behandlerdialog/meldinger/SamtaleTags.tsx
- src/components/behandlerdialog/meldinger/Samtaler.tsx
- src/components/behandlerdialog/meldinger/VisMelding.tsx
- src/data/behandlerdialog/behandlerdialogTypes.ts
- test/behandlerdialog/MeldingerTest.tsx
Ikke nødvendigvis realistisk mock (siden man har svart på en meldingFraBehandler), men legger til tag dersom man har status `AVVIST`. Dersom man har fått `statusTekst` skal man også vise en alert under meldingen.
Har ikke utvidet endepunktet (og responsen) i backend enda, Anders jobber med det 👍🏼
> Show tag for avvist melding

- test/behandlerdialog/MeldingerTest.tsx
- test/behandlerdialog/meldingTestdataGenerator.ts
Denne testfilen var ganske lang og uoversiktlig, så forhåpentligvis blir den litt bedre nå ved å dele inn i flere describes og kategorisere testene deretter. 
Evt kunne man nok delt inn i flere testfiler også, det hadde sikkert vært enda mer ryddig. Tanker?
> Refactor MeldingerTest with describes per subject

- mock/ispersonoppgave/personoppgaveMock.ts
- src/components/behandlerdialog/meldinger/BehandleBehandlerdialogSvarOppgaveKnapp.tsx
- test/behandlerdialog/MeldingerTest.tsx
Fikser bug https://trello.com/c/D0mwLEEn/1484-behandlerdialog-feil-tekst-marker-nye-meldinger-som-lest-osv-ved-inaktiv-checkbox hvor det ble vist disabled checkbox med tekst for å markere oppgaven som behandlet.
> Only show behandle oppgave-checbox if behandlerdialog-svar-oppgaver

- src/components/behandlerdialog/meldinger/SamtaleTags.tsx
Var noe alignment-issues på samtaletagsene (Påminnelse var ikke "midt på" i raden sin):
Før:
Etter:
> Add styling to SamtaleTags

- mock/common/mockConstants.ts
- mock/isbehandlerdialog/behandlerdialogMock.ts
- src/components/behandlerdialog/meldinger/MeldingInnholdPanel.tsx
- src/data/behandlerdialog/behandlerdialogTypes.ts
- test/behandlerdialog/MeldingerTest.tsx
- test/testQueryClient.ts
Viser veiledernavn på samme måte som vi viser behandlernavn.
> Show veiledernavn for utgående melding

- src/data/behandlerdialog/behandlerMeldingTexts.ts
- src/hooks/behandlerdialog/document/useMeldingTilBehandlerDocument.ts
- test/behandlerdialog/MeldingTilBehandlerTest.tsx
- test/behandlerdialog/testDataDocuments.ts
Tas ikke i bruk enda, vi må få på plass mulighet til å velge meldingstype først og kunne sende inn en legeerklaring. Tester det når sånt er på plass 👍🏼
> Add new brevtekster for legeerklaring

- mock/syfoperson/brukerinfoMock.ts
- src/components/personkort/PersonkortHeader/PersonkortHeaderTags.tsx
- src/data/navbruker/navbrukerQueryHooks.ts
- src/data/navbruker/types/BrukerinfoDTO.ts
- test/components/personkort/PersonkortHeaderTest.tsx
- test/stubs/stubSyfoperson.ts
Legger til tags for tilrettelagt kommunikasjon på `PersonKort`. For en person kan det enten være behov for tilrettelagt kommunikasjon i form av talespråk eller tegnspråk.
Avklaringer:
Relatert til [PR i syfoperson](https://github.com/navikt/syfoperson/pull/144)
> Added tags for talesprak and tegnsprak

- src/components/behandlerdialog/meldinger/BehandleBehandlerdialogSvarOppgaveKnapp.tsx
- src/components/behandlerdialog/meldinger/SamtaleTags.tsx
- src/components/personoppgave/BehandlePersonOppgaveKnapp.tsx
- test/behandlerdialog/MeldingerTest.tsx
- test/behandlerdialog/SamtalerTagsTest.tsx
Etter litt tilbakemelding på demo med PO Helse og diskusjon i `#syfo_dialogmeldinger` så ønsket vi å endre litt på tagen for når man har fått et nytt svar.
> Change behandlerdialog-svar tag to "Nytt svar"

- mock/ispersonoppgave/personoppgaveMock.ts
- src/components/personoppgave/BehandlePersonOppgaveKnapp.tsx
- test/behandlerdialog/MeldingerTest.tsx
Det har blitt nevnt at veiledere ikke har noe særlig forhold til veilederident, og at derfor burde vi også vise navn i disse tilfellene. Er ingen skisser på det, så her er et forslag.
> Include behandlernavn in ferdigstillelse av oppgave text

- src/components/behandlerdialog/meldingtilbehandler/MeldingTilBehandler.tsx
- src/components/behandlerdialog/meldingtilbehandler/MeldingsTypeInfo.tsx
- Fikset spacing rundt warning label om info rundt tilleggsopplysninger i dialog med behandler. 
- Fikset også at alerten ikke er full bredde, men er like bred som innholdet.
> Fixed spacing around warning label

- src/data/unleash/unleashQueryHooks.ts
- test/testQueryClient.ts
Fjernet `behandlerRef` query param i kallet vårt til unleash ettersom det ikke er i bruk. 
- Klarer heller ikke egentlig å se at `userId` er i bruk i unleash🤔 Ser vi har en strategi som heter `byUserId`, men inne på beskrivelsen av denne ser det ut som query parameteret er `user`🧐
> Remove behandlerRef query param to unleash

- src/components/behandlerdialog/meldingtilbehandler/MeldingTilBehandlerSkjema.tsx
- src/components/behandlerdialog/meldingtilbehandler/MeldingsTypeInfo.tsx
- src/components/behandlerdialog/meldingtilbehandler/SelectMeldingType.tsx
Fikk warning i consollen på at man heller burde bruke `defaultValue` fra select-komponenten enn å legge `selected` på `option`-tagene.
> Move defaultvalue from option to select-tag

- mock/syfosmregister/sykmeldingerMock.ts
- src/components/speiling/sykmeldinger/sykmelding/sykmeldingOpplysninger/flereopplysninger/MeldingTilNAV.tsx
- src/utils/sykmeldinger/sykmeldingUtils.ts
- test/utils/sykmeldingUtilsTest.ts
- test/utils/sykmeldingutils/sykmeldingUtilsMeldingTilNavTest.ts
Sometimes the 'Nav bør ta tak i saken' box isn't checked in the sykmelding (see section 8 here https://cdn.sanity.io/files/gx9wf39f/soknadsveiviser-p/544438c9bbcac38217940ba9ef7ceaff3b501afe.pdf) , but there is still a begrunnelse. Always show the begrunnelse text if it exists.
> Always show melding til NAV in sykmelding if it exists

- src/components/behandlerdialog/meldinger/AvvistMelding.tsx
- src/components/behandlerdialog/meldinger/MeldingerISamtale.tsx
- test/behandlerdialog/AvvistMeldingTest.tsx
- test/behandlerdialog/SamtalerTagsTest.tsx
> Justerer avvist-melding-oppgavetekst og fjerner feilmelding-alert

- mock/isbehandlerdialog/behandlerdialogMock.ts
- mock/isbehandlerdialog/mockIsbehandlerdialog.ts
- mock/ispersonoppgave/personoppgaveMock.ts
- server/routes/unleashRoutes.ts
- src/components/behandlerdialog/MeldingActionButton.tsx
- src/components/behandlerdialog/legeeklaring/ReturLegeerklaring.tsx
- src/components/behandlerdialog/meldinger/MeldingerISamtale.tsx
- src/components/behandlerdialog/paminnelse/PaminnelseMelding.tsx
- src/data/unleash/unleash_types.ts
- test/behandlerdialog/MeldingerISamtaleTest.tsx
- test/behandlerdialog/PaminnelseTest.tsx
I tillegg:
- Ryddet litt i uuid-er i mockdata
- Flyttet tester på visning av knappene for påminnelse og retur til egen test-fil.
- Refaktorert til MeldingActionButton som brukes av påminnelse og retur.
> Add toggle and button for retur legeerklaring

- mock/isbehandlerdialog/behandlerdialogMock.ts
- src/components/behandlerdialog/meldinger/MeldingInnholdPanel.tsx
- src/components/behandlerdialog/meldinger/PdfVedleggLink.tsx
- test/behandlerdialog/MeldingerTest.tsx
- test/behandlerdialog/meldingTestdataGenerator.ts
For en innkommende legeerklæring-melding vil første vedlegg alltid være selve legeerklæringen - justerer vedlegg lenke-teksten iht dette.
> Adjust vedlegg link for legeerklaring

- mock/unleashMocks.ts
- package-lock.json
- package.json
Oppdaterer `unleash-client`.
Grunnen til at diffen i `package-lock.json` er så stor lurer jeg på om er fordi cypress ble fjernet, men ikke fra dependencies og at dette er et resultat av dette 😊
> IS: Updates unleash-client + more dependencies

- src/components/personkort/OversiktLenker.tsx
Etter ønske fra Tor Halle og veiledere på åpen dag
> [IS-1598] Add link to enhetens oversikt from modia

- mock/isaktivitetskrav/aktivitetskravMock.ts
- src/components/aktivitetskrav/historikk/AktivitetskravHistorikk.tsx
- test/aktivitetskrav/AktivitetskravHistorikkTest.tsx
- test/aktivitetskrav/VurderAktivitetskravTest.tsx
På sikt vil vi også vise brevet/dokumentet som ble sendt ut her, men det krever endringer i endepunktet, slik at dette er foreløpig løsning med kun friteksten/begrunnelsen fra veileder.
> IS-1579: Add forhåndsvarsel to historikk-list, showing beskrivelse

- mock/isbehandlerdialog/behandlerdialogMock.ts
- mock/isdialogmote/dialogmoterMock.ts
- src/components/DocumentComponentVisning.tsx
- src/data/aktivitetskrav/aktivitetskravTexts.ts
- src/data/documentcomponent/documentComponentTypes.ts
- src/hooks/aktivitetskrav/useAktivitetskravVarselDocument.ts
- src/hooks/useDocumentComponents.ts
- src/utils/documentComponentUtils.ts
- test/aktivitetskrav/varselDocuments.ts
- test/behandlerdialog/testDataDocuments.ts
- test/dialogmote/testDataDocuments.ts
Legger til støtte for `BULLET_POINTS` og `HEADER_H3` komponenter i document components. Dette trengs for å rendre pdf riktig med bulletpoints og riktig header størrelse. Se IS-1605 på trello for mer info.
Se tilhørende PR'er i [isaktivitetskrav](https://github.com/navikt/isaktivitetskrav/pull/119) og [isaktivitetskravpdfgen](https://github.com/navikt/isaktivitetskravpdfgen/pull/4)
> IS-1605: Add BULLET_POINTS element and fix texts

- src/utils/datoUtils.ts
- test/utils/datoUtilsTest.ts
Vi fikk en JIRA-sak der det ikke hadde blitt generert aktivitetskrav, men så stod det "Varighet: 8 uker" i personkortet i modia. Varighet bruker `getWeeksBetween` som runder av til nærmeste heltall.
Hvorvidt dette er riktig logikk kan Stine og TH vurdere, jeg tenker feks at `Math.floor()` kanskje hadde vært bedre slik at man ikke viser et lenger sykefravær enn de egentlig har 🤔 
Her er hvertfall en test for utils-metoden, siden vi manglet det.
> Add test for getWeeksBetween to datoer

- src/components/Layout.tsx
- src/components/speiling/sykmeldinger/sykmeldinger/SykmeldingPeriodeInfo.tsx
- src/components/speiling/sykmeldinger/sykmeldinger/SykmeldingTeaser.tsx
Endrer til å bruke LinkPanel i sykmelding-liste-visning. Viser alltid periodeinfo (gradering + dager) i punktliste uavhengig av antall perioder for å unngå visningsbug (ref: https://trello.com/c/wtve2TH4/1521-visningsfeil-p%C3%A5-ditt-sykefrav%C3%A6r)
> Use LinkPanel for SykmeldingTeaser

- mock/isbehandlerdialog/mockIsbehandlerdialog.ts
- src/components/behandlerdialog/meldinger/SamtaleTags.tsx
- test/behandlerdialog/MeldingerTest.tsx
- test/behandlerdialog/SamtalerTagsTest.tsx
- test/behandlerdialog/meldingTestdataGenerator.ts
Fjerner den gule "Venter på svar"-tagen fra `Melding fra NAV`-meldingene. Se også samtale i slack: https://nav-it.slack.com/archives/C04M11803C1/p1695644242139439
I mange tilfeller forventer ikke veileder svar på disse type meldingene, og derfor har det kommet kommentarer fra pilotgruppa at det står en gul "Venter på svar"-tag på samtalen for evig. En løsning er derfor å ikke vise den tagen når den utgående meldingen er en Melding fra NAV. Veileder vil uansett få en oppgave dersom det kommer inn et svar, så tror ikke denne tagen er så viktig å vise for denne meldingtypen.
Vises fortsatt for de to andre meldingstypene
> IS-1626: Hide venter-på-svar tag if melding is of type melding fra NAV

- mock/isbehandlerdialog/behandlerdialogMock.ts
- src/components/behandlerdialog/meldinger/SamtaleAccordionItem.tsx
- src/components/behandlerdialog/meldingtilbehandler/MeldingsTypeInfo.tsx
- src/data/behandlerdialog/behandlerdialogTexts.ts
- src/data/behandlerdialog/behandlerdialogTypes.ts
- src/hooks/behandlerdialog/document/useMeldingTilBehandlerDocument.ts
- test/behandlerdialog/MeldingerTest.tsx
Lagt til meldingstype `HENVENDELSE_MELDING_TIL_NAV`, gjort `behandlerRef` nullable i MeldingDTO og håndterer visning av navn på behandler for meldinger uten behandlerRef.
For meldinger initiert av veileder vil `behandlerRef` være satt ut i fra behandleren som er valgt som mottaker. Meldinger fra behandler til NAV vil ikke ha satt dette feltet. I disse tilfellene kan vi bruke behandlerNavn-feltet fra meldingen (kommer fra dialogmeldingen) til å vise navn på behandler.
> IS-1684: Handle behandlerNavn for HENVENDELSE_MELDING_TIL_NAV

- src/components/behandlerdialog/meldinger/BehandleBehandlerdialogSvarOppgaveKnapp.tsx
- src/components/behandlerdialog/meldinger/SamtaleTags.tsx
- src/components/personoppgave/BehandlePersonOppgaveKnapp.tsx
- test/behandlerdialog/MeldingerTest.tsx
- test/behandlerdialog/SamtalerTagsTest.tsx
Siden vi snart skal ta inn meldingstypen `HENVENDELSE_MELDING_TIL_NAV` fra behandler.
Endret tekster fra nytt svar til ny melding slik at det også passer for meldinger fra behandler som ikke er svar på en melding fra NAV.
> IS-1706: Endret tekst for tag og oppgave fra svar -> melding

- src/components/aktivitetskrav/vurdering/AvventAktivitetskravSkjema.tsx
- src/components/aktivitetskrav/vurdering/SendForhandsvarselSkjema.tsx
- src/components/aktivitetskrav/vurdering/VurderAktivitetskravBeskrivelse.tsx
- test/aktivitetskrav/VurderAktivitetskravTest.tsx
This will make it clearer for veiledere that this is related to a decision they're making, not just some information they're writing. This doesn't change all variable names and such because to rename everything is a big job and has consequences for the backend as well.
Endret navnet på fritekstfeltene i aktivitetskravskjema fra "beskrivelse" til "begrunnelse"
> IS-1699: Change beskrivelse to begrunnelse in aktivitetskrav skjema

- src/components/aktivitetskrav/vurdering/SendForhandsvarselSkjema.tsx
- test/aktivitetskrav/VurderAktivitetskravTest.tsx
Det er ikke helt avklart med IA- og sykefraværskontoret at dette er strategien vi skal påtvinge kontorene ifbm forhåndsvarselet, så da fjernes den foreløpig.
> IS-1767: Remove infobox

- mock/isaktivitetskrav/aktivitetskravMock.ts
- src/components/aktivitetskrav/historikk/AktivitetskravHistorikk.tsx
- src/data/aktivitetskrav/aktivitetskravTexts.ts
- src/data/aktivitetskrav/aktivitetskravTypes.ts
- src/data/aktivitetskrav/forhandsvarselTexts.ts
- src/hooks/aktivitetskrav/useAktivitetskravVarselDocument.ts
- test/aktivitetskrav/AktivitetskravHistorikkTest.tsx
- test/aktivitetskrav/varselDocuments.ts
- test/testDataUtils.ts
Gjør det mulig å se hele varsel-brevet som ble sendt ut ifbm forhåndsvarsel i historikk-fanen i akt.kravet. Har også lagt på noen enkle forbedringer:
- Beskrivelse -> Begrunnelse
- "Vurdert av" overskrift før navnet på veileder dukker opp
Har også lagt på en måling i amplitude av hvor ofte knappen trykkes på. Dette kan man feks se opp mot sidebesøk på Akt.krav-siden. Tror ikke det er rent sammenlignbart, fordi de sikkert er inne på den siden veldig ofte, og alle har jo ikke et forhåndsvarsel 🤷🏼‍♂️ Tenker jeg skal legge på en måling på accordionene også, så vi kan finne ut av om de bruker historikken veldig mye eller ikke, men tar det i en egen PR.
> IS-1601: Add button for showing preview of varsel-document

- src/components/aktivitetskrav/historikk/AktivitetskravHistorikk.tsx
- src/utils/amplitude.ts
Gjør accordionene controlled, og legger på en amplitude-telling. Vi får se om den bærer frukter. 
Visstnok er "accordion åpnet" et eget event, så prøvde å legge det til. Vet ikke om det blir riktig: https://github.com/navikt/analytics-taxonomy/tree/main/events
> Add amplitude tracking to check how often users open the historikk-accordions

- src/components/aktivitetskrav/AktivitetskravSide.tsx
- src/components/aktivitetskrav/GjelderOppfolgingstilfelle.tsx
- src/components/aktivitetskrav/vurdering/StartNyVurdering.tsx
- src/components/aktivitetskrav/vurdering/VurderAktivitetskrav.tsx
- src/components/aktivitetskrav/vurdering/VurderAktivitetskravButtons.tsx
- src/components/aktivitetskrav/vurdering/VurderAktivitetskravModal.tsx
- src/components/aktivitetskrav/vurdering/VurderAktivitetskravTabs.tsx
- src/components/aktivitetskrav/vurdering/vurderAktivitetskravSkjemaTypes.ts
- src/data/aktivitetskrav/useCreateAktivitetskrav.ts
- src/data/aktivitetskrav/useStartNyVurdering.ts
- test/aktivitetskrav/AktivitetskravSideTest.tsx
- test/aktivitetskrav/StartNyVurderingTest.tsx
- test/aktivitetskrav/VurderAktivitetskravTest.tsx
Viser Start ny vurdering-side dersom det ikke finnes noe aktivitetskrav å vurdere. Trykk på knappen skal kalle nytt api for å opprette aktivitetskrav med status `NY_VURDERING`. Så er tanken at man får dette aktivitetskravet tilbake fra GET-kallet til apiet og VurderAktivitetskrav-siden vil vises.
NB: Må vente med merging til nytt API er klart i isaktivitetskrav og dette er testet i dev.
> IS-1690: Start ny vurdering uten aktivitetskrav

- src/components/aktivitetskrav/vurdering/VurderAktivitetskravTabs.tsx
- test/aktivitetskrav/VurderAktivitetskravTest.tsx
Kom på at dette er noe vi kanskje burde ha på plass. Det er ikke mulig å sende et forhåndsvarsel to ganger i backenden, men fint å også støtte dette i frontenden ved å skjule fanen. Man kan altså bare sende forhåndsvarsel når statusen er NY, AVVENT eller NY_VURDERING. Det er samme logikk som i backend. Ettersom det ikke er mulig å sette AVVENT etter at et forhåndsvarsel har gått ut, så kan man da heller ikke gjøre forhåndsvarsel --> avvent --> forhåndsvarsel.
Vi hadde også noe async-issues i testene som gjør at de feiler i GA av og til, så fikser det i samme slengen 🤞🏼
> IS-1609: Hide forhandsvarsel-tab when already sent forhåndsvarsel

- src/components/aktivitetskrav/vurdering/ForhandsvarselOppsummering.tsx
- src/styles/style.css
Det var ganske stygt på ubuntu/windows med scrollbars her, så prøver å gjøre noen forbedringer. Oppdaget ikke dette på min flotte Mac-maskin.
Se: https://dev.to/derick1530/how-to-create-scrollable-element-in-tailwind-without-a-scrollbar-4mbd
Før: 
Nå: når testen er kort:
Nå: når teksten er lang:
> Hide scrollbars

- src/components/aktivitetskrav/vurdering/VurderAktivitetskravTabs.tsx
- test/aktivitetskrav/VurderAktivitetskravTest.tsx
Vi viser `Ikke oppfylt` selv uten forhåndsvarsel, ettersom at de som har sendt forhåndsvarsel fra Arena vil sluttføre ting i Modia, særlig hvis de har satt feks Avventer først.
> IS-1814: Show ikke oppfylt tab all the time

- src/components/personkort/PersonkortHeader/MaksdatoSummary.tsx
- src/components/personkort/PersonkortHeader/PersonkortHeader.tsx
- src/components/personkort/PersonkortHeader/SyketilfelleSummary.tsx
- src/components/personkort/PersonkortHeader/TilfellePeriod.tsx
- src/components/personkort/PersonkortHeader/Varighet.tsx
Det ble noen rariterer i personkortet etter at vi byttet ut mange av `<></>` med `<div>`. 
Har også refaktorert litt kode, ettersom at alle hadde samme logikk for visning med `Noe: noe annet i bold`.
Flytta også maksdato inn under samme komponent som alle de andre lignende infoelementene lå under.
Før:
Nå:
> Fix personkort styling

- src/components/aktivitetskrav/vurdering/IkkeAktuellAktivitetskravSkjema.tsx
- test/aktivitetskrav/VurderAktivitetskravTest.tsx
- Legger til "begrunnelse" felt for når en veileder ønsker å gjøre en `IKKE_AKTUELL` vurdering.
Ser ut til å fungere utav boksen.
> IS-1806: Add field for begrunnelse in IKKE_AKTUELL vurdering

- src/components/behandlerdialog/meldingtilbehandler/MeldingTilBehandlerSkjema.tsx
- src/components/behandlerdialog/meldingtilbehandler/MeldingsTypeInfo.tsx
Så at det på et tidspunkt har blitt endret litt i stylingen på skjemaet, muligens i forbindelse med overgangen til react-hook-form. I følge skissene skal teksten være aligned i center, og helst breake på samme sted/ha samme bredde som Select-boksen.
Ellers litt andre forbedringer som å bruke mer tailwind.
Før:
Etter:
> Fix styling on meldingtypeInfo

- mock/isaktivitetskrav/mockIsaktivitetskrav.ts
- src/components/aktivitetskrav/AktivitetskravContainer.tsx
- src/components/aktivitetskrav/AktivitetskravSide.tsx
- src/components/aktivitetskrav/useAktivitetskravNotificationAlert.ts
- src/components/aktivitetskrav/vurdering/AktivitetskravVurderingAlert.tsx
- src/components/aktivitetskrav/vurdering/IkkeAktuellAktivitetskravSkjema.tsx
- src/components/aktivitetskrav/vurdering/IkkeOppfyltAktivitetskravSkjema.tsx
- src/components/aktivitetskrav/vurdering/OppfyltAktivitetskravSkjema.tsx
- src/components/aktivitetskrav/vurdering/StartNyVurdering.tsx
- src/components/aktivitetskrav/vurdering/UnntakAktivitetskravSkjema.tsx
- src/components/aktivitetskrav/vurdering/VurderAktivitetskrav.tsx
- src/context/notification/NotificationContext.tsx
- test/aktivitetskrav/AktivitetskravSideTest.tsx
- test/aktivitetskrav/AktivitetskravVurderingAlertTest.tsx
- test/aktivitetskrav/StartNyVurderingTest.tsx
- test/aktivitetskrav/VurderAktivitetskravTest.tsx
Endrer til å vise success-alert for vurdering bare etter vurderingen er sendt og ikke hver gang man går inn på aktivitetskrav-siden.
> Use notification alert on final aktivitetskrav vurdering

- src/components/aktivitetskrav/vurdering/OppfyltAktivitetskravSkjema.tsx
- test/aktivitetskrav/VurderAktivitetskravTest.tsx
- "Begrunnelse" felt er ikke lenger obligatorisk å fylle ut når veileder vurderer innbygger til "I aktivitet"/`OPPFYLT`
> IS-1815: Set begrunnelse optional

- src/components/ExpandableBlockquote.tsx
- src/components/aktivitetskrav/vurdering/ForhandsvarselOppsummering.tsx
Shows expand button when text exceeds default size.
Currently only used for showing forhåndsvarsel, but can be used other places as well.
Next iteration could add a way to let user define default size.
> Add blockquote with button for expanding

- src/components/motebehov/GenerellSykmeldingInfo.tsx
- src/components/motebehov/Perioder.tsx
- src/components/utdragFraSykefravaeret/UtdragFraSykefravaeret.tsx
- test/components/UtdragFraSykefravaeretTest.tsx
- test/testQueryClient.ts
Ifbm tredeling endret jeg litt på utseendet til sykmeldingene i utdraget fra sykefraværet, slik at arbeidsgiver var mer synlig. Vi fikk tilbakemeldinger på Yammer om at arbeidsgiver ikke var like viktig, som regel var det den samme hver gang, og at dato, sykmeldingsgrad og diagnose var det de lette etter. 
I tillegg ønsket de å se hvem som hadde sendt inn sykmeldingen, feks hvis de skulle sende en dialogmelding til den gitte meldingen. Det feltet har vi hatt tilgjengelig lenge, uten å vise. Legger derfor til dette også når man åpner sykmeldingen.
> IS-1764: Show sykmelder in sykmelding

- src/sider/Side.tsx
- src/sider/TredeltSide.tsx
Det var noen tilbakemeldinger om at sykmeldingen ble for smal, så da gir vi de litt mer plass ved å fjerne margins, og bytte fra en 66/33% view til 60/40%
> Give more space to third column

- package-lock.json
- src/components/aktivitetskrav/AktivitetskravContainer.tsx
- src/components/utdragFraSykefravaeret/UtdragFraSykefravaeret.tsx
Når skjermen blir mindre enn 1300px (som den alltid vil være for de med 150% zoom), så beholder vi samme gamle design på todelingen. Tanken var at aktivitetskravsiden skulle være sticky også i todelingen, slik at veileder kunne se personkortet til enhver tid, men å bytte tilbake til at hele siden kan scrolles er en enkel fiks og et kjent mønster for de som nå sliter med liten skjerm.
Før:
Etter:
> IS-1870: Fix scrolling when todeling in 150% zoom

- src/components/speiling/sykepengsoknader/soknad-felles-oppsummering/OppsummeringBekreftelsespunkter.tsx
Used wrong component name after copy paste, but it got correct name in OppsummeringSporsmal because it's default export.
We were unsure about Undertekst, but it isn't needed for this SvarType.
> Rename, remove undertekst from Bekreftelsespunkter

- src/components/motebehov/GenerellSykmeldingInfo.tsx
- src/components/motebehov/SykmeldingUtdragFraSykefravaretVisning.tsx
- src/components/utdragFraSykefravaeret/UtdragFraSykefravaeret.tsx
På denne måten kan veileder se viktig informasjon allerede før de ekspanderer sykmeldingen. Utseende avklarte med Stine og Andrea.
> IS-1881: Move AG and sykmelder to header of expansion card

- src/utils/datoUtils.ts
- test/behandlerdialog/MeldingerTest.tsx
- Måned vi lette etter var hardkodet inn i testen. Dette gjorde at testen nå feilet når vi kom til desember.
- Løsningen nå er litt vanskelig å lese synes jeg, men henter månedens navn og prøver å finne denne i stedet for et hardkodet månedsnavn.
> IS: Fix meldingertest.tsx

- mock/huskelapp/mockHuskelapp.tsx
- src/components/huskelapp/Huskelapp.tsx
- src/components/huskelapp/HuskelappModal.tsx
- src/data/huskelapp/huskelappTypes.ts
- test/huskelapp/HuskelappModalTest.tsx
Mulighet til å lagre frist når man lager oppfølgingsoppgave, og at fristen vises når man har lagret.
Synes det er litt rart at datepickeren også er i en modal, så blir modal i modal, men er sånn på avventer også. Mulig man kan endre på noen instillinger i komponenten.
> IS-1868: Add frist-option in trenger oppfølging modal

- src/data/aktivitetskrav/forhandsvarselTexts.ts
Endret noen tekster i forhåndsvarselet iht https://trello.com/c/yLjwI96W/1836-endringer-i-brevmalen-for-forh%C3%A5ndsvarsel
**Info om året 1836**
[Republikken Texas](https://no.wikipedia.org/wiki/Republikken_Texas) erklærer seg uavhengig fra [Mexico](https://no.wikipedia.org/wiki/Mexico).
> IS-1836: Tekstendringer forhåndsvarselet

- mock/huskelapp/mockHuskelapp.tsx
- src/components/huskelapp/Huskelapp.tsx
- src/data/huskelapp/huskelappTypes.ts
- test/huskelapp/HuskelappModalTest.tsx
Viser veilederen som har laget trenger-oppfolging oppgaven og når den ble sist endret. Jeg tenker man kan snakke litt om vi burde vise `updatedAt` eller `createdAt`. Per idag så kan man ikke oppdatere huskelappen, men "fjern" og cronjob-publisering gjør begge en update på `updatedAt`-feltet. Etter "fjern" vil den ikke vises, og cronjoben kjører 1-2 minutter etter create, så det vil fortsatt være samme dato som createdAt når vi bruker updatedAt (med mindre vi er uheldige og en veileder lager oppgaven kl 23:59). 
Med andre ord: Per idag vil `updatedAt` og `createdAt` være samme dag så lenge oppgaven er synlig i syfomodiaperson, så det har kanskje ikke så mye å si hvilken av dem som vises. Men hvis vi begynner med endringer på dagens mønster, så burde dette tas i betraktning. Jeg valgte å …
> IS-1742: Show veileder and last update for trenger oppfolging

- mock/isaktivitetskrav/aktivitetskravMock.ts
- src/components/aktivitetskrav/vurdering/SendForhandsvarselSkjema.tsx
- src/components/aktivitetskrav/vurdering/SkjemaHeading.tsx
- src/data/aktivitetskrav/aktivitetskravTypes.ts
- src/data/aktivitetskrav/forhandsvarselTexts.ts
- src/hooks/aktivitetskrav/useAktivitetskravVarselDocument.ts
- src/utils/amplitude.ts
- test/aktivitetskrav/VurderAktivitetskravTest.tsx
- test/aktivitetskrav/varselDocuments.ts
Lagt til select-komponent med mulighet for å velge brevmal (Med arbeidsgvier / Uten arbeidsgiver) ved sending av forhåndsvarsel.
Design er avsjekket med Andrea. Skal avklare endelige tekster med Stine og om vi trenger både label og description og hva som evt skal stå der. Tar gjerne innspill på det også :+1: 
Har også lagt til logging av event i Amplitude når bruker gjør et valg i selecten.
> IS-1812: Add forhåndsvarsel brevmal select

- src/components/Layout.tsx
- src/components/mote/components/DialogmotePanel.tsx
- Legger til mindre marginer mellom paneler på dialogmøte side
Før:
Ettter:
> IS: Added smaller margins to dialogmote page panels

- src/components/dialogmote/DialogmoteTidOgSted.tsx
- src/components/dialogmote/FritekstSeksjon.tsx
- src/components/dialogmote/innkalling/DialogmoteInnkallingBehandler.tsx
- src/components/dialogmote/innkalling/DialogmoteInnkallingSkjema.tsx
- src/components/dialogmote/innkalling/DialogmoteInnkallingSkjemaSeksjon.tsx
- src/components/dialogmote/innkalling/DialogmoteInnkallingTekster.tsx
- src/components/dialogmote/innkalling/virksomhet/DialogmoteInnkallingVelgVirksomhet.tsx
Veiledere don't want to scroll so much when writing an innkalling, so we need to make the form more compact with less air. Change "frist" to "Frist dialogmøte 2" to make it more clear. Remove section headers.
Decrease margin between sections.
Decrease margin between Tid og sted fields.
> IS-1923: Make DM-innkallingskjema more compact

- package-lock.json
- package.json
- src/utils/amplitude.ts
Ref https://nav-it.slack.com/archives/CMK1SCBP1/p1703242354102479
Se https://www.docs.developers.amplitude.com/data/sdks/typescript-browser/migration/
En del av config-parameterne er ikke støttet lenger så vi får heller justere etter hvert hvis ikke defaultene i den nye SDKen gjør jobben.
> Migrate to amplitude/analytics-browser

- src/components/dialogmote/DialogmoteTidOgSted.tsx
- src/components/dialogmote/innkalling/DialogmoteInnkallingSkjema.tsx
The experiment is concluded, so the code is no longer needed.
The warning didn't make veiledere select møtedato closer to innkallingsdato.
Før:
Etter:
> Remove warning for møtedato too far into future

- src/components/dialogmote/motehistorikk/MoteHistorikkUnntak.tsx
- src/components/dialogmote/motehistorikk/MotehistorikkPanel.tsx
- test/dialogmote/MotehistorikkTest.tsx
Veiledere don't want modal because then they have to repeatedly open and close it when filling out the form.
Før:
Etter:
> IS-1925: Show motehistorikk as accordion

- mock/syfoperson/persondataMock.ts
- src/components/personkort/Personkort.tsx
- src/components/personkort/PersonkortElement.tsx
- src/components/personkort/PersonkortEnhet.tsx
- src/components/personkort/PersonkortHeader/PersonkortHeaderTags.tsx
- src/components/personkort/PersonkortSikkerhetstiltak.tsx
- src/components/personkort/PersonkortSykmeldt.tsx
- src/data/navbruker/navbrukerQueryHooks.ts
- src/data/navbruker/navbruker_hooks.ts
- src/data/navbruker/types/BrukerinfoDTO.ts
- test/components/personkort/PersonkortHeaderTest.tsx
- test/components/personkort/PersonkortTest.tsx
Viser tag i header og ny fane for sikkerhetstiltak i personkortet dersom bruker har sikkerhetstiltak registrert.
Gjenstår å avklare endelig design og visning med Peter/Stine, men regner med det blir noe sånt-ish.
Før:
Etter:
> IS-1955: Sikkerhetstiltak tag and tab in personkortet

- src/components/oppfolgingsplan/lps/OppfolgingsplanerOversiktLPS.tsx
Veiledere don't want to download the pdf, so we should open it in a new tab instead.
> Open LPS-planer in new tab

- src/components/utdragFraSykefravaeret/UtdragOppfolgingsplaner.tsx
Veiledere don't want to download the pdfs.
Same as PR #1169 but in "Utdrag fra sykefraværet".
> IS-1994: Open LPS-planer in new tab in Utdrag

- src/components/dialogmote/innkalling/virksomhet/VirksomhetRadioGruppe.tsx
- test/dialogmote/DialogmoteInnkallingSkjema/DialogmoteInnkallingSkjemaTest.tsx
Dette sparer veiledere for mange klikk.
Første arbeidsgiver blir automatisk valgt selv om "oppgi virksomhetsnummer" er tilgjengelig.
Hvis flere virksomheter er tilgjengelig, velges ingen automatisk.
> IS-1506: Auto select single virksomhet in DM form

- mock/syfoperson/personAdresseMock.ts
- src/components/personkort/PersonkortSykmeldt.tsx
- src/data/personinfo/types/PersonAdresse.ts
- src/utils/adresseUtils.tsx
Veiledere ønsker seg poststed for å slippe å slå opp postnummer.
Bruk de nye objektene fra isperson, med ubrukte felter fjernet og poststed lagt til.
Før:
Etter (med ny kontaktadresse som ikke er Oslo):
> IS-1848: Show poststed in personkort

- src/components/flexjar/EmojiButton.tsx
- src/components/flexjar/Flexjar.tsx
Jeg oppdaget at vi logget til amplitude hver gang man trykket på en emoji. Hvis en veileder klikker på feks flere emojies for å prøve seg litt frem, så får vi mange innslag i amplitude. Jeg husker ikke om dette var med vilje, men jeg tenker kanskje vi kun vil sende inn på submit? På den måten kan vi telle det litt lettere i Amplitude også, i stedet for å koble opp Metabase og Bigquery.
@andersrognstad husker du hvorfor vi puttet dette per emoji-trykk opprinnelig?
> Track flexjar-score in amplitude only on submit

- src/components/flexjar/Flexjar.tsx
- src/hooks/useLocalStorageState.ts
- src/sider/Side.tsx
- test/flexjar/FlexjarTest.tsx
I stedet for å vise flexjar på nytt hver dag, så sier vi nå at dersom du har svart en gang, så får du den ikke opp igjen. Vi kan ha det som utgangspunkt, og så heller endre på dette basert på mengden vi får inn.
Endrer også localstorage key-navnet, ettersom vi kanskje på sikt vil ha flexjar på flere sider enn bare aktivitetskravet. Da kan vi styre hvor ofte vi vil vise ting på hver enkelt side litt bedre.
> IS-2020: Adjust how often flexjar is displayed

- src/sider/aktivitetskrav/vurdering/VurderAktivitetskravTabs.tsx
- test/aktivitetskrav/VurderAktivitetskravTest.tsx
IKKE_OPPFYLT skal bare vises etter et forhåndsvarsel er sendt og utgått (dvs det er laget oppgave for å vurdere stans). Sjekken var fjernet tidligere pga påbegynte forhåndsvarsler i Arena.
> IS-1816: Bare vis Ikke oppfylt etter forhåndsvarsel er utgått

- src/apiConstants.ts
- src/data/historikk/historikkQueryHooks.ts
- src/data/motebehov/motebehovQueryHooks.ts
- src/data/motebehov/useBehandleMotebehov.ts
- src/data/motebehov/useBehandleMotebehovAndSendTilbakemelding.ts
- test/data/historikkQueryHooksTest.tsx
- test/stubs/stubSyfomotebehov.ts
Tar i bruk v3 av motebehov-apiet med personident i header i stedet for url. Kan merges etter https://github.com/navikt/syfomotebehov/pull/284
> IS-2015: Use personident in header in motebehov api-calls

- src/components/Forhandsvisning.tsx
- src/components/ForhandsvisningModal.tsx
- src/components/dialogmote/TextareaField.tsx
- src/sider/mote/components/avlys/AvlysDialogmoteSkjema.tsx
- test/dialogmote/AvlysDialogmoteSkjemaTest.tsx
Migrert dialogmote avlys-skjema til react hook form.
Fjernet for enkelhets skyld feiloppsumeringen nederst siden dette er et såpass enkelt skjema og feiloppsummeringskomponenten ikke uten videre fungerer med react-hook-form-feil.
> IS-1959: Avlys dialogmote react hook form

- src/components/flexjar/Flexjar.tsx
Vi har ikke fått noen tilbakemeldinger på flexjar enda. Da Stine testet Flexjar tidligere så oppdaget vi ved én anledning at den ble sjult på fullskjerm av en eller annen grunn. Hvis vi tracker om panelet faktisk åpnes så kan vi se om vi mister folk på veien, eller om de bare aldri åpner panelet.
> Add tracking of open Flexjar-panel

- src/components/ChooseMalform.tsx
- src/components/MalformRadioGroup.tsx
- src/components/dialogmote/innkalling/DialogmoteInnkallingSkjema.tsx
- src/context/malform/MalformContext.tsx
- src/data/dialogmote/dialogmoteTexts.ts
- src/hooks/dialogmote/document/useDialogmoteDocumentComponents.ts
- src/hooks/dialogmote/document/useInnkallingDocument.ts
- src/hooks/dialogmote/document/useReferatDocument.ts
- src/hooks/dialogmote/document/useTidStedDocument.ts
- src/utils/behandlerUtils.ts
- src/utils/datoUtils.ts
- test/dialogmote/AvlysDialogmoteSkjemaTest.tsx
- test/dialogmote/DialogmoteInnkallingContainerTest.tsx
- test/dialogmote/DialogmoteInnkallingSkjema/BehandlerInnkallingTest.tsx
- test/dialogmote/DialogmoteInnkallingSkjema/DialogmoteInnkallingPreviewTest.tsx
- test/dialogmote/DialogmoteInnkallingSkjema/DialogmoteInnkallingSkjemaTest.tsx
- test/dialogmote/DialogmoteInnkallingTeksterTest.tsx
- test/dialogmote/testData.ts
- test/dialogmote/testDataDocuments.ts
Her er et utkast for hvordan det kommer til å se ut. Tanken er at alle tekster skal være på formen `BOKMAL` eller `NYNORSK`, selv om det ikke er forskjell på tekstene. 
Det blir også noen anti-patterns her fordi det er mange brev i dialogmøte som bruker felleskomponenter, der kun innkallingen foreløpig skal ta i bruk målform. Feks må vi ta inn `malform` i noen metoder og sende nedover utils-funksjonene 😕 
Gjerne gi tilbakemelding i PR eller muntlig hvordan dere synes det fungerer!
Vi har basert tankegangen litt på denne artikkelen: https://blogg.bekk.no/lag-ditt-eget-typesikre-oversettelsesbibliotek-54f066348540
Se også context-state og localstorage-bruk her: https://github.com/navikt/syfomodiaperson/pull/1199
Slik ser velgeren ut per nå
> IS-1189: Add nynorsk to dialogmoteinnkalling

- src/sider/mote/components/endre/EndreDialogmoteContainer.tsx
Lagt til nytt panel med heading og `<DeltakereSvarInfo>` (samme komponent som på møte-landdingssiden) i tredeling med endre dialogmøte-skjema. 
Gjenstår en avsjekk med Peter på designet.
> IS-2013: Add tredeling with motesvar to endre-skjema

- mock/isdialogmote/dialogmoterMock.ts
- mock/isdialogmote/mockIsdialogmote.ts
I kjølvannet av nynorsk på dm-referat så oppdaget jeg at siden kræsjet hvis man skrev et referat på localhost og sendte inn, vet ikke hvor lenge det har vært sånn. Det var heller ikke mulig å lage nytt møte, eller å oppdatere status korrekt på de man hadde. Nå kan man avlyse, opprette, og skrive referat med riktig "state". Sikkert mer man kunne gjort for å gjøre det enda mer realistisk, men dette hindrer hvertfall ikke fra å gjennomføre en realistisk flyt selv om alle felter nødvendigvis ikke stemmer med hva man skriver/endrer etc.
> Improve mocks for dialogmote

- mock/syfooppfolgingsplanservice/mockSyfooppfolgingsplanservice.ts
- src/apiConstants.ts
- src/components/utdragFraSykefravaeret/UtdragOppfolgingsplaner.tsx
- src/data/historikk/historikkQueryHooks.ts
- src/data/oppfolgingsplan/oppfolgingsplanQueryHooks.ts
- src/sider/oppfolgingsplan/lps/OppfolgingsplanerOversiktLPS.tsx
- src/sider/oppfolgingsplan/oppfolgingsplaner/Oppfolgingsplan.tsx
- test/data/historikkQueryHooksTest.tsx
- test/data/oppfolgingsplanQueryHooksTest.tsx
- test/stubs/stubSyfooppfolgingsplan.ts
Det er ikke laget ny versjon av api for kall uten fnr i url så der brukes fortsatt v2.
NB: Merge etter https://github.com/navikt/syfooppfolgingsplanservice/pull/406
> IS-2034: Erstattet kall for historikk og oppfolgingsplan med v3 av api (uten fnr i url)

- mock/syfosmregister/sykmeldingerMock.ts
- src/components/utdragFraSykefravaeret/UtdragFraSykefravaeret.tsx
- src/data/sykmelding/types/SykmeldingStatusDTO.ts
- src/utils/sykmeldinger/sykmeldingUtils.ts
- test/components/UtdragFraSykefravaeretTest.tsx
- test/mockdata/sykmeldinger/mockSykmeldingExtraInfo.ts
- test/mockdata/sykmeldinger/mockSykmeldinger.ts
- test/utils/sykmeldingUtilsTest.ts
Fjernet filtrering av at det kun er sendte sykmeldinger som vises i utdraget fra sykefraværet. I tillegg legger vi på en tag for å vise for veilederen at denne ikke er tatt i bruk enda.
> IS-2036: Add NY sykmeldinger and show as "ikke tatt i bruk"

- src/components/MalformRadioGroup.tsx
- src/data/dialogmote/dialogmoteTexts.ts
- src/hooks/dialogmote/document/useDialogmoteDocumentComponents.ts
- src/hooks/dialogmote/document/useTidStedDocument.ts
- src/sider/mote/components/endre/EndreDialogmoteContainer.tsx
- src/sider/mote/components/endre/EndreDialogmoteSkjema.tsx
- src/utils/behandlerUtils.ts
- test/dialogmote/EndreDialogmoteSkjemaTest.tsx
- test/dialogmote/testDataDocuments.ts
Egne tekster for endre tid og sted på dialogmøteinnkalling.
Ett av brevene:
Endret også litt på tekst i radiogruppa, Peter ville ha en "nudging" der
> IS-2083: Add nynorsktekst for endre-tid-sted dialogmøte

- src/data/dialogmote/dialogmoteTexts.ts
- src/hooks/dialogmote/document/useAvlysningDocument.ts
- src/hooks/dialogmote/document/useDialogmoteDocumentComponents.ts
- src/hooks/dialogmote/document/useInnkallingDocument.ts
- src/hooks/dialogmote/document/useReferatDocument.ts
- src/hooks/dialogmote/document/useTidStedDocument.ts
- src/sider/mote/components/avlys/AvlysDialogmoteContainer.tsx
- src/sider/mote/components/avlys/AvlysDialogmoteSkjema.tsx
- test/dialogmote/AvlysDialogmoteSkjemaTest.tsx
- test/dialogmote/testDataDocuments.ts
Lagt inn nynorsktekster for avlysning. Ettersom dette var siste brevet som ble oversatt, så fikk vi fjernet litt målform-parametere som måtte bli sendt rundt, og heller håndterer dette globalt. Det er fortsatt noe som kunne blitt flyttet ut til hjelpefunksjoner, men som brukes på tvers av dialogmøte og aktivitetskrav. La inn noen TODOs, men kan godt fjerne det også 👍🏼
> IS-2099: Add nynorsk to avlysning dialogmøte

- src/data/arbeidsuforhet/forhandsvarsel84Texts.ts
- src/hooks/arbeidsuforhet/useArbeidsuforhetVarselDocument.ts
- src/routers/AppRouter.tsx
- src/sider/arbeidsuforhet/ArbeidsuforhetSide.tsx
- src/sider/arbeidsuforhet/SendForhandsvarselSkjema.tsx
Begynt på skjema for forhåndsvarsel, men uten funksjonalitet på knappene.
Tekstene er kopiert fra aktivitetskrav, så vi må legge inn de nye.
Lagt til en Side nå, vi må vurdere om vi ønsker både Container og Side etter hvert som det skal være mer enn bare et Skjema.
Vi vil vel ikke bruke 84 i navn på ting, men det kan fint endres etter hvert.
> IS-2100: Add forhandsvarsel84Skjema

- src/hooks/aktivitetskrav/useAktivitetskravVarselDocument.ts
- test/aktivitetskrav/varselDocuments.ts
- test/aktivitetskrav/vurdering/AktivitetskravForhandsvarselTest.tsx
- test/aktivitetskrav/vurdering/VurderAktivitetskravTest.tsx
- test/aktivitetskrav/vurdering/vurderingTestUtils.ts
Det fattes ikke vedtak når det vurderes `IKKE_AKTUELL` så her må standardteksten som journalføres med vurderingen tilpasses.
Ryddet samtidig litt i `VurderAktivitetskravTest`: Flyttet forhåndsvarsel-tester og felles testdata ut i egne filer.
> IS-2125: Tilpasser tekst som journalføres ved ikke-aktuell-vurdering

- src/components/VisBrev.tsx
- src/sider/aktivitetskrav/historikk/AktivitetskravHistorikk.tsx
- src/sider/aktivitetskrav/vurdering/ForhandsvarselOppsummering.tsx
- src/sider/arbeidsuforhet/ArbeidsuforhetSide.tsx
- src/sider/arbeidsuforhet/ForhandsvarselSendt.tsx
Mangler kobling til backend.
Nå er det lagt opp til bare en side for både "venter" og "passert frist". Mangler dato for frist til høyre for tittel.
Mangler ordentlig visning av brevet som faktisk ble sendt.
- Vi kan vurdere om vi vil ha to sider eller om det er best å bare endre innholdet på én side basert på hvorvidt fristen er passert eller ikke. Jeg tror kanskje bare én er greiest.
- Til forhåndsvisningen må vi vel bare hente fra backend, er det lagt opp til at DocumentComponents skal sendes med?
- ~Forhåndsvisning heter egentlig "Se sendt brev" i skissene, men det var enklest å bare bruke samme knapp som andre steder nå, selv om den har feil tekst.~ Nå bruker vi VarselBrev i stedet.
> IS-2121: Add page for sent forhandsvarsel

- src/components/utdragFraSykefravaeret/UtdragFraSykefravaeret.tsx
- src/utils/sykmeldinger/sykmeldingUtils.ts
- test/components/UtdragFraSykefravaeretTest.tsx
- test/utils/sykmeldingUtilsTest.ts
Se https://jira.adeo.no/browse/FAGSYSTEM-320013 og https://jira.adeo.no/browse/FAGSYSTEM-316186.
Når sykmeldt har flere arbeidsgivere, grupperes de inn på virksomhetsnummer. Innenfor hver virksomhet var sykmeldingene sortert, men ettersom det var en key-value mapping på virksomhetsnummer så ble rekkefølgen på sykmeldingene vilkårlig på tvers av arbeidsgivere, ettersom vi i dag ikke har noen visuell visning av grupperingen på arbeidsgiver.
Veilederne som har meldt inn saken har egentlig alle sykmeldinger tilgjengelig, men de lå lenger ned i lista ettersom en "gammel" arbeidsgiver endte opp øverst i sorteringen.
> IS-2119: Remove virksomhet-grouping for sykmeldinger

- src/sider/sykmeldinger/container/DinSykmeldingContainer.tsx
Fiks bug hvor knappen for å korrigere en sykmelding kun ble vist på ikke-papirsykmeldinger.
> IS-2150: Show korriger button when papirsykmelding

- mock/isarbeidsuforhet/arbeidsuforhetMock.ts
- mock/isarbeidsuforhet/mockIsarbeidsuforhet.ts
- src/data/arbeidsuforhet/useSendForhandsvarsel.ts
Fordi man bare mottar det opprettede forhåndsvarselet når man gjør et post-kall, funker det ikke å bare dytte det inn i queryData for arbeidsuførhet.
Da er det like greit å bare invalidere og hente data på nytt.
Før:
Etter:
> Invalidate arbeidsuforhet queries after mutate

- src/components/oppfolgingsoppgave/OppfolgingsoppgaveModal.tsx
- test/oppfolgingsoppgave/OppfolgingsoppgaveModalTest.tsx
- Legger til mulighet for å legge ved beskrivelse når oppfølgingsgrunn er `ANNET`
- Virker veldig overflødig med 2 alerts slik det ser ut nå, men er visst slik det må se ut foreløpig. Bekreftet at vi går for denne løsningen i første omgang med Stine og Peter.
https://github.com/navikt/syfomodiaperson/assets/11747383/76caaba8-bb94-41c5-b401-e2e8ccd85289
> IS-2126: Add possibility of beskrivelse to oppfolgingsgrunn ANNET

- src/sider/arbeidsuforhet/ForhandsvarseAfterDeadline.tsx
- src/sider/arbeidsuforhet/ForhandsvarselBeforeDeadline.tsx
- src/sider/arbeidsuforhet/ForhandsvarselSendt.tsx
- test/arbeidsuforhet/ForhandsvarselSendtTest.tsx
Det er nå en komponent for passert frist og en for ikke passert.
De har en del forskjeller, så da er det greit å slippe mange ifer.
Knappene er ikke helt i henhold til skissene, men det er en lapp på å fikse det.
Det mangler også queries som knappene kan bruke for å faktisk sende oppfylt/avslag til backend.
> IS-2171: Split sent forhandsvarsel page in two

- src/sider/arbeidsuforhet/SendForhandsvarselSkjema.tsx
Den er ikke i bruk i dag, og gir ikke noen verdi.
Den kan evt. legges på igjen senere hvis det er et ønske om å avbryte prosessen for å være sikker på at teksten er fjernet.
Før:
Etter:
> IS-2181: Remove Avbryt button from forhandsvarsel

- src/routers/AppRouter.tsx
- src/sider/arbeidsuforhet/ArbeidsuforhetOppfylt.tsx
- src/sider/arbeidsuforhet/ArbeidsuforhetOppfyltSide.tsx
- test/arbeidsuforhet/ArbeidsuforhetOppfyltTest.tsx
- test/arbeidsuforhet/arbeidsuforhetTestData.ts
Da blir det lettere å håndtere tilstanden på arbeidsuforhet-siden.
Klar til å legge til skjema for oppfylt, der det nå er placeholder.
Forhåndsvarsel:
Oppfylt:
Avslag:
> IS-2200: Add route for ArbeidsuforhetOppfyltSide

- mock/isarbeidsuforhet/mockIsarbeidsuforhet.ts
- src/sider/arbeidsuforhet/ArbeidsuforhetSide.tsx
- src/sider/arbeidsuforhet/ForhandsvarseAfterDeadline.tsx
- src/sider/arbeidsuforhet/ForhandsvarselBeforeDeadline.tsx
- test/arbeidsuforhet/ArbeidsuforhetForhandsvarselTest.tsx
- test/arbeidsuforhet/ForhandsvarselSendtTest.tsx
Vis spinner når henting av arbeidsuforhet laster, så vi ikke viser forhåndsvarselskjema en liten stund før vi bytter til en annen side. Fjern NotificationProvider som ikke er i bruk, fra test og ArbeidsuforhetSide.
Fjern litt ubrukte tekster.
Opprett varsel i lokal mock når det gjøres en forhåndsvarselvurdering.
<details>
<summary>Med og uten isLoading for å vise spinner:</summary>
Før:
https://github.com/navikt/syfomodiaperson/assets/40055758/434391d7-0d62-4d73-9079-c234e49f6146
Etter:
https://github.com/navikt/syfomodiaperson/assets/40055758/047db2da-cfcb-4920-9ef8-b47be7588a8c
</details>
> Do minor fixes in arbeidsuforhet code

- src/sider/arbeidsuforhet/Arbeidsuforhet.tsx
- src/sider/arbeidsuforhet/ArbeidsuforhetSide.tsx
- src/sider/arbeidsuforhet/AvslagSent.tsx
- src/sider/arbeidsuforhet/ForhandsvarseAfterDeadline.tsx
- test/arbeidsuforhet/ArbeidsuforhetTest.tsx
- test/arbeidsuforhet/ForhandsvarselSendtTest.tsx
Ved klikk på avslag-knappen, når fristen på forhåndsvarselet er utgått, send en avslag-vurdering til isarbeidsuforhet.
Når siste status på arbeidsuforhet er avslag, vises en side med de neste stegene i prosessen.
Siden for veien videre skal fjernes etter hvert, f.eks. ved ny sykmelding, men det er ikke implementert enda.
https://github.com/navikt/syfomodiaperson/assets/40055758/816a3f6b-68aa-47e6-90a1-add5f7603f9c
> IS-2214: Add functionality for 8-4-avslag

- src/data/oppfolgingstilfelle/person/oppfolgingstilfellePersonQueryHooks.ts
- src/utils/oppfolgingstilfelleUtils.ts
- test/utils/oppfolgingstilfelleUtilsTest.ts
Alle tilfeller med minst 3 dager, i stedet for 4, skal være med i beregningen.
Bruk antallSykedager i stedet for å bare beregne lengde fra start til slutt i tilfellet.
> IS-2219: Fix logic for gjentakende sykefravar

- src/data/arbeidsuforhet/useSendVurderingArbeidsuforhet.ts
Siden vi får den opprettede vurderingen i responsen fra POST-kallet kan vi oppdatere query direkte i stedet for å invalidere query og gjøre nytt GET-kall.
> Update arbeidsuforhet query from response

- src/components/flexjar/Flexjar.tsx
- src/hooks/useLocalStorageState.ts
- src/sider/Side.tsx
- test/flexjar/FlexjarTest.tsx
Fjerner fra aktivitetskrav, som vi ble enige om. 
Økte knappen til regular size, og så kan vi endre farge etterhvert tenker jeg. Alt av amplitude-greier burde bli riktig når vi filterer på URL/sidetittel. MEN noen skjær i sjøen ettersom siden kanskje etterhvert endrer navn, og `/oppfylt` er en egen route - må bare passe på dette i amplitude-målingene.
> IS-2217: Add flexjar for arbeidsuforhet and remove from aktivitetskrav

- mock/isarbeidsuforhet/arbeidsuforhetMock.ts
- src/components/VisBrev.tsx
- src/components/globalnavigasjon/GlobalNavigasjon.tsx
- src/data/arbeidsuforhet/forhandsvarselArbeidsuforhetTexts.ts
- src/hooks/arbeidsuforhet/useArbeidsuforhetVurderingDocument.ts
- src/routers/AppRouter.tsx
- src/sider/arbeidsuforhet/Arbeidsuforhet.tsx
- src/sider/arbeidsuforhet/ArbeidsuforhetOppfylt.tsx
- src/sider/arbeidsuforhet/ArbeidsuforhetOppfyltSide.tsx
- src/sider/arbeidsuforhet/ArbeidsuforhetSide.tsx
- src/sider/arbeidsuforhet/AvslagSent.tsx
- src/sider/arbeidsuforhet/ForhandsvarseAfterDeadline.tsx
- src/sider/arbeidsuforhet/ForhandsvarselBeforeDeadline.tsx
- src/sider/arbeidsuforhet/OppfyltForm.tsx
- src/sider/arbeidsuforhet/SendForhandsvarselSkjema.tsx
- src/sider/arbeidsuforhet/historikk/VurderingHistorikk.tsx
- test/arbeidsuforhet/ArbeidsuforhetForhandsvarselTest.tsx
- test/arbeidsuforhet/ArbeidsuforhetOppfyltTest.tsx
- test/arbeidsuforhet/ArbeidsuforhetTest.tsx
- test/arbeidsuforhet/ForhandsvarselSendtTest.tsx
- test/arbeidsuforhet/OppfyltFormTest.tsx
- test/arbeidsuforhet/documents.ts
- test/components/GlobalNavigasjonTest.tsx
Inkluderer også IS-2206 og IS-2229.
Har gjort en del tekstendringer etter prat med Stine, og kosmetiske styling-endringer slik at ting ser mer likt ut og bruker Aksel i større grad:
- Endret sidetittel og menypunkt fra `Forhåndsvarsel § 8-4` til `Arbeidsuførhet`
- Endret fra "Se sendt brev" til "Se sendt varsel" på knapp for å vise forhåndsvarselet man har sendt ut
- Lagt til en ny setning om friskmelding før fristen i forhåndsvarselbrevet
- Fjernet tittler på forhåndsvisingmodal, slik at det er mer likt som dialogmelding- og aktivitetskravmodalene
- Bruker [List](https://aksel.nav.no/komponenter/core/list) fra Aksel i stedet for ol, ul og li tags
- Tekstendringer i flere visninger (se bilder)
- Avbryt-knapp når man kommer til oppfylt-form
- Send-knapp på Oppfylt endres til Lagre
- …
> IS-2188: Update texts and styling for arbeidsuforhet-pages

- src/components/IconHeader.tsx
- src/components/Layout.tsx
- src/components/dialogmote/DeltakereSvarInfo.tsx
- src/sider/mote/components/DialogmotePanel.tsx
- src/sider/mote/components/innkalling/DialogmoteMoteStatusPanel.tsx
Disse knappene har irritert meg lenge, så tenkte jeg kunne oppgradere til Aksel-knapper. Innebærer også litt styling-endringer her og der, og fjerne bruk av styled-komponents og `FlexRow`. Tenker generelt at margin burde brukes for spacing der man dytter ting vekk utenfor elementet, ikke padding.
Hva er gjort:
- Flytta rekkefølge på knappene - håper det er greit å gjøre uten store konsekvenser.
- Nye knapper
- Dersom `Sted: ` hadde lang tekst, så flyttet den teksten under kalender-ikonet
- Bruker samme margin mellom alle elementer, og ikke padding til å skape space mellom ting
- Bytter ut eldre tekst-komponenter med Aksel-komponenter
Før:
Etter:
> IS-2237: Use aksel-buttons for dialogmøtestatus

- src/sider/arbeidsuforhet/AvslagSent.tsx
- test/arbeidsuforhet/ArbeidsuforhetTest.tsx
Vis alert i stedet for bare tekst, slik at det er tydelig at avslaget var vellykket.
Vis fortsatt informasjon om det neste veilederen må gjøre.
Før:
Etter:
> IS-2227: Show alert after arbeidsuforhet avslag

- src/context/notification/NotificationContext.tsx
- src/sider/arbeidsuforhet/Arbeidsuforhet.tsx
- src/sider/arbeidsuforhet/ArbeidsuforhetSide.tsx
- src/sider/arbeidsuforhet/ForhandsvarseAfterDeadline.tsx
- src/sider/arbeidsuforhet/NyVurdering.tsx
- src/sider/arbeidsuforhet/StartetVurdering.tsx
- test/arbeidsuforhet/ArbeidsuforhetTest.tsx
- test/arbeidsuforhet/ForhandsvarselSendtTest.tsx
Knappen sender veileder til skjemaet for forhåndsvarsel. Avslag-siden fjernes og erstattes med en alert over knappen, som blir borte når man beveger seg bort fra siden.
I tillegg til knappen viser vi når siste forhåndsvarsel og oppfylt/avslag ble sendt.
Endrer også testene til arbeidsuforhet, med assertions på at ting ikke vises, siden noen komponenter i teorien kan vises samtidig, men ikke skal det i praksis.
https://github.com/navikt/syfomodiaperson/assets/40055758/d8bc0b5c-f850-4578-b380-05b27d8758c6
> IS-2264: Add ny vurdering button to arbeidsuforhet

- src/routers/AppRouter.tsx
- src/sider/arbeidsuforhet/avslag/ArbeidsuforhetAvslag.tsx
- src/sider/arbeidsuforhet/avslag/ArbeidsuforhetAvslagSide.tsx
- test/arbeidsuforhet/avslag/ArbeidsuforhetAvslagTest.tsx
Vi bruker en egen route for dette, tilsvarende oppfylt, for å separere det fra skjema for forhåndsvarsel.
Det er ingenting som lenker til routen enda, men det skal legges inn på Avslag-knappen i `ForhandsvarselAfterDeadline`.
> IS-2293: Add page for arbeidsuforhet avslag

- mock/isfrisktilarbeid/mockIsfrisktilarbeid.ts
- src/sider/frisktilarbeid/FattVedtak.tsx
- src/sider/frisktilarbeid/FriskmeldingTilArbeidsformidlingSide.tsx
- src/sider/frisktilarbeid/VedtakDatoer.tsx
- test/frisktilarbeid/FattVedtakTest.tsx
Begynt på skjema for å fatte vedtak. Foreløpig bare med dato-inputs og begrunnelse.
Størrelsen på input-feltene er som i skissene foreløpig, selv om vi bruker `small` mange andre steder
> IS-2160: Fatt vedtak med datoer og begrunnelse

- src/data/arbeidsuforhet/arbeidsuforhetDocumentTexts.ts
- src/data/arbeidsuforhet/arbeidsuforhetTypes.ts
- src/hooks/arbeidsuforhet/useArbeidsuforhetVurderingDocument.ts
- src/sider/arbeidsuforhet/avslag/ArbeidsuforhetAvslag.tsx
- src/sider/arbeidsuforhet/avslag/AvslagDatePicker.tsx
- src/sider/arbeidsuforhet/avslag/AvslagForm.tsx
- test/arbeidsuforhet/avslag/ArbeidsuforhetAvslagTest.tsx
- test/arbeidsuforhet/avslag/AvslagFormTest.tsx
- test/arbeidsuforhet/documents.ts
Veileder trenger å kunne fylle ut dato og begrunnelse, og få det lagret i Joark, slik at de kan henvise til det senere i kommunikasjon med NAY. Etter hvert skal "avslag"-knappen sende veileder til dette skjemaet.
Det mangler også en bekreftelse til veileder på at avslaget er innsendt.
https://github.com/navikt/syfomodiaperson/assets/40055758/82ea2b0d-c423-41ab-b131-56f288af3af5
> IS-2293: Add form for 8-4-avslag

- src/sider/sykepengsoknader/soknad-felles-oppsummering/OppsummeringTall.tsx
Det er forvirrende når "eksempel 12" ser ut som en del av svaret til innbygger.
Derfor bruker vi nå kun svaret fra bruker i visningen, med "prosent/timer" bak, uavhengig av om undertekst finnes på spørsmålet.
<details>
<summary>Bilder</summary>
Før:
Etter: 
</details>
> IS-2289: Don't show question undertekst as user response in soknad

- src/sider/arbeidsuforhet/Arbeidsuforhet.tsx
- src/sider/historikk/Historikk.tsx
- src/sider/mote/components/DialogmotePanel.tsx
- src/sider/nokkelinformasjon/sykmeldingsgrad/Sykmeldingsgrad.tsx
- src/sider/sykepengsoknader/soknader/SoknaderTeasere.tsx
- src/sider/sykmeldinger/sykmeldinger/SykmeldingTeasere.tsx
- Setter standard margin mellom kort til `1 rem` (`16px`)
Eksempelvis siden for nøkkelinformasjon
Før
Etter
> IS-2261: Set standard vertical margins between cards

- src/components/Sidetopp.tsx
- Endrer sidetitler fra `xlarge` til `large` og flytter overskrift til venstre.
Før
Etter
> IS-2146: Endre storrelse pa page headings til large

- .npmrc
- README.md
- mock/ereg/virksomhetMock.ts
- mock/lps-oppfolgingsplan-mottak/oppfolgingsplanLPSMock.ts
- mock/lpsoppfolgingsplanmottak/mockLpsOppfolgingsplanMottak.ts
- package-lock.json
- package.json
- src/data/oppfolgingsplan/types/OppfolgingsplanLPS.ts
- src/sider/oppfolgingsplan/lps/OppfolgingsplanerOversiktLPS.tsx
- src/sider/oppfolgingsplan/oppfolgingsplaner/OppfolgingsplanerOversikt.tsx
- test/data/oppfolgingsplanQueryHooksTest.tsx
- test/oppfolgingsplaner/OppfolgingsplanerOversiktTest.tsx
- test/stubs/stubSyfooppfolgingsplan.ts
Jeg la merke til at LPS-planene ble sortert slik at de nyeste kom nederst. nav.no planene kommer øverst. De har altså ulik sortering i oversikten! Her bør nok nyeste planer alltid komme øverst, uavhengig av LPS eller ikke.
Ryddet i tillegg litt opp i typing/DTO som var feil, og noe smårusk.
> Change sorting of LPS plans

- mock/syfoperson/persondataMock.ts
- src/sider/frisktilarbeid/FattVedtak.tsx
- src/sider/frisktilarbeid/FattVedtakSkjema.tsx
- test/components/personkort/PersonkortHeaderTest.tsx
- test/data/maksdatoQueryTest.tsx
- test/frisktilarbeid/FattVedtakTest.tsx
- test/frisktilarbeid/FriskmeldingTilArbeidsformidlingTest.tsx
- test/testUtils.ts
- Beregner Tom-dato basert på maksdato dersom den er tidligere enn 12 uker
- Gir en warning hvis den går til maks
- Flyttet litt på tekster, blant annet ved å legge inn i Helptext (etter samtale med Peter)
Før:
Etter:
https://github.com/navikt/syfomodiaperson/assets/37441744/d2e89e93-2dc8-4874-8640-a5d68a674c64
> IS-2316: Set tom-date automatically to maksdato when maksdato is before 12 weeks

- mock/isaktivitetskrav/aktivitetskravMock.ts
- src/data/aktivitetskrav/forhandsvarselTexts.ts
- src/hooks/aktivitetskrav/useAktivitetskravVarselDocument.ts
- src/sider/aktivitetskrav/vurdering/SendForhandsvarselSkjema.tsx
- test/aktivitetskrav/varselDocuments.ts
- test/aktivitetskrav/vurdering/AktivitetskravForhandsvarselTest.tsx
Lagt til ny mal for NAV utland. Det besto av å legge til noen setninger her og der, og endre telefonnummer.
I tillegg var det en feil i brevet til de uten arbeidsgiver som vi får fikset her. 
La også til et avsnitt mellom `intro` og `stans`-tekstene, sånn at det kommer tydelig frem at vi vurderer å stanse sykepengene.
> IS-2077: Add mal for NAV utland in forhandsvarsel aktivitetskrav

- src/sider/nokkelinformasjon/sykmeldingsgrad/Sykmeldingsgrad.tsx
- src/utils/periodeUtils.ts
- src/utils/sykmeldinger/sykmeldingUtils.ts
To ting som var feil her:
1. Det var en fast lengde på grafen, så den var maks 55 uker. Jeg endret til enten 52 uker, eller så langt tilfellet varer.
2. I lista over sykmeldinger, så var det to stk med lik `fom` og `tom`, men ulik `grad`. Den ene ble sendt inn noen minutter etter den andre, men vi hadde ikke tatt høyde for `mottattTidspunkt` i sorteringen, så disse lå feil; den med 20% var skrevet over av den med 40% i grafen (riktig), men lå som nyest av de to i sykmeldingslista (feil).
Fra Jira-sak
Etterpå
Burde vi prøvd å pimpe denne litt mer, siden den er så populær? Feks bruke Timeline fra Aksel https://aksel.nav.no/komponenter/core/timeline#timeline-interndemo-pins
> IS-2340: Show whole graph when oppfolgingstilfelle bigger than one year

- src/sider/nokkelinformasjon/sykmeldingsgrad/Sykmeldingsgrad.tsx
Fikk `Cannot read properties of undefined (reading 'fom')` etter prodsetting, så håndterer at det kan være personer uten sykmeldinger.
> Fix sykmeldingsgrad when no aktiv sykmeldingsperiode

- src/components/dialogmote/DeltakereSvarInfo.tsx
Default open svar-expandable hvis det har kommet svar (uavhengig av om det er skrevet tekst eller ei).
Kunne også bare åpnet dersom det er skrevet noe, men hypotesen er at de uansett vil ekspandere for å sjekke om det står noe der. Her kunne man kanskje løst det med en visuell indikator på om det finnes tekst, men tenker det er enklest å bare begynne med å expande. 
Sjekket i databasen og lengste svar fra arbeidstaker og arbeidsgiver er på 300 tegn (input-begrensning). Fra behandler har vi noen outliers på flere tusen tegn, men de aller flest er under 1000 tegn. Tenker uansett det er greit å beholde muligheten til å collapse.
> IS-1896: Expand deltaker-svar if received svar

- mock/isdialogmote/dialogmoterMock.ts
- mock/isdialogmote/mockIsdialogmote.ts
- src/components/dialogmote/motehistorikk/MoteSvarHistorikk.tsx
- src/components/dialogmote/svar/ArbeidsgiverSvar.tsx
- src/components/dialogmote/svar/ArbeidstakerSvar.tsx
- src/components/dialogmote/svar/BehandlerSvar.tsx
- src/sider/dialogmoter/Motelandingsside.tsx
- test/data/dialogmoteQueryHooksTest.tsx
- test/dialogmote/InnkallingDialogmotePanelTest.tsx
- test/dialogmote/MoteSvarHistorikkTest.tsx
Lagt til panel med møtesvarhistorikk i tredelingen til høyre på dialogmøte-siden. Foreløpig vises kun svar på innkalling for hvert historiske møte, men skal være greit å utvide til å vise svar på evt endringer av tid/sted også.
Har også gjort litt forbedring av dialogmøte-mockdataene.
Gjenstår:
- Tester på komponenten.
- Endelig avklare design, tekster osv - tar gjerne innspill på det. Tanken er for enkelhets skyld å gjenbruke mest mulig av svar-visningen vi har for det aktive møtet.
> IS-1703: Dialogmøtesvar-historikk innkallinger

- src/sider/nokkelinformasjon/sykmeldingsgrad/SyketilfelleList.tsx
- src/utils/sykmeldinger/sykmeldingUtils.ts
- test/utils/sykmeldingUtilsTest.ts
Viser diagnosenavn i Tooltip ved hover, etter ønske på Yammer.
I dag er det sånn at det bare er siste diagnose for oppfølgingstilfellet, aka man kan ha hatt én diagnose i alle sykmeldingene i et oppfølgingstilfelle bortsett fra det siste, men da vil likevel den siste diagnosen "oppsummere" tilfellet.
> IS-2439: Add diagnosenavn tooltip

- src/data/dialogmote/dialogmoteTexts.ts
- test/dialogmote/dialogmoteTextsTest.ts
Legger til mulighet for å velge standardtekst om ekspertbistand i referatet. Se tilhørende PR med link i [dialogmote-frontend](https://github.com/navikt/dialogmote-frontend/pull/554)
Gjenstår:
> IS-2069: Add ekspertbistand standardtekst

- mock/syfosmregister/sykmeldingerMock.ts
- src/components/utdragFraSykefravaeret/Sykmeldinger.tsx
- src/components/utdragFraSykefravaeret/UtdragFraSykefravaeret.tsx
- test/components/UtdragFraSykefravaeretTest.tsx
Vi har kombinert alle sykemeldingene, både med og uten arbeidsgiver, og viser disse i kronologisk rekkefølge i "utdrag fra sykefraværet". De kortene uten arbeidsgiver har fått en tag med navn "uten arbeidsgiver".
> IS-1958: combine sykmeldinger with and without arbeidsgiver

- mock/isfrisktilarbeid/mockIsfrisktilarbeid.ts
- src/components/globalnavigasjon/GlobalNavigasjon.tsx
- src/styles/_antallNytt.less
- src/utils/globalNavigasjonUtils.ts
- test/components/GlobalNavigasjonTest.tsx
Nå vises en rød prikk hvis det er sendt inn vedtak som ikke er behandlet enda. Da kan veileder enkelt se at her er det noe ubehandlet Friskmelding til arbeidsformidling når de går inn på en person.
Verdt å legge merke til at når man har klikket seg gjennom sidene på FTA mange ganger lokalt (som jeg har gjort før innspillingen av videoen), så kommer man ikke til "Nytt vedtak"-siden fordi denne styres av en useState som aldri flippes tilbake til `false`. Tror ingen reelle caser vil komme hit dog, da må en veileder først ferdigbehandle et vedtak, så sende ut et nytt et med en gang, og ferdigbehandle det også på samme person. 
https://github.com/user-attachments/assets/41fa15db-11b6-469a-8f47-394075b69de7
> IS-2610: Add red notification dot when ubehandlet friskmelding til arbeidsformidling

- public/index.html
Fikser utdatert url slik at dekoratøren vises riktig lokalt og man får satt enhet i context
> Fix local decorator url

- src/sider/arbeidsuforhet/avslag/ArbeidsuforhetAvslag.tsx
Unngår at siden krasjer hvis man går til direkte til avslag-siden uten (via url) uten å ha sendt forhåndsvarsel.
> IS-2631: Fix avslag bug

- mock/syfooversiktsrv/mockSyfooversiktsrv.ts
- src/components/TildeltVeileder.tsx
- src/data/veilederbrukerknytning/useTildelVeileder.ts
Endrer til å bruke nytt [endepunkt](https://github.com/navikt/syfooversiktsrv/pull/427) for å registrere veilederknytning for enkeltperson.
Legger aktiv veilder øverst i lista med veiledere som kan velges.
> IS-2601: Use new endpoint, put aktivveilder first

- src/components/TildeltVeileder.tsx
`shouldAutocomplete` matchet bare starten av teksten (etternavn, fornavn) når man skriver i comboboxen - erstatter denne med `filteredOptions` som overrider søkelogikken slik at man får treff om man søker på deler av "etternavn, fornavn". Filtrerer ut veiledere uten fornavn og etternavn (antar det bare er et problem i dev)
> IS-2601: Improved filtering in tildel veileder

- mock/ismanglendemedvirkning/mockIsmanglendemedvirkning.ts
- src/routers/AppRouter.tsx
- src/sider/manglendemedvirkning/ManglendeMedvirkning.tsx
- src/sider/manglendemedvirkning/ManglendeMedvirkningButtons.tsx
- src/sider/manglendemedvirkning/ManglendeMedvirkningSide.tsx
- src/sider/manglendemedvirkning/forhandsvarsel/ForhandsvarselAfterDeadline.tsx
- src/sider/manglendemedvirkning/forhandsvarsel/ForhandsvarselBeforeDeadline.tsx
- src/sider/manglendemedvirkning/forhandsvarsel/ForhandsvarselSendt.tsx
- src/sider/manglendemedvirkning/forhandsvarsel/ForhandsvarselSkjema.tsx
- test/manglendemedvirkning/ManglendeMedvirkningTest.tsx
Egen side som sjekker om det er blitt sendt forhåndsvarsel, og i så fall viser sider for om fristen for varselet er utgått eller ikke. Har også satt opp routes for `/oppfylt`, `/stans` og `/ikkeaktuell` slik at man kan begynne på disse hvis man ønsker i parallell.
Gjort litt opprydninger her på styling og tekster basert på hvordan det så ut i arbeidsuførhet-sidene, som jeg tenker å endre der også i en egen PR. Avklares med Stine også.
Før frist:
Etter frist:
> IS-2620: Add page for sent forhandsvarsel

- src/sider/manglendemedvirkning/forhandsvarsel/ForhandsvarselAfterDeadline.tsx
- src/sider/manglendemedvirkning/forhandsvarsel/ForhandsvarselBeforeDeadline.tsx
- src/sider/manglendemedvirkning/forhandsvarsel/SupportingTextList.tsx
- test/manglendemedvirkning/ForhandsvarselTest.tsx
Lagt til støttetekst på knappene 'innstilling om stans', 'oppfylt', 'unntak' og 'ikke aktuell' i hovedbilde. 
Før forhåndsvarselet har gått ut:
Etter forhåndsvarselet har gått ut:
> IS-2698: Add støttetekst manglende medvirkning

- src/data/manglendemedvirkning/manglendeMedvirkningTypes.ts
- src/data/manglendemedvirkning/useSendVurderingManglendeMedvirkning.tsx
- src/hooks/manglendemedvirkning/useManglendeMedvirkningVurderingDocument.ts
- src/mocks/ismanglendemedvirkning/mockIsmanglendemedvirkning.ts
- src/sider/manglendemedvirkning/forhandsvarsel/ForhandsvarselSkjema.tsx
- src/sider/manglendemedvirkning/ikkeaktuell/IkkeAktuellSkjema.tsx
- src/sider/manglendemedvirkning/oppfylt/OppfyltSkjema.tsx
- src/sider/manglendemedvirkning/stans/StansSkjema.tsx
- src/sider/manglendemedvirkning/stans/StansdatoDatePicker.tsx
- src/sider/manglendemedvirkning/unntak/UnntakSkjema.tsx
- test/manglendemedvirkning/ForhandsvarselTest.tsx
- test/manglendemedvirkning/IkkeAktuellTest.tsx
- test/manglendemedvirkning/OppfyltTest.tsx
- test/manglendemedvirkning/StansTest.tsx
- test/manglendemedvirkning/UnntakTest.tsx
- test/manglendemedvirkning/vurderingDocuments.ts
Legger til felt for stansdato på innstillingen om stans som går til NAY.
Se [tilhørende PR i ismanglendemedvirkning](https://github.com/navikt/ismanglendemedvirkning/pull/35)
https://github.com/user-attachments/assets/0b311e40-d2cf-44b2-ae49-86963e2a78bc
> IS-2621: Add stansdato datepicker

- src/sider/senoppfolging/OvingssideLink.tsx
- src/sider/senoppfolging/SenOppfolging.tsx
- test/senoppfolging/SenOppfolgingTest.tsx
Lagt til link til esyfo sin demo av svarskjemaet. 
For å forstå tråden under lar jeg bare disse gamle screenshottene ligge litt lengre: 
Hjelpetekst:
> IS-2617: add demo link

- src/components/EksternLenke.tsx
- src/utils/amplitude.ts
Nå teller amplitude alle klikk på eksterne linker. Vi ønsker å se hvor mange som klikker på demo side linken, men la det til på alle eksterne linker samtidig.
> IS-2617: count demo link click amplitude

- src/data/senoppfolging/senOppfolgingTypes.ts
- src/data/senoppfolging/useSenOppfolgingSvarQuery.ts
- src/mocks/ismeroppfolging/mockIsmeroppfolging.ts
- src/sider/senoppfolging/KandidatFormResponse.tsx
- src/sider/senoppfolging/KandidatSvar.tsx
- src/sider/senoppfolging/SenOppfolging.tsx
- src/sider/senoppfolging/SenOppfolgingSide.tsx
- src/utils/globalNavigasjonUtils.ts
- test/components/GlobalNavigasjonTest.tsx
- test/senoppfolging/SenOppfolgingTest.tsx
Dette er for å bevare slik det er i prod i dag når vi begynner å konsumere varsler fra eSyfo. Da vil kandidater opprettes når vi får inn varsel, og vi vil lage oppgave når kandidaten har svart (eller det har gått 10 dager siden varsel). I apiet vi kaller her må vi derfor sjekke at kandidaten har svart i logikken som styrer rød prikk.
Siden vi nå får informasjon om kandidaten har svart via vårt api trenger vi ikke lenger laste spørsmål og svar fra esyfo sitt api ute i `SenOppfolgingSide`. Flyttet derfor denne lastingen inn i egen komponent med egen spinner og feilmelding dersom kallet feilet (slik at vi fortsatt kan vise resten av siden mens esyfo sitt api kalles).
Jobber videre med å vise rød prikk på at det har gått 10 dager siden varsel og vise når varsel ble sendt i komponenten
> IS-2687: Vise rød prikk når sen oppfolging-kandidat med svar

- src/sider/senoppfolging/KandidatIkkeSvart.tsx
- src/sider/senoppfolging/KandidatVarsel.tsx
- src/sider/senoppfolging/SenOppfolging.tsx
- src/utils/datoUtils.ts
- src/utils/globalNavigasjonUtils.ts
- test/components/GlobalNavigasjonTest.tsx
- test/senoppfolging/SenOppfolgingTest.tsx
Har også tilpasset logikk for rød prikk slik at denne vises når kandidat har svart eller det har gått minst ti dager siden varsel.
Dette er som i skissene, men tenker at vi kanskje burde legge til noe mer tekst her etter hvert, f.eks. noe om at det kommer oppgave i oversikten når den sykmeldte svarer eller de ikke har svart på ti dager...
> IS-2687: Viser info om varsel når kandidat er varslet og ikke svart

- src/components/utdragFraSykefravaeret/UtdragOppfolgingsplaner.tsx
- src/sider/dialogmoter/Motelandingsside.tsx
- src/sider/nokkelinformasjon/Nokkelinformasjon.tsx
Siden mesteparten av innholdet i Utdrag fra sykefraværet kan vises uten at oppfølgingsplaner er lastet endrer vi slik at Utdrag fra sykefraværet rendres før oppfølgingsplaner er lastet ferdig. 
Viser spinner og evt feilmelding for lasting av oppfølgingsplaner i `UtdragOppfolgingsplaner`
> IS-2712: Do not wait for oppfolgingsplaner to load

- src/sider/senoppfolging/KandidatIkkeSvart.tsx
- src/sider/senoppfolging/SenOppfolging.tsx
- src/utils/senOppfolgingUtils.ts
- test/senoppfolging/SenOppfolgingTest.tsx
Viser samme vurdering-skjema som ved svar dersom den sykmeldte ikke har svart på 10 dager.
I tillegg laget ulike varianter av teksten i boksen over avhengig av om varsel-svarfristen er utløpt eller ikke.
> IS-2688: Vis vurdering-skjema hvis varsel ikke besvart på 10 dager

- test/dialogmote/AvlysDialogmoteSkjemaTest.tsx
- test/dialogmote/DialogmoteInnkallingSkjema/BehandlerInnkallingTest.tsx
- test/dialogmote/DialogmoteInnkallingSkjema/DialogmoteInnkallingPreviewTest.tsx
- test/dialogmote/DialogmoteInnkallingSkjema/DialogmoteInnkallingSkjemaTest.tsx
- test/dialogmote/EndreDialogmoteSkjemaTest.tsx
- test/dialogmote/ReferatEndreTest.tsx
- test/dialogmote/ReferatMellomlagreTest.tsx
- test/dialogmote/ReferatTest.tsx
- test/dialogmote/testDataDocuments.ts
Prøver å minimere potensielle timing-problemer i testene ved å sende inn forventet sendt-tidspunkt til test-dokumentene i stedet for at dette genereres der man gjør assertion.
> Robustify tests

- src/sider/senoppfolging/NewVurderingForm.tsx
- test/senoppfolging/SenOppfolgingTest.tsx
Endret teksten i beskrivelsen av begrunnelsesfeltet i sen fase
**Før:**
**Nå:**
> IS-2750: change text sen fase

- src/sider/dialogmoter/Motelandingsside.tsx
- src/sider/dialogmoter/components/motehistorikk/ForhandsvisDocumentAccordionItem.tsx
- src/sider/dialogmoter/components/motehistorikk/MoteHistorikkEvent.tsx
- src/sider/dialogmoter/components/motehistorikk/MoteHistorikkUnntak.tsx
- src/sider/dialogmoter/components/motehistorikk/MoteSvarHistorikk.tsx
- src/sider/dialogmoter/components/motehistorikk/MoteSvarHistorikkEvent.tsx
- src/sider/dialogmoter/components/motehistorikk/MotehistorikkPanel.tsx
- Legger til visning for når man ikke har noen historiske møter å vise
- Splittet også ut en del lengre filer i egne komponenter
Før
Se [vedlegg i PR](https://trello.com/c/6HFdx6nx/2573-viser-ikke-tredjekolonne-p%C3%A5-dialogm%C3%B8ter-side)
Etter
> IS-2573: Add view when no historic meetings

- src/data/historikk/historikkQueryHooks.ts
- src/data/historikk/types/historikkTypes.ts
- src/hooks/historikk/useHistorikk.ts
- src/hooks/historikk/useOppfolgingsplanHistorikk.ts
- src/mocks/lps-oppfolgingsplan-mottak/oppfolgingsplanLPSMock.ts
- src/sider/historikk/Historikk.tsx
- test/historikk/HistorikkTest.tsx
Henter alle lps-oppfolgingsplaner og legger til i historikken ("interne" oppfolgingsplaner har vi allerede historikk på)
Ref denne tråden: https://nav-it.slack.com/archives/CGX6MF9S8/p1730811357036099
> IS-2739: Add lps-planer to oppfolgingsplan-historikk

- src/sider/sykepengsoknader/soknad-felles-oppsummering/OppsummeringSporsmal.tsx
Relatert til https://github.com/navikt/syfomodiaperson/pull/1420. Har avklart med @olebaba at det ikke gir mening å vise 
`OppsummeringBekreftelsespunkter` for denne svartypen da den ikke vil ha noen spørsmålstekst eller svar med verdier som kan vises. (for denne typen vil man bare ett svar som har verdien "true" dersom  brukeren har åpnet oppsummeringen) i søknaden.
Før:
Nå:
> IS-2796: Skal ikke vise OppsummeringBekreftelsespunkter for svarType OPPSUMMERING

- src/data/historikk/types/historikkTypes.ts
- src/data/oppfolgingsoppgave/types.ts
- src/data/oppfolgingsoppgave/useGetOppfolgingsoppgaver.tsx
- src/hooks/historikk/useHistorikk.ts
- src/hooks/historikk/useOppfolgingsoppgaveHistorikk.ts
- src/mocks/oppfolgingsoppgave/historikkOppfolgingsoppgaveMock.ts
- src/mocks/oppfolgingsoppgave/mockOppfolgingsoppgave.tsx
- src/sider/historikk/Historikk.tsx
- test/historikk/HistorikkTest.tsx
Har lagt til oppfølgingsoppgaver i historikken. Det er tatt i bruk nytt endepunkt med ny struktur.
Litt usikker på om testene burde teste noe som har med expandable om det i det hele tatt er mulig. Litt usikker på hvilke muligheter vi har med det vi bruker og så er det litt hva som gir mening/verdi.
Jeg tenker det gir mening å ta refaktorering av aktiv oppfølgingsoppgave som en egen PR.
Denne er avhengig av: https://github.com/navikt/ishuskelapp/pull/83
> IS-2460 Lagt til oppfølgingsoppgave i historikken

- src/hooks/historikk/useAktivitetskravHistorikk.ts
- src/sider/aktivitetskrav/historikk/AktivitetskravHistorikk.tsx
- src/sider/historikk/Historikk.tsx
- test/historikk/HistorikkTest.tsx
Vi landet ikke på så mange endringer, men endret litt på tekstene slik at det ikke står "Det ble vurdert IKKE_AKTUELT" på aktivitetskrav, samt fikset noen av de lengste tagsene som fikk rar formatering på liten skjerm. Beholder ting i "vanlig størrelse" foreløpig, og så kan vi heller ta small når vi får konkrete tilbakemeldinger på ting. 
Se på "Snart slutt på sykepengene" tagsene.
Før:
Etter:
> IS-2769: Refactor historikk-page with design changes

- src/components/oppfolgingsoppgave/Oppfolgingsoppgave.tsx
- src/components/oppfolgingsoppgave/OppfolgingsoppgaveModal.tsx
- src/data/oppfolgingsoppgave/types.ts
- src/data/oppfolgingsoppgave/useAktivOppfolgingsoppgave.tsx
- src/data/oppfolgingsoppgave/useCreateOppfolgingsoppgave.tsx
- src/data/oppfolgingsoppgave/useEditOppfolgingsoppgave.tsx
- src/data/oppfolgingsoppgave/useOppfolgingsoppgaver.tsx
- src/data/oppfolgingsoppgave/useRemoveOppfolgingsoppgave.tsx
- src/hooks/historikk/useOppfolgingsoppgaveHistorikk.ts
- src/mocks/oppfolgingsoppgave/historikkOppfolgingsoppgaveMock.ts
- src/mocks/oppfolgingsoppgave/mockOppfolgingsoppgave.tsx
- test/historikk/HistorikkTest.tsx
- test/oppfolgingsoppgave/OppfolgingsoppgaveModalTest.tsx
- test/stubs/stubIshuskelapp.ts
Denne bygger videre på tidligere [PR](https://github.com/navikt/syfomodiaperson/pull/1545) og tar for seg avvikling av tidligere datamodell for aktiv oppfølgingsoppgave. APIet leverer nå oppfølgingsoppgave som har flere versjoner hvorav siste versjon ligger først i lista.
Har i tillegg fikset slik at mock for oppfølgingsoppgave fungerer, mao. er det nå mulig å opprette, endre og slette oppfølgingsoppgaven og det vil også resultere i at historikken får nye forekomster.
> IS-2460: Refaktorert slik at oppfølgingsoppgave bruker ny datamodell

- src/components/ImportantInformationIcon.tsx
- src/components/utdragFraSykefravaeret/Sykmeldinger.tsx
- src/sider/sykmeldinger/sykmeldinger/SykmeldingLinkPanel.tsx
- src/sider/sykmeldinger/sykmeldinger/SykmeldingTeasere.tsx
- Legger til ikon for å vise at sykmelding på sykmeldinger siden inneholder "viktig informasjon", slik de er vandt til i `UtdragFraSykefravaeret` komponenten.
> IS-2852: Show viktig informasjon ikon on sykmelding

- src/data/aktivitetskrav/aktivitetskravQueryHooks.ts
- src/data/dialogmotekandidat/dialogmotekandidatQueryHooks.ts
- src/data/senoppfolging/useSenOppfolgingKandidatQuery.ts
Vi har tilfeller av `ConflictException` ved vurdering av aktivitetskrav/sen oppfolging-kandidat/dialogmøte-unntak. Hypotesen er at dette skjer pga to veiledere som er inne på en bruker samtidig og gjør vurdering etter hverandre uten at data er oppdatert i frontend.
Reduserer `staleTime` på relevante queries slik at disse regnes som gamle etter 5min og blir refetchet når man går inn på siden for å gjøre vurdering. Setter i tillegg `refetchOnWindowFocus: true` slik at data refetches om man har vurdering-siden åpen og data er gamle.
Ref https://blogg.bekk.no/jeg-har-misforst%C3%A5tt-tanstack-querys-cachetime-og-det-har-nok-du-ogs%C3%A5-f6594bc1b5dd og https://tanstack.com/query/v4/docs/framework/react/guides/window-focus-refetching
> IS-2848: Decrease stale time and refetch on window focus for some queries

- src/components/oppfolgingsoppgave/Oppfolgingsoppgave.tsx
- src/data/oppfolgingsoppgave/types.ts
- src/mocks/oppfolgingsoppgave/historikkOppfolgingsoppgaveMock.ts
- src/mocks/oppfolgingsoppgave/mockOppfolgingsoppgave.tsx
- test/oppfolgingsoppgave/OppfolgingsoppgaveModalTest.tsx
Kom inn tilbakemelding på Viva Engage om at veilederen som lagde oppgaven ikke vises lenger.
Etter endringer i DTOen her, så får vi ikke `createdBy` på hovedobjektet, men inne i versjonen. 
I dev så det bare sånn ut:
Nå:
> IS-2898: Use correct field for createdBy in oppfolgingsoppgave

- src/components/ImportantInformationIcon.tsx
- src/components/utdragFraSykefravaeret/Sykmeldinger.tsx
- Lagt til tooltip på de tre prikkene som indikerer at det finnes viktig info i sykmeldingen. 
Utdrag fra sykmeldingen
Sykmeldingene på sykmeldingsiden
> IS-2890: Add tooltip om viktig info i sykmeldingen

- src/data/motebehov/types/motebehovTypes.ts
- src/hooks/historikk/useHistorikk.ts
- src/hooks/historikk/useMotebehovHistorikk.ts
- src/mocks/syfomotebehov/historikkmotebehovMock.ts
- src/mocks/syfomotebehov/motebehovMock.ts
- src/sider/dialogmoter/Motelandingsside.tsx
- src/sider/dialogmoter/motebehov/DialogmoteOnskePanel.tsx
- src/sider/dialogmoter/motebehov/MotebehovKvittering.tsx
- src/utils/motebehovUtils.ts
- test/historikk/HistorikkTest.tsx
Har gjort følgende:
- Laget en ny intern modell for møtebehov som skiller på meldt møtebehov (de ønsker møte) og svar på møtebehov (de blir bedt om å svare på møtebehov ved uke 17 dialogmøtekandidat). Den mapper blant annet om en del verdier som bare finnes i ett av tilfellene, og deduserer noen felter basert på ting som kommer i DTOen.
- Fjerner bruk av /historikk-endepunktet hos esyfo, slik at vi bare kan forholde oss til en liste av møtebehov og heller mappe om denne til tekst slik vi ønsker det.
- Behandling av en møtebehov-oppgave skjer ved at feltene `behandletTidspunkt` og `behandletVeilederIdent` er fylt ut på samme entry i lista. Derfor går man gjennom lista to ganger og legger til behandlinger som en egen rad i historikken, der tidspunktet er tidspunktet for behandling og ikke …
> IS-2019: Add motebehov historikk with svar

- src/components/ImportantInformationIcon.tsx
- src/components/utdragFraSykefravaeret/Sykmeldinger.tsx
Reverserer [denne PRen](https://github.com/navikt/syfomodiaperson/pull/1572) fordi tooltipen om viktig info i sykmeldingen innskrenket muligheten til å trykke seg inn på kortet. Uten tooltipen kan man trykke hvor som helst på sykmeldingskortet, som gjør det lett å navigere seg mellom mange sykmeldinger spesielt på store skjermer. 
<details> 
<summary>Dette er sykmeldingskortet med de tre prikkene: </summary>
</details>
> IS-2912: remove tooltip on sykmelding

- src/components/personkort/PersonkortHeader/PersonkortHeaderTags.tsx
- test/components/personkort/PersonkortHeaderTest.tsx
~Trenger innspill på tekst her.~ Teksten vokste på Stine 🤌🏼
Viser altså en Tag når `tom`-dato er fremover i tid.
Blå tag ettersom det ikke er en warning. "Under arbeidsrettet oppfølging" burde nok også vært det, men gjør ikke endringer der i denne PRen. Tenker egt at kode 6/7 tagene burde vært røde også 🤷🏼‍♂️
> IS-2876: Show 8-5 tag when active vedtak

- src/components/personkort/Personkort.tsx
- src/components/personkort/PersonkortInformasjon.tsx
- src/components/personkort/PersonkortLege.tsx
- src/components/personkort/PersonkortSykmeldt.tsx
- src/components/personkort/ledere/PersonKortVirksomhetLedere.tsx
- src/utils/stringUtils.ts
- test/utils/stringUtilsTest.ts
- Endrer visning av telefon nummere til et leselig format. 
- Håndterer både nummere som er på formatet 12345678 og +4712345678. Disse blir 12 34 56 78 og +47 12 3 56 78.
- Følger [språkrådets anbefalinger rundt visning av telefon nummere](https://arc.net/l/quote/aygjlewf)
Før
https://github.com/user-attachments/assets/a40804c9-4d28-4649-b9b7-8f9ed038e3c8
Etter
https://github.com/user-attachments/assets/16029146-9e84-401a-a388-3ee9e2c39b15
> IS-2907: Display phone numbers on readable format

- src/sider/dialogmoter/components/motehistorikk/MoteSvarHistorikk.tsx
- src/sider/dialogmoter/components/motehistorikk/MoteSvarHistorikkEndringer.tsx
- src/sider/dialogmoter/components/motehistorikk/MoteSvarHistorikkEvent.tsx
- src/sider/dialogmoter/components/motehistorikk/MoteSvarHistorikkInnkalling.tsx
- test/dialogmote/MoteSvarHistorikkTest.tsx
Lagt til arbeidstakers/arbeidsgivers/behandlers svar på utsendt endring av tid/sted for dialogmøte. I teorien kan endring av tid/sted skje flere ganger og kan svares på hver gang. Lagt alle disse kronologisk under svar på innkallingen vi har i møtesvar-historikken.
> IS-2427: Add svar på endringer (nytt tid/sted) to motesvarhistorikk

- src/data/dialogmote/dialogmoteTexts.ts
- src/hooks/dialogmote/document/useDialogmoteDocumentComponents.ts
- test/dialogmote/testDataDocuments.ts
Lagt til setning med lenke til info om videomøte dersom lenke til videomøte er angitt. Bruker samme stil på denne som vi har i andre brev hvor vi lenker til relevant info på nav.no (dvs ingen lenke-styling - dels fordi vi ikke har støtte for det ut av boksen med DocumentComponent og dels fordi brevet kan gå fysisk)
> IS-2753: Lagt til info om videmøte-link

- src/components/oppfolgingsoppgave/Oppfolgingsoppgave.tsx
- src/sider/historikk/Historikk.tsx
- src/styles/_utils.less
Tekst som inneholder linjeskift vil nå brekke riktig i både visningen til venstre under menyen og i historikk. Det er en god del forskjellige måter dette kan løses på, så er bare si ifra om det er en annen foretrukket måte å gjøre dette på.
> IS-2995 Endret slik at visning av oppfølgingsoppgaveteksten tar hensyn til whitespace

- src/data/oppfolgingsoppgave/useOppfolgingsoppgaver.tsx
- src/mocks/oppfolgingsoppgave/mockOppfolgingsoppgave.tsx
Opprydding ifm. refaktorering av versjoner for oppfølgingsoppgaver. Fjernet bruk av request parameteren `filter` ettersom den ble fjernet i en tidligere [PR i ishuskelapp](https://github.com/navikt/ishuskelapp/pull/86/files#diff-48d50921c431f269f80d373e17706563e77f93e1771513e3f1c9ef431ad7394eL34)
> IS-2460: Fjernet bruk av request parameter som ikke lenger finnes i apiet

- src/sider/dialogmoter/components/referat/Referat.tsx
Fikser bug som gjorde at dersom veileder endret navn på nærmeste leder i dialogmøtereferat og lagret dette så ble det overskrevet med faktisk navn på nærmeste leder fra `isnarmesteleder` når man senere skulle fortsette på det lagrede referatet.
> IS-2899: Correct initial values for narmeste leder

- src/components/personkort/PersonkortSykmeldt.tsx
- src/data/navbruker/navbrukerQueryHooks.ts
- src/data/navbruker/types/BrukerinfoDTO.ts
- src/mocks/syfoperson/mockSyfoperson.ts
- src/mocks/syfoperson/persondataMock.ts
- src/sider/dialogmoter/components/DialogmoteSideContainer.tsx
- src/sider/dialogmoter/components/endre/EndreDialogmoteContainer.tsx
- src/sider/dialogmoter/components/innkalling/DialogmoteInnkallingContainer.tsx
- src/sider/dialogmoter/components/innkalling/DialogmoteInnkallingSkjema.tsx
- src/sider/dialogmoter/components/innkalling/InnkallingDialogmotePanel.tsx
- test/components/personkort/PersonkortHeaderTest.tsx
- test/components/personkort/PersonkortTest.tsx
- test/components/personkort/PersonkortVisningTest.tsx
- test/containers/MotelandingssideContainerTest.tsx
- test/containers/SykepengesoknadSideTest.tsx
- test/dialogmote/DialogmoteInnkallingSkjema/DialogmoteInnkallingSkjemaTest.tsx
- test/dialogmote/InnkallingDialogmotePanelTest.tsx
- test/testQueryClient.ts
Bruker `/kontaktinformasjon`-endpunkt i syfoperson for å hente info fra KRR. 
Fjerner samtidig bruk av kontaktinfo fra responsen til brukerinfo-kallet. Etterpå kan vi fjerne henting av kontaktinfo fra KRR i `/brukerinfo`-endepunket i syfoperson.
> IS-2897: Use kontaktinformasjon api for kontaktinfo

- src/components/dialogmoteunntak/DialogmoteunntakSkjema.tsx
- src/data/dialogmotekandidat/types/dialogmoteikkeaktuellTypes.ts
- src/data/dialogmotekandidat/types/dialogmoteunntakTypes.ts
- src/mocks/isdialogmotekandidat/dialogmoteunntakMock.ts
- src/sider/dialogmoter/components/ikkeaktuell/DialogmoteIkkeAktuellSkjema.tsx
- src/sider/dialogmoter/components/motehistorikk/MoteHistorikkUnntak.tsx
- test/dialogmoteikkeaktuell/DialogmoteikkeaktuellSkjemaTest.tsx
- test/dialogmoteunntak/DialogmoteunntakSkjemaTest.tsx
Flytter årsakene "friskmeldt" og "arbeidsforhold opphørt" fra unntak til ikke aktuell. Årsakene må fortsatt ligge der for å kunne vise historiske unntak.
Unntak nå:
Ikke aktuell nå:
> IS-2884: Move unntak-arsaker to ikke-aktuell

- src/data/personoppgave/types/PersonOppgave.ts
- src/mocks/ispersonoppgave/personoppgaveMock.ts
- src/sider/sykmeldinger/VurderBistandsbehov.tsx
- test/sider/oppfolgingsplaner/OppfolgingsplanerOversiktTest.tsx
- test/sykmeldinger/VurderBistandsbehovTest.tsx
Markerer behandler-ber-om-bistand-oppgaver fra sykmeldinger som duplikate hvis samme tekst har kommet i en tidligere sykmelding.
> Sykmelding bistand duplikat

- src/components/TildeltVeileder.tsx
- src/data/veilederinfo/types/Veileder.ts
- src/data/veilederinfo/veilederinfoQueryHooks.ts
- src/mocks/common/mockConstants.ts
- test/components/TildeltVeilederTest.tsx
Viser bare veiledere med `enabled=true` (dvs at de finnes og ikke er deaktivert i MS Graph) når man skal tildele person til veileder.
> IS-2260: Filter enabled veileder

- src/components/LabelAndText.tsx
- src/sider/oppfolgingsplan/oppfolgingsplaner/BeOmOppfolgingsplan.tsx
- test/sider/oppfolgingsplaner/OppfolgingsplanerOversiktTest.tsx
Lagt til forhåndsvisning via `ReadMore` og lagt til nye tekster. Noen stylingendringer også.
Lagde en `LabelAndText` på utils-nivå, fordi vi har flere steder der vi har lignende logikk (`Info` i personkortet og `SyketilfelleSummaryElement` i utdraget fra sykefraværet). Implementerte ikke bruken av denne komponenten flere steder, fordi det er noen ting som er litt annerledes. Feks at det er **label:** text og label: **text** ulike steder, og at fontstørrelser er satt av en global less-styling 😢
> IS-3011: Add preview of email for oppfølgingsplan forespørsel

- src/components/pengestopp/PengestoppHistorikk.tsx
- src/components/pengestopp/PengestoppModal.tsx
- src/data/pengestopp/types/FlaggPerson.ts
- src/data/pengestopp/useFlaggPerson.ts
- src/mocks/ispengestopp/mockIspengestopp.ts
- src/mocks/ispengestopp/pengestoppStatusMock.ts
- src/utils/pengestoppUtils.ts
- test/pengestopp/PengestoppTest.tsx
Skrevet om `PengestoppModal` til å bruke `react-hook-form` for å forenkle skjemakoden og gjøre det mer likt andre skjemaer. 
I tillegg ryddet litt i årsaks-kodene slik at det er tydeligere hvilke som er i bruk og hvilke som finnes bare for historikk.
Funksjonaliteten skal være uendret :crossed_fingers:
> Pengestopp improvements and refactor

- src/data/virksomhet/virksomhetQueryHooks.ts
- src/mocks/common/mockConstants.ts
- src/mocks/isoppfolgingstilfelle/oppfolgingstilfellePersonMock.ts
- src/sider/oppfolgingsplan/oppfolgingsplaner/AktiveOppfolgingsplaner.tsx
- src/sider/oppfolgingsplan/oppfolgingsplaner/BeOmOppfolgingsplan.tsx
- test/sider/oppfolgingsplaner/BeOmOppfolgingsplanTest.tsx
- test/sider/oppfolgingsplaner/OppfolgingsplanerOversiktTest.tsx
Legger til valg av arbeidsgiver når det er flere aktive nærmeste ledere for det aktive oppfølgingstilfellet.
Når det bare er én nærmeste leder blir det som før, dvs valget vises ikke:
Dersom det er flere vises radio-knapper med validering:
Tanker? Burde vi f.eks vise radio-knapp uansett om det er én eller flere?
TODO
> IS-3073: Be om oppfølgingsplan ved flere arbeidsgivere

- src/components/oppfolgingsoppgave/OppfolgingsoppgaveModal.tsx
- src/sider/aktivitetskrav/vurdering/AvventFristDato.tsx
- lagt til ukenummer på datepicker til oppfølgingsoppgave og avvent aktivitetskrav
Oppfølgingsoppgave:
Før:
Etter:
Avvent aktivitetskrav:
Før:
Etter:
> IS-3091: add week number on datepicker oppfolgingsoppgave and avvent aktivitetskrav

- src/mocks/syfomotebehov/motebehovMock.ts
- src/sider/dialogmoter/Motelandingsside.tsx
- src/sider/dialogmoter/motebehov/DialogmoteOnskePanel.tsx
- src/sider/dialogmoter/motebehov/MotebehovKvittering.tsx
- src/sider/dialogmoter/motebehov/MotebehovKvitteringInnhold.tsx
- src/sider/oppfolgingsplan/oppfolgingsplaner/AktiveOppfolgingsplaner.tsx
- src/utils/motebehovUtils.ts
- test/containers/MotelandingssideContainerTest.tsx
- test/dialogmote/Motebehov/MotebehovKvitteringTest.tsx
- test/dialogmote/MotebehovHistorikkTest.tsx
Endret visningslogikk for møtebehovpanelet på dialogmøtesiden. 
- Konsekvent skille på meldt behov og svar behov, dermed fikset slik at det:
- Vises svar fra arbeidsgiver og arbeidstaker i aktivt oppfølgingstilfelle, også hvis en av de ikke har svart
- Vises meldt behov fra arbeidsgiver og arbeidstaker i aktivt oppfølgingstilfelle, også hvis en av de ikke har meldt behov
- Endret visningslogikk for motebehov i tilfelle slik at det: 
- Viser ikke behandlet behov utenfor tilfelle
<details> <summary> Foreløpig utseende: </summary>
Meldt behov innenfor tilfelle:
Svart behov innenfor tilfelle: 
Ubehandlet behov utenfor tilfelle:
Behandlet behov utenfor tilfelle:
Ingen tidligere møtebehov:
</details>
> IS-3061: Fix visning av møtebehov

- src/data/historikk/types/historikkTypes.ts
- src/hooks/historikk/useAktivitetskravHistorikk.ts
- src/hooks/historikk/useArbeidsuforhetHistorikk.ts
- src/hooks/historikk/useDialogmoteStatusEndringHistorikk.ts
- src/hooks/historikk/useDialogmotekandidatHistorikk.ts
- src/hooks/historikk/useFriskmeldingTilArbeidsformidligVedtakHistorikk.ts
- src/hooks/historikk/useHistorikk.ts
- src/hooks/historikk/useLedereHistorikk.ts
- src/hooks/historikk/useManglendeMedvirkningHistorikk.ts
- src/hooks/historikk/useMotebehovHistorikk.ts
- src/hooks/historikk/useOppfolgingsoppgaveHistorikk.ts
- src/hooks/historikk/useOppfolgingsplanHistorikk.ts
- src/hooks/historikk/useSenOppfolgingHistorikk.ts
- src/hooks/historikk/useVeilederTildelingHistorikk.ts
- src/mocks/common/mockConstants.ts
- src/mocks/isoppfolgingsplan/oppfolgingsplanForesporselMocks.ts
- src/sider/historikk/Historikk.tsx
- src/sider/historikk/container/HistorikkContainer.tsx
- test/historikk/HistorikkTest.tsx
Lagt til forespørsler om oppfølgingsplan i på Historikk-siden.
Forenklet sjekk på `isLoading` / `isError` i `useHistorikk` og refaktorerte/forenklet historikk-hooks slik at alle returnerer `HistorikkHook` i stedet for sine egne "duplikate" typer.
> IS-3087: Forespørsel om oppfølgingsplan i Historikk

- src/components/LinkAsTab.tsx
- src/components/TildeltVeileder.tsx
- src/components/personkort/OversiktLenker.tsx
- src/sider/Side.tsx
Endret slik at menyen ser lik ut det som er i syfooversikt og endret rekkefølgen slik at søk er sist
Relatert PR: https://github.com/navikt/syfooversikt/pull/604
Før:
Etter:
> IS-3097: Endret slik at menyen ser lik ut det som er i syfooversikt

- src/components/ExpansionCardFormField.tsx
- src/sider/dialogmoter/components/referat/DeltakerArbeidsgiverHeading.tsx
- src/sider/dialogmoter/components/referat/DeltakerArbeidstakerHeading.tsx
- src/sider/dialogmoter/components/referat/DeltakerBehandlerHeading.tsx
- src/sider/dialogmoter/components/referat/DeltakerNavHeading.tsx
- src/sider/dialogmoter/components/referat/Referat.tsx
- Endret teksten på warning om sensitiv informasjon i referatet slik at rutinene for dokumentasjon av sensitiv informasjon kommer tydelig frem. Denne dokumentasjonen gjøres foreløpig andre steder, som feks i personoversikten, aktivitetsplanen eller gosys. Veiledere bruker arena, men dette er feil.  
- Endret linken til en mer generell link om rutiner for dialogen i Modia, Min side og Gosys, som vi antar er vanskeligere å finne for veileder. Den forrige linken var en mer intern side om dialogmøter på navet under sykefraværsoppfølging. 
- Byttet fra warning til vanlig tekst siden dette er noe som alltid skal stå der. 
- Fjernet den info boksen helt øverst, fordi den stjal litt oppmerksomhet og teksten er ifølge Stine selvforklarende og unødvendig. 
- Også gjort noen finjusteringer på …
> IS-3035: add text om rutiner for sensitiv info i dialogmøtereferat

- src/components/InaktivPersonident.tsx
- src/data/modiacontext/usePostAktivBruker.ts
- src/data/navbruker/navbrukerQueryHooks.ts
- src/data/navbruker/types/BrukerinfoDTO.ts
- src/mocks/syfoperson/persondataMock.ts
- src/sider/Side.tsx
Viser error alert og modal dersom man åpner en person som har byttet fnr/dnr. Dvs at fnr/dnr man har lagt inn i dekoratøren ikke er den aktive personidenten til brukeren.
> IS-3096: Show alert and modal when inaktiv personident

- src/components/pengestopp/PengestoppHistorikk.tsx
- src/data/pengestopp/types/FlaggPerson.ts
Disse har blitt nullable i backend så må håndtere at de kan være null i frontend også. 
Må merges før vi begynner å trykke automatisk på stoppknappen ved konsumering av vurderinger ([PR](https://github.com/navikt/ispengestopp/pull/161)) for at historikken på stoppknappetrykk som finnes på Sykmeldinger-siden ikke skal brekke.
> IS-3112: Make pengestopp fields nullable

- src/components/personkort/PersonkortHeader/PersonkortHeaderTags.tsx
- test/components/personkort/PersonkortHeaderTest.tsx
Iht. [Språkrådet](https://sprakradet.no/spraksporsmal-og-svar/prosentteikn-og-mellomrom/) så skal det være mellomrom mellom tall og prosenttegn
> IS-3034: Lagt til mellomrom mellom tall og prosenttegn

- src/components/utdragFraSykefravaeret/Sykmeldinger.tsx
Fikset slik at tekst for sykmeldinger er synlig hvis man skal skrive det ut.
Det er litt uheldig at det er grå tekst på løsningen, men det virker som det er noe css som jeg potensielt ikke får overstyrt (eller mer sannsynlig at jeg ikke vet hva som skal overstyres). Tenkte jeg skulle høre med Aksel. Mao. så er denne PRen litt for å i hvert fall gjøre innholdet synlig i første omgang.
Før:
Etter:
> IS-3151: Gjort sykmeldinger mer utskriftsvennlig

- src/sider/arbeidsuforhet/avslag/AvslagDatePicker.tsx
- src/sider/dialogmoter/components/DialogmoteDato.tsx
- src/sider/frisktilarbeid/VedtakFraDato.tsx
- src/sider/manglendemedvirkning/stans/StansdatoDatePicker.tsx
Lagt til ukenummer i datepickers på: 
- Dialogmøteinnkalling
- Stansdato 8-4 og 8-8
- 8-5 Friskmelding til arbeidsformidling
<details>
<summary>Sånn ser det ut etter at nummeret er lagt til i kalenderne: </summary>
</details>
> IS-3101: add ukenummer i datepickers

- src/sider/arbeidsuforhet/ArbeidsuforhetButtons.tsx
- src/sider/arbeidsuforhet/avslag/AvslagDatePicker.tsx
- src/sider/arbeidsuforhet/avslag/AvslagForm.tsx
- test/arbeidsuforhet/ForhandsvarselSendtTest.tsx
- test/arbeidsuforhet/avslag/ArbeidsuforhetAvslagTest.tsx
- test/arbeidsuforhet/avslag/AvslagFormTest.tsx
Endret tekster i skjemaet for å skrive innstilling ifm. arbeidsuførhet for å reflektere at man ikke lenger trenger å trykke manuelt på stoppknappen ettersom dette skal gjøres automatisk av backend ved innsendt innstilling.
Avhengig av: https://github.com/navikt/ispengestopp/pull/163
Satt denne som draft inntil videre, men er ferdig.
Før:
Etter:
> IS-3121: Endret tekster i skjemaet for å skrive innstilling ifm. arbeidsuførhet

- src/components/pengestopp/PengestoppModal.tsx
- test/pengestopp/PengestoppTest.tsx
Fjernet muligheten for å velge arbeidsuførhet som årsak ved bruk av stoppknappen
Relatert til (og må merges først): https://github.com/navikt/syfomodiaperson/pull/1661
Før:
Etter:
> IS-3120: Fjernet muligheten for å velge arbeidsuførhet som årsak ved bruk av stoppknappen

- src/sider/aktivitetskrav/useAktivitetskravNotificationAlert.ts
- src/sider/aktivitetskrav/vurdering/InnstillingOmStansSkjema.tsx
- src/sider/aktivitetskrav/vurdering/StansdatoDatePicker.tsx
- src/sider/aktivitetskrav/vurdering/VurderAktivitetskravTabs.tsx
- test/aktivitetskrav/vurdering/AktivitetskravForhandsvarselTest.tsx
- test/aktivitetskrav/vurdering/VurderAktivitetskravTest.tsx
Endret tekster i skjemaet for å skrive innstilling ifm. aktivitetskrav for å reflektere at man ikke lenger trenger å trykke manuelt på stoppknappen ettersom dette skal gjøres automatisk av backend ved innsendt innstilling.
Avhengig av: https://github.com/navikt/ispengestopp/pull/164
Satt denne som draft inntil videre, men er ferdig.
**Før**
Skjema:
**Etter**
Skjema:
Ved innsendt innstilling:
> IS-3132: Endret tekster i skjemaet for å skrive innstilling ifm. aktivitetskrav

- src/components/pengestopp/Pengestopp.tsx
- src/components/pengestopp/PengestoppHistorikk.tsx
- src/mocks/ispengestopp/mockIspengestopp.ts
- src/mocks/ispengestopp/pengestoppStatusMock.ts
- test/pengestopp/PengestoppTest.tsx
Fjernet modal for å stanse sykepenger ettersom aktivitetskrav var siste mulige valg.
Jeg har fjernet annen kode jeg anså som nødvendig og tenkte resten kunne slettes når dette med historikken er på plass på alle sidene ettersom denne siden er fortsatt eneste sted hvor det er mulig å se hvorvidt automatisk utbetaling er stanset tidligere.
La også inn informasjon om at det ikke finnes noen beskjeder i stedet for at det hele bare ikke vises. Dette er ment litt midlertidig så antar at det ikke skal være slik veldig lenge.
Avhengig av: https://github.com/navikt/syfomodiaperson/pull/1665
**Før**
**Etter**
Beskjeder:
Ingen beskjeder:
> IS-3130: Fjernet modal for å stanse automatisk utbetaling av sykepenger

- src/data/manglendemedvirkning/manglendeMedvirkningTypes.ts
- src/mocks/ispengestopp/pengestoppStatusMock.ts
- src/sider/manglendemedvirkning/ManglendeMedVirkningStatusItem.tsx
- src/sider/manglendemedvirkning/ManglendeMedvirkningHistorikk.tsx
- test/manglendemedvirkning/ManglendeMedvirkningHistorikkTest.tsx
Lagt til statusendringer med årsakType: `MANGLENDE_MEDVIRKING` i historikken på siden manglende medvirkning. Disse statusendringer vil komme opp som: `Melding om stans sendt`.  Alle elementer i historikken sorteres synkende på dato (nyeste øverst).
Tanken i første omgang var å høre om dette er grei nok måte å løse det på. Visningen/Informasjonen man får fra vurdering og statusendring var ganske forskjellige så virka litt unødvendig å lage en felles komponent (litt slik som Historikk er lagt opp), men kan fint gjøre det om ønskelig.
> IS-3113: Lagt til statusendringer om stans av sykepenger til under historikken på siden manglende medvirkning

- src/data/frisktilarbeid/frisktilarbeidDocumentTexts.ts
- src/hooks/frisktilarbeid/useFriskmeldingTilArbeidsformidlingDocument.ts
- test/frisktilarbeid/frisktilarbeidTestData.ts
- Fjerner meldekort informasjon fra vedtaksbrevet om friskmelding til arbeidsformidling.
- Se screenshot – Det er kun det som er innrammet i den røde firkantet som er fjernet/endret.
Før
Etter
> IS-3194: Remove meldekort from vedtakstekst

- src/mocks/oppfolgingsoppgave/historikkOppfolgingsoppgaveMock.ts
- test/historikk/HistorikkTest.tsx
Fikset tester som feilet fordi de sjekket mot hardkodede datoverdier og disse datoene havnet i forrige uke utenfor oppfølgingstilfellet definert i mocken og var derfor ikke en del av visningen på historikksiden.
> Endret tester til å sjekke mot dynamiske datoer

- test/historikk/HistorikkTest.tsx
Fikset tester som feilet fordi de sjekket mot hardkodede datoverdier og disse datoene havnet i forrige uke utenfor oppfølgingstilfellet definert i mocken og var derfor ikke en del av visningen på historikksiden.
Samme problem som ble fikset i: https://github.com/navikt/syfomodiaperson/pull/1676
> Fikset flere tester ifm. historikk til å sjekke mot dynamiske datoer

- src/components/personkort/PersonkortChangeEnhet.tsx
- src/components/personkort/PersonkortEnhet.tsx
- src/components/personkort/useChangeEnhet.tsx
- src/data/behandlendeenhet/behandlendeEnhetQueryHooks.ts
- src/data/behandlendeenhet/types/BehandlendeEnhet.ts
- src/data/behandlendeenhet/types/BehandlendeEnhetDTOs.ts
- src/mocks/syfobehandlendeenhet/behandlendeEnhetMock.ts
- src/mocks/syfobehandlendeenhet/mockSyfobehandlendeenhet.ts
- test/components/personkort/PersonkortEnhetTest.tsx
- test/components/personkort/PersonkortVisningTest.tsx
- test/data/behandlendeEnhetQueryHooksTest.tsx
- test/stubs/stubSyfobehandlendeEnhet.ts
Fjernet bruk av `/person` endepunktet og byttet ut med `/oppfolgingsenhet-tildelinger`.
To visuelle endringer her: 
Nr 1: La på hva som er den geografiske enheten i knappen, slik at dette er synlig før man gjør flyttingen. Dette skal nok uansett endres på etterhvert, så tenker det er en forbedring uten for mye risiko.
Nr 2: Viser feilmelding når noe går galt, og lukker ikke modalen med en gang kallet går:
> IS-3171: Use new endpoint for tildeling of oppfolgingsenhet

- src/mocks/syfosmregister/sykmeldingerMock.ts
- src/utils/sykmeldinger/sykmeldingUtils.ts
- test/utils/sykmeldingUtilsTest.ts
Fikset slik at nøkkelinfo ikke inkluderer sykmeldinger som er avvist av Nav, hverken i grafen eller i opplistingen nedenfor. Men hvis man velger "Sykmeldinger" i menyen vil man fortsatt kunne se avviste sykmeldinger.
> IS-3247: Filter invalid sykmelding

- src/apiConstants.ts
- src/data/motebehov/motebehovQueryHooks.ts
- src/data/motebehov/types/motebehovTypes.ts
- src/hooks/historikk/useMotebehovHistorikk.ts
- src/mocks/syfomotebehov/motebehovMock.ts
- src/sider/dialogmoter/motebehov/MotebehovKvittering.tsx
- src/sider/dialogmoter/motebehov/MotebehovKvitteringInnhold.tsx
- src/sider/dialogmoter/motebehov/skjema/CheckboxSvar.tsx
- src/sider/dialogmoter/motebehov/skjema/MotebehovSkjemasvar.tsx
- src/sider/dialogmoter/motebehov/skjema/RadioGroupSvar.tsx
- src/sider/dialogmoter/motebehov/skjema/TextSvar.tsx
- src/utils/motebehovUtils.ts
- test/containers/MotelandingssideContainerTest.tsx
- test/dialogmote/Motebehov/DialogmoteOnskePanelTest.tsx
- test/dialogmote/Motebehov/MotebehovKvitteringTest.tsx
- test/dialogmote/MotebehovHistorikkTest.tsx
- test/utils/motebehovUtilsTest.ts
Tatt i bruk nytt endepunkt for møtebehov. Nye som leveres og fremvises:
- Ønske om at sykmelder er tilstede og begrunnelse
- Ønske om tolk og begrunnelse
Mye av endringene er relatert til nye typer og mocking av korrekte data (iht. hva som faktisk er forventet å få av respons). APIet leverer informasjonen på to forskjellige format: 
- Flatt (samme som i dag, men ligger i `MotebehovFormValuesOutputDTO`) 
- Liste med skjemaelementer (inkl. selve spørsmålet og svaret, se `FormSnapshot` og subklasser av `FieldSnapshot`
Det er det siste som er implementert i PRen. Som betyr at spørsmål og svar presenteres som et skjema slik brukeren så det, men visningen er ikke identisk. 
Denne kan ikke merges før esyfo prodsetter ny løsning
> IS-3168: Tatt i bruk nytt endepunkt for møtebehov og lagt til visning av nye felter

- src/data/navbruker/types/BrukerinfoDTO.ts
- src/sider/dialogmoter/Motelandingsside.tsx
- src/sider/dialogmoter/motebehov/InfoOmTolk.tsx
- src/utils/motebehovUtils.ts
- test/dialogmote/Motebehov/InfoOmTolkTest.tsx
Lagt til en egen boks med informasjon om hvor veileder kan oppdatere informasjon om tolk for den sykmeldte. Denne boksen vises hvis det ikke er registrert noe informasjon om tolk på den sykmeldte i pdl og det er ytret ønske om tolk fra den sykmeldte og/eller arbeidsgiver
Fortsettelse av https://github.com/navikt/syfomodiaperson/pull/1694, men ble skilt ut ettersom det ikke hastet.
> IS-3168: Lagt til informasjon om hvor det er mulig å oppdatere informasjon om tolk for sykmeldt

- src/sider/frisktilarbeid/VedtakFattet.tsx
- test/frisktilarbeid/FriskmeldingTilArbeidsformidlingTest.tsx
- Endrer tekst på knapp fra "Avslutt oppgave" til "Fjern oppgaven fra oversikten" for å forhåpentligvis gjøre det enklere for veileder å forstå hva som skjer når de trykker på knappen. Vi ønsker ikke at de skal tro at de avslutter selve vedtaket.
Før
Etter
> IS-3229: Change text and button for removing oppgave from oversikt

- src/components/motebehov/BehandleMotebehovKnapp.tsx
Endret tekst som sendes til arbeidsgiver eller sykmeldt ved innmeldt møtebehov. Ettersom teksten inneholder info som sier noe om at veileder allerede har snakket med innmelder, så ble Stine og jeg enige om å legge på en Ny-tag og å gjøre ReadMore-komponenten default-åpen slik at veilederne får dette med seg.
EDIT: Flyttet Ny-tagen opp på headeren til ReadMore-elementet.
> IS-3287: Change text for tilbakemelding and add Ny-tag

- src/components/document/DocumentComponentVisning.tsx
- src/data/frisktilarbeid/frisktilarbeidDocumentTexts.ts
- src/hooks/frisktilarbeid/useFriskmeldingTilArbeidsformidlingDocument.ts
- test/frisktilarbeid/frisktilarbeidTestData.ts
Endret tekster i 8-5 brevet
Venter på avklaring av:
Før ([vedtak-om-friskmelding-til-arbeidsformidling-gammel.pdf](https://github.com/user-attachments/files/20571566/vedtak-om-friskmelding-til-arbeidsformidling-gammel.pdf)):
Etter ([vedtak-om-friskmelding-til-arbeidsformidling-ny.pdf](https://github.com/user-attachments/files/20571593/vedtak-om-friskmelding-til-arbeidsformidling-ny.pdf)):
> IS-3297: Endret tekster i 8-5 brevet

- src/sider/dialogmoter/hooks/dialogmoteTexts.ts
- Endrer tekst som blir med dialogmøte referat om man huker av for at man har opplyst
https://github.com/user-attachments/assets/e7654d29-fa00-4c6e-a70b-cdeea2bd3a99
> IS-3321: Endre DM referat standardtekst om okonomisk stotte

- src/components/personkort/PersonkortHeader/KjonnIkon.tsx
- src/components/personkort/PersonkortHeader/NavnHeader.tsx
- src/components/personkort/PersonkortHeader/PersonkortHeader.tsx
- src/data/navbruker/navbrukerQueryHooks.ts
- src/data/navbruker/types/BrukerinfoDTO.ts
- src/konstanter.ts
- src/mocks/syfoperson/persondataMock.ts
- src/utils/fnrUtils.ts
- test/utils/fnrUtilsTest.js
Ingen synlig endring, men alder og kjønn skal nå vises basert på responsen fra PDL i stedet for å bli kalkulert fra personident'en.
> IS-2700: Hente kjønn og fødselsdato fra PDL

- src/components/side/tildeltveileder/TildeltVeileder.tsx
- src/data/veilederbrukerknytning/useGetVeilederBrukerKnytning.tsx
- src/data/veilederinfo/veilederinfoQueryHooks.ts
- src/hooks/historikk/useVeilederTildelingHistorikk.ts
- src/mocks/syfooversiktsrv/mockSyfooversiktsrv.ts
- src/sider/historikk/Historikk.tsx
- Legger til støtte for å vise historikk på når sykmeldt har blitt satt som ufordelt.
Før
Etter
> IS-3330: Stotte for å vise fordeling til ufordelt på historikk

- src/sider/frisktilarbeid/FriskmeldingTilArbeidsformidling.tsx
- src/sider/frisktilarbeid/FriskmeldingTilArbeidsformidlingSide.tsx
- src/sider/frisktilarbeid/NyttVedtak.tsx
- src/sider/frisktilarbeid/VedtakFattet.tsx
- src/sider/frisktilarbeid/VedtakInfoPanel.tsx
- test/frisktilarbeid/FriskmeldingTilArbeidsformidlingTest.tsx
- test/frisktilarbeid/VedtakFattetTest.tsx
- Forbedre kvitteringsside for 8-5 etter man har fattet vedtak
- Legger til visningspanel for vedtak som brukes både på kvitteringsside, og når veileder har lukket oppgaven.
- Legger på at notification alerts kan lukkes.
Før
Aktivt vedtak
https://github.com/user-attachments/assets/4e359bdd-f7e9-47e7-8ae5-85ac766114f2
Utgått vedtak
https://github.com/user-attachments/assets/871237f6-e2ec-4e92-883f-8e7bab5c9e43
Etter
Aktivt vedtak
https://github.com/user-attachments/assets/44cc469a-ab53-4cea-a19b-19bcfa4e186c
Ikke lenger aktivt vedtak
https://github.com/user-attachments/assets/599040ec-cc2c-458b-8489-d1f8bbb8728c
> IS-3353: Forbedre kvitteringsside etter fattet 8-5 vedtak

- src/sider/arbeidsuforhet/VelgVurdering.tsx
- Gjør funksjonalitet for å vurdere oppfylt uten å sende forhåndsvarsel på arbeidsuførhet 8-4 vurdering tilgjengelig for alle.
Slik vil det vises for alle som ikke har tilgang til "Avslag uten forhåndsvarsel" -funksjonalitet
> IS-3378-2: Gjor oppfylt arbeidsuforhet vurdering tilgjengelig for alle

- src/data/oppfolgingsenhet/useGetMuligeOppfolgingsenheter.tsx
Sender med personident slik at backend kan finne geografisk enhet og legge den til i lista over mulige oppfølgingsenheter (dette er relevant når noen skal sendes tilbake både fra Nav utland og fra ROE).
Ref https://github.com/navikt/syfobehandlendeenhet/pull/226
> IS-3419: Sende med personident for mulige oppfolgingsenheter

- src/sider/arbeidsuforhet/NyVurdering.tsx
Endret teksten for å kunne starte ny 8.4 vurdering slik at den passer både for pilotkontor og resten av kontorene. 
Før:
Nå:
> IS-3454: endre start ny vurdering 8.4 tekst
